FC=fxtran-f90 --config $(SRC)/fxtran.conf -- \
   ifort -convert big_endian -assume byterecl -align array64byte,all -traceback \
  -fpic -qopenmp -qopenmp-threadprivate compat -fp-model source \
  -ftz -diag-disable=remark,cpu-dispatch -qopt-report=5 -qopt-report-phase=vec \
  -g -O2 -march=core-avx2 -finline-functions -finline-limit=500 -Winline \
  -qopt-prefetch=4 -fast-transcendentals -fimf-use-svml -no-fma
LIBS=-L/home/gmap/mrpm/khatib/opt/gcc/14.1.0/mkl_serv_intel_cpu_true -ltrick -qmkl=sequential -Wl,-rpath,/home/gmap/mrpm/khatib/opt/gcc/14.1.0/mkl_serv_intel_cpu_true

