MODULE PARKIND1

INTEGER, PARAMETER :: JPLM = 4
INTEGER, PARAMETER :: JPIM = 4
INTEGER, PARAMETER :: JPRM = 4

#ifdef PARKIND1_SINGLE
INTEGER, PARAMETER :: JPRB = 4
#else
INTEGER, PARAMETER :: JPRB = 8
#endif

INTEGER, PARAMETER :: JPRD = 8
INTEGER, PARAMETER :: JPIB = 8
INTEGER, PARAMETER :: JPIA = 8

END 
