!> geometry derived type for the IFS model
!> separated from geometry_mod to break dependency issues with sugeometry

MODULE TYPE_GEOMETRY

!$ACDC methods --skip-components GEOMETRY%YRCSGEOMAD,GEOMETRY%YRGSGEOMAD,GEOMETRY%YROROG,GEOMETRY%YROROG_B,GEOMETRY%YRCSGEOMAD_NB,GEOMETRY%YRGSGEOMAD_NB,GEOMETRY%YRCSGEOM_NB,GEOMETRY%YRCSGEOM,GEOMETRY%YRCSGEOM_B,GEOMETRY%YRGSGEOM_NB,GEOMETRY%YRGSGEOM,GEOMETRY%YRGSGEOM_B,GEOMETRY%YRGEOMVARS,GEOMETRY%YRATLAS,GEOMETRY%YRELBC_GEO,GEOMETRY%YSPGEOM

USE YOMVERT    , ONLY : TVAB, TVETA, TVFE, TVERTICAL_GEOM
USE YOMSTA     , ONLY : TSTA
USE YOMLAP     , ONLY : TLAP
USE YOMLEG     , ONLY : TCSGLEG
USE YOMDIM     , ONLY : TDIM
USE YOMDIMV    , ONLY : TDIMV
USE YOMMP      , ONLY : TMP
USE YOMGEM     , ONLY : TGEM
USE TYPE_SPGEOM, ONLY : TSPGEOM
USE YEMDIM     , ONLY : TEDIM
USE YEMGEO     , ONLY : TEGEO
USE YEMMP      , ONLY : TEMMP
USE YEMLAP     , ONLY : TLEP
USE YEMGSL     , ONLY : TEGSL
USE YOMCVER , ONLY : TCVER


IMPLICIT NONE 

PRIVATE

TYPE, PUBLIC :: GEOMETRY
  LOGICAL          :: LNHX_GEOM
  TYPE(TVERTICAL_GEOM) :: YRVERT_GEOM

  TYPE(TSTA)    :: YRSTA
  TYPE(TLAP)    :: YRLAP
  TYPE(TCSGLEG) :: YRCSGLEG

  TYPE(TDIM)    :: YRDIM
  TYPE(TDIMV)   :: YRDIMV
  TYPE(TMP)     :: YRMP
  TYPE(TGEM)    :: YRGEM

  LOGICAL                    :: AD_GEOM = .FALSE.
  TYPE(TSPGEOM) :: YSPGEOM

  TYPE(TVAB)    :: YVABIO ! I/O full vertical hybrid coordinates 0->NIOLEVG (NIOLEVG >=NFLEVG)

  ! LAM specific objects
  TYPE(TEDIM) :: YREDIM
  TYPE(TEGEO) :: YREGEO
  TYPE(TEMMP) :: YREMP
  TYPE(TLEP)  :: YRELAP
  TYPE(TEGSL) :: YREGSL

END TYPE GEOMETRY

END MODULE TYPE_GEOMETRY
