MODULE UTIL_TDYNA_MOD

USE YOMDYNA, ONLY : TDYNA

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDYNA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDYNA
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDYNA
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDYNA
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TDYNA (SELF, KLUN)
USE UTIL_TGFLT_MOD
USE UTIL_TGMVT_MOD
USE UTIL_TTND_MOD
IMPLICIT NONE
TYPE (TDYNA), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LNHEE
WRITE (KLUN) SELF%LNHQE
WRITE (KLUN) SELF%LNHHY
WRITE (KLUN) SELF%LNHDYN
WRITE (KLUN) SELF%LSACC
WRITE (KLUN) SELF%LSPRT
WRITE (KLUN) SELF%LTWOTL
WRITE (KLUN) SELF%LSLAG
WRITE (KLUN) SELF%NPDVAR
WRITE (KLUN) SELF%NVDVAR
WRITE (KLUN) SELF%NTPVAR
WRITE (KLUN) SELF%ND4SYS
WRITE (KLUN) SELF%LNHX
WRITE (KLUN) SELF%LSPNHX
WRITE (KLUN) SELF%LNHXDER
WRITE (KLUN) SELF%LGWADV
WRITE (KLUN) SELF%NGWADVSI
WRITE (KLUN) SELF%LRDBBC
WRITE (KLUN) SELF%LSI_NHEE
WRITE (KLUN) SELF%LSLHD
WRITE (KLUN) SELF%LSLHD_W
WRITE (KLUN) SELF%LSLHD_T
WRITE (KLUN) SELF%LSLHD_SPD
WRITE (KLUN) SELF%LSLHD_SVD
WRITE (KLUN) SELF%LSLHD_GFL
WRITE (KLUN) SELF%LSLHD_OLD
WRITE (KLUN) SELF%LSLHD_STATIC
WRITE (KLUN) SELF%LSLHDQUAD
WRITE (KLUN) SELF%SLHDKMIN
WRITE (KLUN) SELF%SLHDKMAX
WRITE (KLUN) SELF%SLHDKREF
WRITE (KLUN) SELF%SLHDEPSH
WRITE (KLUN) SELF%SLHDEPSV
WRITE (KLUN) SELF%LSLVF
WRITE (KLUN) SELF%SLVFEPS
WRITE (KLUN) SELF%P_SLVF_BOT
WRITE (KLUN) SELF%SLVFMIN
WRITE (KLUN) SELF%SLVFTR
WRITE (KLUN) SELF%P_SLVF_TR
WRITE (KLUN) SELF%LGRADSP
WRITE (KLUN) SELF%LPGFSF
WRITE (KLUN) SELF%LPGREUSE
WRITE (KLUN) SELF%LPGFTEST
WRITE (KLUN) SELF%L3DTURB
WRITE (KLUN) SELF%LSLDIA
WRITE (KLUN) SELF%LRPRSLTRJ
WRITE (KLUN) SELF%NQMGMV
WRITE (KLUN) SELF%NQMGFL
WRITE (KLUN) SELF%LRALTVDISP
WRITE (KLUN) SELF%LVSPLIP
WRITE (KLUN) SELF%LRHSVWENO
WRITE (KLUN) SELF%LCOMAD
WRITE (KLUN) SELF%LCOMADH
WRITE (KLUN) SELF%LCOMADV
WRITE (KLUN) SELF%LCOMAD_W
WRITE (KLUN) SELF%LCOMAD_T
WRITE (KLUN) SELF%LCOMAD_SPD
WRITE (KLUN) SELF%LCOMAD_SVD
WRITE (KLUN) SELF%LCOMAD_SP
WRITE (KLUN) SELF%LCOMAD_GFL
WRITE (KLUN) SELF%LNESCT
WRITE (KLUN) SELF%LNESCV
WRITE (KLUN) SELF%LNESC
WRITE (KLUN) SELF%LSETTLST
WRITE (KLUN) SELF%LSETTLSV
WRITE (KLUN) SELF%LSETTLS
WRITE (KLUN) SELF%LELTRA
WRITE (KLUN) SELF%LSLINLC2
WRITE (KLUN) SELF%LSLINL
WRITE (KLUN) SELF%LHOISLT
WRITE (KLUN) SELF%HOISLTV
WRITE (KLUN) SELF%HOISLTH
WRITE (KLUN) SELF%LSLTVWENO
WRITE (KLUN) SELF%LRUBC
WRITE (KLUN) SELF%LBIGW
WRITE (KLUN) SELF%LPC_FULL
WRITE (KLUN) SELF%LPC_CHEAP
WRITE (KLUN) SELF%LPC_CHEAP2
WRITE (KLUN) SELF%LPC_SPHY
WRITE (KLUN) SELF%LMIXETTLS
WRITE (KLUN) SELF%LMIXETTLS_PRINT
WRITE (KLUN) SELF%RMIXNL_TRH
WRITE (KLUN) SELF%LSI_UPDATE_FULL
WRITE (KLUN) SELF%LSI_UPDATE_CHEAP
WRITE (KLUN) SELF%L_RDRY_VD
WRITE (KLUN) SELF%L_RDRY_NHX
WRITE (KLUN) SELF%LHYQE_BLEND
WRITE (KLUN) SELF%TSTART_BLEND
WRITE (KLUN) SELF%TSTOP_BLEND
WRITE (KLUN) SELF%LNHQE_BALANCE
WRITE (KLUN) SELF%LNHQE_LASTSI
WRITE (KLUN) SELF%LNHQE_CSVTRMO
WRITE (KLUN) SELF%RNHQE_DELTA
WRITE (KLUN) SELF%LNHHY_VERTIC
WRITE (KLUN) SELF%LNHHY_BALANCE
WRITE (KLUN) SELF%RNHHY_DELTA
WRITE (KLUN) SELF%RNHHY_TAUD
WRITE (KLUN) SELF%RNHHY_TAUX
CALL SAVE_TTND (SELF%YYTTND, KLUN)
CALL SAVE_TGMVT (SELF%YYTGMVT95, KLUN)
CALL SAVE_TGFLT (SELF%YYTGFLT95, KLUN)
END SUBROUTINE

SUBROUTINE LOAD_TDYNA (SELF, KLUN)
USE UTIL_TGFLT_MOD
USE UTIL_TGMVT_MOD
USE UTIL_TTND_MOD
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TDYNA), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) SELF%LNHEE
READ (KLUN) SELF%LNHQE
READ (KLUN) SELF%LNHHY
READ (KLUN) SELF%LNHDYN
READ (KLUN) SELF%LSACC
READ (KLUN) SELF%LSPRT
READ (KLUN) SELF%LTWOTL
READ (KLUN) SELF%LSLAG
READ (KLUN) SELF%NPDVAR
READ (KLUN) SELF%NVDVAR
READ (KLUN) SELF%NTPVAR
READ (KLUN) SELF%ND4SYS
READ (KLUN) SELF%LNHX
READ (KLUN) SELF%LSPNHX
READ (KLUN) SELF%LNHXDER
READ (KLUN) SELF%LGWADV
READ (KLUN) SELF%NGWADVSI
READ (KLUN) SELF%LRDBBC
READ (KLUN) SELF%LSI_NHEE
READ (KLUN) SELF%LSLHD
READ (KLUN) SELF%LSLHD_W
READ (KLUN) SELF%LSLHD_T
READ (KLUN) SELF%LSLHD_SPD
READ (KLUN) SELF%LSLHD_SVD
READ (KLUN) SELF%LSLHD_GFL
READ (KLUN) SELF%LSLHD_OLD
READ (KLUN) SELF%LSLHD_STATIC
READ (KLUN) SELF%LSLHDQUAD
READ (KLUN) ZTMP0
SELF%SLHDKMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDKMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDKREF = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDEPSH = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDEPSV = ZTMP0
READ (KLUN) SELF%LSLVF
READ (KLUN) ZTMP0
SELF%SLVFEPS = ZTMP0
READ (KLUN) ZTMP0
SELF%P_SLVF_BOT = ZTMP0
READ (KLUN) ZTMP0
SELF%SLVFMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%SLVFTR = ZTMP0
READ (KLUN) ZTMP0
SELF%P_SLVF_TR = ZTMP0
READ (KLUN) SELF%LGRADSP
READ (KLUN) SELF%LPGFSF
READ (KLUN) SELF%LPGREUSE
READ (KLUN) SELF%LPGFTEST
READ (KLUN) SELF%L3DTURB
READ (KLUN) SELF%LSLDIA
READ (KLUN) SELF%LRPRSLTRJ
READ (KLUN) SELF%NQMGMV
READ (KLUN) SELF%NQMGFL
READ (KLUN) SELF%LRALTVDISP
READ (KLUN) SELF%LVSPLIP
READ (KLUN) SELF%LRHSVWENO
READ (KLUN) SELF%LCOMAD
READ (KLUN) SELF%LCOMADH
READ (KLUN) SELF%LCOMADV
READ (KLUN) SELF%LCOMAD_W
READ (KLUN) SELF%LCOMAD_T
READ (KLUN) SELF%LCOMAD_SPD
READ (KLUN) SELF%LCOMAD_SVD
READ (KLUN) SELF%LCOMAD_SP
READ (KLUN) SELF%LCOMAD_GFL
READ (KLUN) SELF%LNESCT
READ (KLUN) SELF%LNESCV
READ (KLUN) SELF%LNESC
READ (KLUN) SELF%LSETTLST
READ (KLUN) SELF%LSETTLSV
READ (KLUN) SELF%LSETTLS
READ (KLUN) SELF%LELTRA
READ (KLUN) SELF%LSLINLC2
READ (KLUN) SELF%LSLINL
READ (KLUN) SELF%LHOISLT
READ (KLUN) ZTMP0
SELF%HOISLTV = ZTMP0
READ (KLUN) ZTMP0
SELF%HOISLTH = ZTMP0
READ (KLUN) SELF%LSLTVWENO
READ (KLUN) SELF%LRUBC
READ (KLUN) SELF%LBIGW
READ (KLUN) SELF%LPC_FULL
READ (KLUN) SELF%LPC_CHEAP
READ (KLUN) SELF%LPC_CHEAP2
READ (KLUN) SELF%LPC_SPHY
READ (KLUN) SELF%LMIXETTLS
READ (KLUN) SELF%LMIXETTLS_PRINT
READ (KLUN) ZTMP0
SELF%RMIXNL_TRH = ZTMP0
READ (KLUN) SELF%LSI_UPDATE_FULL
READ (KLUN) SELF%LSI_UPDATE_CHEAP
READ (KLUN) SELF%L_RDRY_VD
READ (KLUN) SELF%L_RDRY_NHX
READ (KLUN) SELF%LHYQE_BLEND
READ (KLUN) ZTMP0
SELF%TSTART_BLEND = ZTMP0
READ (KLUN) ZTMP0
SELF%TSTOP_BLEND = ZTMP0
READ (KLUN) SELF%LNHQE_BALANCE
READ (KLUN) SELF%LNHQE_LASTSI
READ (KLUN) SELF%LNHQE_CSVTRMO
READ (KLUN) ZTMP0
SELF%RNHQE_DELTA = ZTMP0
READ (KLUN) SELF%LNHHY_VERTIC
READ (KLUN) SELF%LNHHY_BALANCE
READ (KLUN) ZTMP0
SELF%RNHHY_DELTA = ZTMP0
READ (KLUN) ZTMP0
SELF%RNHHY_TAUD = ZTMP0
READ (KLUN) ZTMP0
SELF%RNHHY_TAUX = ZTMP0
CALL LOAD_TTND (SELF%YYTTND, KLUN)
CALL LOAD_TGMVT (SELF%YYTGMVT95, KLUN)
CALL LOAD_TGFLT (SELF%YYTGFLT95, KLUN)
END SUBROUTINE


SUBROUTINE COPY_TDYNA (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_TGFLT_MOD
USE UTIL_TGMVT_MOD
USE UTIL_TTND_MOD
IMPLICIT NONE
TYPE (TDYNA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

CALL COPY_TTND (SELF%YYTTND, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TGMVT (SELF%YYTGMVT95, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TGFLT (SELF%YYTGFLT95, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE



     



SUBROUTINE WIPE_TDYNA (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_TGFLT_MOD
USE UTIL_TGMVT_MOD
USE UTIL_TTND_MOD
IMPLICIT NONE
TYPE (TDYNA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

CALL WIPE_TTND (SELF%YYTTND, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TGMVT (SELF%YYTGMVT95, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TGFLT (SELF%YYTGFLT95, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
