MODULE UTIL_TEAERC_TEGEN_MOD

USE YOEAERC_TEGEN, ONLY : TEAERC_TEGEN

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEAERC_TEGEN
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEAERC_TEGEN
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEAERC_TEGEN
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEAERC_TEGEN
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEAERC_TEGEN (SELF, KLUN)

IMPLICIT NONE
TYPE (TEAERC_TEGEN), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV
WRITE (KLUN) SELF%REPAER
LRAERBC = ASSOCIATED (SELF%RAERBC)
WRITE (KLUN) LRAERBC
IF (LRAERBC) THEN
  WRITE (KLUN) LBOUND (SELF%RAERBC)
  WRITE (KLUN) UBOUND (SELF%RAERBC)
  WRITE (KLUN) SELF%RAERBC
ENDIF
LRAEROR = ASSOCIATED (SELF%RAEROR)
WRITE (KLUN) LRAEROR
IF (LRAEROR) THEN
  WRITE (KLUN) LBOUND (SELF%RAEROR)
  WRITE (KLUN) UBOUND (SELF%RAEROR)
  WRITE (KLUN) SELF%RAEROR
ENDIF
LRAERSD = ASSOCIATED (SELF%RAERSD)
WRITE (KLUN) LRAERSD
IF (LRAERSD) THEN
  WRITE (KLUN) LBOUND (SELF%RAERSD)
  WRITE (KLUN) UBOUND (SELF%RAERSD)
  WRITE (KLUN) SELF%RAERSD
ENDIF
LRAERSS = ASSOCIATED (SELF%RAERSS)
WRITE (KLUN) LRAERSS
IF (LRAERSS) THEN
  WRITE (KLUN) LBOUND (SELF%RAERSS)
  WRITE (KLUN) UBOUND (SELF%RAERSS)
  WRITE (KLUN) SELF%RAERSS
ENDIF
LRAERSU = ASSOCIATED (SELF%RAERSU)
WRITE (KLUN) LRAERSU
IF (LRAERSU) THEN
  WRITE (KLUN) LBOUND (SELF%RAERSU)
  WRITE (KLUN) UBOUND (SELF%RAERSU)
  WRITE (KLUN) SELF%RAERSU
ENDIF
LRAERV = ASSOCIATED (SELF%RAERV)
WRITE (KLUN) LRAERV
IF (LRAERV) THEN
  WRITE (KLUN) LBOUND (SELF%RAERV)
  WRITE (KLUN) UBOUND (SELF%RAERV)
  WRITE (KLUN) SELF%RAERV
ENDIF
LRLATV = ASSOCIATED (SELF%RLATV)
WRITE (KLUN) LRLATV
IF (LRLATV) THEN
  WRITE (KLUN) LBOUND (SELF%RLATV)
  WRITE (KLUN) UBOUND (SELF%RLATV)
  WRITE (KLUN) SELF%RLATV
ENDIF
WRITE (KLUN) SELF%RTAEBC
WRITE (KLUN) SELF%RTAEOR
WRITE (KLUN) SELF%RTAESD
WRITE (KLUN) SELF%RTAESS
WRITE (KLUN) SELF%RTAESU
WRITE (KLUN) SELF%RTAEVO
WRITE (KLUN) SELF%ISYEAR
WRITE (KLUN) SELF%IEYEAR
WRITE (KLUN) SELF%IS_INITIALISED
END SUBROUTINE

SUBROUTINE LOAD_TEAERC_TEGEN (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TEAERC_TEGEN), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL3(3), IU3(3)
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
READ (KLUN) ZTMP0
SELF%REPAER = ZTMP0
READ (KLUN) LRAERBC
IF (LRAERBC) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RAERBC (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RAERBC,1):UBOUND(SELF%RAERBC,1), LBOUND(SELF%RAERBC,2):UBOUND(SELF%RAERBC,2), LBOUND(SELF%RAERBC,3):UBOUND(SELF%RAERBC,3)))
  READ (KLUN) ZTMP3
  SELF%RAERBC = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (SELF%RAERBC)
ENDIF
READ (KLUN) LRAEROR
IF (LRAEROR) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RAEROR (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RAEROR,1):UBOUND(SELF%RAEROR,1), LBOUND(SELF%RAEROR,2):UBOUND(SELF%RAEROR,2), LBOUND(SELF%RAEROR,3):UBOUND(SELF%RAEROR,3)))
  READ (KLUN) ZTMP3
  SELF%RAEROR = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (SELF%RAEROR)
ENDIF
READ (KLUN) LRAERSD
IF (LRAERSD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RAERSD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RAERSD,1):UBOUND(SELF%RAERSD,1), LBOUND(SELF%RAERSD,2):UBOUND(SELF%RAERSD,2), LBOUND(SELF%RAERSD,3):UBOUND(SELF%RAERSD,3)))
  READ (KLUN) ZTMP3
  SELF%RAERSD = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (SELF%RAERSD)
ENDIF
READ (KLUN) LRAERSS
IF (LRAERSS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RAERSS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RAERSS,1):UBOUND(SELF%RAERSS,1), LBOUND(SELF%RAERSS,2):UBOUND(SELF%RAERSS,2), LBOUND(SELF%RAERSS,3):UBOUND(SELF%RAERSS,3)))
  READ (KLUN) ZTMP3
  SELF%RAERSS = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (SELF%RAERSS)
ENDIF
READ (KLUN) LRAERSU
IF (LRAERSU) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RAERSU (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RAERSU,1):UBOUND(SELF%RAERSU,1), LBOUND(SELF%RAERSU,2):UBOUND(SELF%RAERSU,2), LBOUND(SELF%RAERSU,3):UBOUND(SELF%RAERSU,3)))
  READ (KLUN) ZTMP3
  SELF%RAERSU = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (SELF%RAERSU)
ENDIF
READ (KLUN) LRAERV
IF (LRAERV) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RAERV (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RAERV,1):UBOUND(SELF%RAERV,1), LBOUND(SELF%RAERV,2):UBOUND(SELF%RAERV,2), LBOUND(SELF%RAERV,3):UBOUND(SELF%RAERV,3)))
  READ (KLUN) ZTMP3
  SELF%RAERV = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (SELF%RAERV)
ENDIF
READ (KLUN) LRLATV
IF (LRLATV) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RLATV (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RLATV,1):UBOUND(SELF%RLATV,1)))
  READ (KLUN) ZTMP1
  SELF%RLATV = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (SELF%RLATV)
ENDIF
ALLOCATE (ZTMP2(LBOUND(SELF%RTAEBC,1):UBOUND(SELF%RTAEBC,1), LBOUND(SELF%RTAEBC,2):UBOUND(SELF%RTAEBC,2)))
READ (KLUN) ZTMP2
SELF%RTAEBC = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(SELF%RTAEOR,1):UBOUND(SELF%RTAEOR,1), LBOUND(SELF%RTAEOR,2):UBOUND(SELF%RTAEOR,2)))
READ (KLUN) ZTMP2
SELF%RTAEOR = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(SELF%RTAESD,1):UBOUND(SELF%RTAESD,1), LBOUND(SELF%RTAESD,2):UBOUND(SELF%RTAESD,2)))
READ (KLUN) ZTMP2
SELF%RTAESD = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(SELF%RTAESS,1):UBOUND(SELF%RTAESS,1), LBOUND(SELF%RTAESS,2):UBOUND(SELF%RTAESS,2)))
READ (KLUN) ZTMP2
SELF%RTAESS = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(SELF%RTAESU,1):UBOUND(SELF%RTAESU,1), LBOUND(SELF%RTAESU,2):UBOUND(SELF%RTAESU,2)))
READ (KLUN) ZTMP2
SELF%RTAESU = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP1(LBOUND(SELF%RTAEVO,1):UBOUND(SELF%RTAEVO,1)))
READ (KLUN) ZTMP1
SELF%RTAEVO = ZTMP1
DEALLOCATE (ZTMP1)
READ (KLUN) SELF%ISYEAR
READ (KLUN) SELF%IEYEAR
READ (KLUN) SELF%IS_INITIALISED
END SUBROUTINE


SUBROUTINE COPY_TEAERC_TEGEN (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEAERC_TEGEN), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LRAERBC = ASSOCIATED (SELF%RAERBC)
IF (LRAERBC) THEN
  !$ACC ENTER DATA CREATE (SELF%RAERBC)
  !$ACC UPDATE DEVICE (SELF%RAERBC)
  !$ACC ENTER DATA ATTACH (SELF%RAERBC)
ENDIF

LRAEROR = ASSOCIATED (SELF%RAEROR)
IF (LRAEROR) THEN
  !$ACC ENTER DATA CREATE (SELF%RAEROR)
  !$ACC UPDATE DEVICE (SELF%RAEROR)
  !$ACC ENTER DATA ATTACH (SELF%RAEROR)
ENDIF

LRAERSD = ASSOCIATED (SELF%RAERSD)
IF (LRAERSD) THEN
  !$ACC ENTER DATA CREATE (SELF%RAERSD)
  !$ACC UPDATE DEVICE (SELF%RAERSD)
  !$ACC ENTER DATA ATTACH (SELF%RAERSD)
ENDIF

LRAERSS = ASSOCIATED (SELF%RAERSS)
IF (LRAERSS) THEN
  !$ACC ENTER DATA CREATE (SELF%RAERSS)
  !$ACC UPDATE DEVICE (SELF%RAERSS)
  !$ACC ENTER DATA ATTACH (SELF%RAERSS)
ENDIF

LRAERSU = ASSOCIATED (SELF%RAERSU)
IF (LRAERSU) THEN
  !$ACC ENTER DATA CREATE (SELF%RAERSU)
  !$ACC UPDATE DEVICE (SELF%RAERSU)
  !$ACC ENTER DATA ATTACH (SELF%RAERSU)
ENDIF

LRAERV = ASSOCIATED (SELF%RAERV)
IF (LRAERV) THEN
  !$ACC ENTER DATA CREATE (SELF%RAERV)
  !$ACC UPDATE DEVICE (SELF%RAERV)
  !$ACC ENTER DATA ATTACH (SELF%RAERV)
ENDIF

LRLATV = ASSOCIATED (SELF%RLATV)
IF (LRLATV) THEN
  !$ACC ENTER DATA CREATE (SELF%RLATV)
  !$ACC UPDATE DEVICE (SELF%RLATV)
  !$ACC ENTER DATA ATTACH (SELF%RLATV)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TEAERC_TEGEN (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEAERC_TEGEN), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LRAERBC = ASSOCIATED (SELF%RAERBC)
IF (LRAERBC) THEN
  !$ACC EXIT DATA DETACH (SELF%RAERBC)
  !$ACC EXIT DATA DETACH (SELF%RAERBC)
ENDIF

LRAEROR = ASSOCIATED (SELF%RAEROR)
IF (LRAEROR) THEN
  !$ACC EXIT DATA DETACH (SELF%RAEROR)
  !$ACC EXIT DATA DETACH (SELF%RAEROR)
ENDIF

LRAERSD = ASSOCIATED (SELF%RAERSD)
IF (LRAERSD) THEN
  !$ACC EXIT DATA DETACH (SELF%RAERSD)
  !$ACC EXIT DATA DETACH (SELF%RAERSD)
ENDIF

LRAERSS = ASSOCIATED (SELF%RAERSS)
IF (LRAERSS) THEN
  !$ACC EXIT DATA DETACH (SELF%RAERSS)
  !$ACC EXIT DATA DETACH (SELF%RAERSS)
ENDIF

LRAERSU = ASSOCIATED (SELF%RAERSU)
IF (LRAERSU) THEN
  !$ACC EXIT DATA DETACH (SELF%RAERSU)
  !$ACC EXIT DATA DETACH (SELF%RAERSU)
ENDIF

LRAERV = ASSOCIATED (SELF%RAERV)
IF (LRAERV) THEN
  !$ACC EXIT DATA DETACH (SELF%RAERV)
  !$ACC EXIT DATA DETACH (SELF%RAERV)
ENDIF

LRLATV = ASSOCIATED (SELF%RLATV)
IF (LRLATV) THEN
  !$ACC EXIT DATA DETACH (SELF%RLATV)
  !$ACC EXIT DATA DETACH (SELF%RLATV)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
