MODULE UTIL_REGLATLON_FIELD_MOD

USE REGLATLON_FIELD_MIX, ONLY : REGLATLON_FIELD

INTERFACE SAVE
MODULE PROCEDURE SAVE_REGLATLON_FIELD
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_REGLATLON_FIELD
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_REGLATLON_FIELD
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_REGLATLON_FIELD
END INTERFACE



CONTAINS

SUBROUTINE SAVE_REGLATLON_FIELD (SELF, KLUN)

IMPLICIT NONE
TYPE (REGLATLON_FIELD), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LPFLD, LPLAT, LPLON, LPSIN
WRITE (KLUN) SELF%NLAT
WRITE (KLUN) SELF%NLON
WRITE (KLUN) SELF%DLAT
WRITE (KLUN) SELF%DLON
LPFLD = ASSOCIATED (SELF%PFLD)
WRITE (KLUN) LPFLD
IF (LPFLD) THEN
  WRITE (KLUN) LBOUND (SELF%PFLD)
  WRITE (KLUN) UBOUND (SELF%PFLD)
  WRITE (KLUN) SELF%PFLD
ENDIF
LPLAT = ASSOCIATED (SELF%PLAT)
WRITE (KLUN) LPLAT
IF (LPLAT) THEN
  WRITE (KLUN) LBOUND (SELF%PLAT)
  WRITE (KLUN) UBOUND (SELF%PLAT)
  WRITE (KLUN) SELF%PLAT
ENDIF
LPSIN = ASSOCIATED (SELF%PSIN)
WRITE (KLUN) LPSIN
IF (LPSIN) THEN
  WRITE (KLUN) LBOUND (SELF%PSIN)
  WRITE (KLUN) UBOUND (SELF%PSIN)
  WRITE (KLUN) SELF%PSIN
ENDIF
LPLON = ASSOCIATED (SELF%PLON)
WRITE (KLUN) LPLON
IF (LPLON) THEN
  WRITE (KLUN) LBOUND (SELF%PLON)
  WRITE (KLUN) UBOUND (SELF%PLON)
  WRITE (KLUN) SELF%PLON
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_REGLATLON_FIELD (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (REGLATLON_FIELD), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LPFLD, LPLAT, LPLON, LPSIN
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
READ (KLUN) SELF%NLAT
READ (KLUN) SELF%NLON
READ (KLUN) ZTMP0
SELF%DLAT = ZTMP0
READ (KLUN) ZTMP0
SELF%DLON = ZTMP0
READ (KLUN) LPFLD
IF (LPFLD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%PFLD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%PFLD,1):UBOUND(SELF%PFLD,1), LBOUND(SELF%PFLD,2):UBOUND(SELF%PFLD,2)))
  READ (KLUN) ZTMP2
  SELF%PFLD = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (SELF%PFLD)
ENDIF
READ (KLUN) LPLAT
IF (LPLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%PLAT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%PLAT,1):UBOUND(SELF%PLAT,1)))
  READ (KLUN) ZTMP1
  SELF%PLAT = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (SELF%PLAT)
ENDIF
READ (KLUN) LPSIN
IF (LPSIN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%PSIN (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%PSIN,1):UBOUND(SELF%PSIN,1)))
  READ (KLUN) ZTMP1
  SELF%PSIN = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (SELF%PSIN)
ENDIF
READ (KLUN) LPLON
IF (LPLON) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%PLON (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%PLON,1):UBOUND(SELF%PLON,1)))
  READ (KLUN) ZTMP1
  SELF%PLON = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (SELF%PLON)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_REGLATLON_FIELD (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (REGLATLON_FIELD), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LPFLD, LPLAT, LPLON, LPSIN

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LPFLD = ASSOCIATED (SELF%PFLD)
IF (LPFLD) THEN
  !$ACC ENTER DATA CREATE (SELF%PFLD)
  !$ACC UPDATE DEVICE (SELF%PFLD)
  !$ACC ENTER DATA ATTACH (SELF%PFLD)
ENDIF

LPLAT = ASSOCIATED (SELF%PLAT)
IF (LPLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%PLAT)
  !$ACC UPDATE DEVICE (SELF%PLAT)
  !$ACC ENTER DATA ATTACH (SELF%PLAT)
ENDIF

LPSIN = ASSOCIATED (SELF%PSIN)
IF (LPSIN) THEN
  !$ACC ENTER DATA CREATE (SELF%PSIN)
  !$ACC UPDATE DEVICE (SELF%PSIN)
  !$ACC ENTER DATA ATTACH (SELF%PSIN)
ENDIF

LPLON = ASSOCIATED (SELF%PLON)
IF (LPLON) THEN
  !$ACC ENTER DATA CREATE (SELF%PLON)
  !$ACC UPDATE DEVICE (SELF%PLON)
  !$ACC ENTER DATA ATTACH (SELF%PLON)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_REGLATLON_FIELD (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (REGLATLON_FIELD), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LPFLD, LPLAT, LPLON, LPSIN

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LPFLD = ASSOCIATED (SELF%PFLD)
IF (LPFLD) THEN
  !$ACC EXIT DATA DETACH (SELF%PFLD)
  !$ACC EXIT DATA DETACH (SELF%PFLD)
ENDIF

LPLAT = ASSOCIATED (SELF%PLAT)
IF (LPLAT) THEN
  !$ACC EXIT DATA DETACH (SELF%PLAT)
  !$ACC EXIT DATA DETACH (SELF%PLAT)
ENDIF

LPSIN = ASSOCIATED (SELF%PSIN)
IF (LPSIN) THEN
  !$ACC EXIT DATA DETACH (SELF%PSIN)
  !$ACC EXIT DATA DETACH (SELF%PSIN)
ENDIF

LPLON = ASSOCIATED (SELF%PLON)
IF (LPLON) THEN
  !$ACC EXIT DATA DETACH (SELF%PLON)
  !$ACC EXIT DATA DETACH (SELF%PLON)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
