MODULE UTIL_TGEM_MOD

USE YOMGEM, ONLY : TGEM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TGEM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TGEM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TGEM
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TGEM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TGEM (SELF, KLUN)

IMPLICIT NONE
TYPE (TGEM), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LNDGLU, LNGPTOTL, LNLOEN, LNLOENG, LNMEN, LNMENG, LNSTAGP, LNTSTAGP
WRITE (KLUN) SELF%NGPTOT
WRITE (KLUN) SELF%NGPTOT_CAP
WRITE (KLUN) SELF%NGPTOTMX
WRITE (KLUN) SELF%NGPTOTG
LNGPTOTL = ALLOCATED (SELF%NGPTOTL)
WRITE (KLUN) LNGPTOTL
IF (LNGPTOTL) THEN
  WRITE (KLUN) LBOUND (SELF%NGPTOTL)
  WRITE (KLUN) UBOUND (SELF%NGPTOTL)
  WRITE (KLUN) SELF%NGPTOTL
ENDIF
WRITE (KLUN) SELF%RDELXN
WRITE (KLUN) SELF%SLHDP
WRITE (KLUN) SELF%RMUCEN
WRITE (KLUN) SELF%RLOCEN
WRITE (KLUN) SELF%RSTRET
WRITE (KLUN) SELF%NSTTYP
WRITE (KLUN) SELF%NHTYP
WRITE (KLUN) SELF%RNLGINC
WRITE (KLUN) SELF%R4JP
WRITE (KLUN) SELF%RC2P1
WRITE (KLUN) SELF%RC2M1
WRITE (KLUN) SELF%RCOR0
WRITE (KLUN) SELF%RCOR1
LNLOEN = ALLOCATED (SELF%NLOEN)
WRITE (KLUN) LNLOEN
IF (LNLOEN) THEN
  WRITE (KLUN) LBOUND (SELF%NLOEN)
  WRITE (KLUN) UBOUND (SELF%NLOEN)
  WRITE (KLUN) SELF%NLOEN
ENDIF
LNLOENG = ALLOCATED (SELF%NLOENG)
WRITE (KLUN) LNLOENG
IF (LNLOENG) THEN
  WRITE (KLUN) LBOUND (SELF%NLOENG)
  WRITE (KLUN) UBOUND (SELF%NLOENG)
  WRITE (KLUN) SELF%NLOENG
ENDIF
LNMEN = ALLOCATED (SELF%NMEN)
WRITE (KLUN) LNMEN
IF (LNMEN) THEN
  WRITE (KLUN) LBOUND (SELF%NMEN)
  WRITE (KLUN) UBOUND (SELF%NMEN)
  WRITE (KLUN) SELF%NMEN
ENDIF
LNMENG = ALLOCATED (SELF%NMENG)
WRITE (KLUN) LNMENG
IF (LNMENG) THEN
  WRITE (KLUN) LBOUND (SELF%NMENG)
  WRITE (KLUN) UBOUND (SELF%NMENG)
  WRITE (KLUN) SELF%NMENG
ENDIF
LNDGLU = ALLOCATED (SELF%NDGLU)
WRITE (KLUN) LNDGLU
IF (LNDGLU) THEN
  WRITE (KLUN) LBOUND (SELF%NDGLU)
  WRITE (KLUN) UBOUND (SELF%NDGLU)
  WRITE (KLUN) SELF%NDGLU
ENDIF
LNSTAGP = ALLOCATED (SELF%NSTAGP)
WRITE (KLUN) LNSTAGP
IF (LNSTAGP) THEN
  WRITE (KLUN) LBOUND (SELF%NSTAGP)
  WRITE (KLUN) UBOUND (SELF%NSTAGP)
  WRITE (KLUN) SELF%NSTAGP
ENDIF
LNTSTAGP = ALLOCATED (SELF%NTSTAGP)
WRITE (KLUN) LNTSTAGP
IF (LNTSTAGP) THEN
  WRITE (KLUN) LBOUND (SELF%NTSTAGP)
  WRITE (KLUN) UBOUND (SELF%NTSTAGP)
  WRITE (KLUN) SELF%NTSTAGP
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TGEM (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TGEM), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LNDGLU, LNGPTOTL, LNLOEN, LNLOENG, LNMEN, LNMENG, LNSTAGP, LNTSTAGP
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) SELF%NGPTOT
READ (KLUN) SELF%NGPTOT_CAP
READ (KLUN) SELF%NGPTOTMX
READ (KLUN) SELF%NGPTOTG
READ (KLUN) LNGPTOTL
IF (LNGPTOTL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%NGPTOTL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%NGPTOTL
ENDIF
READ (KLUN) ZTMP0
SELF%RDELXN = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDP = ZTMP0
READ (KLUN) ZTMP0
SELF%RMUCEN = ZTMP0
READ (KLUN) ZTMP0
SELF%RLOCEN = ZTMP0
READ (KLUN) ZTMP0
SELF%RSTRET = ZTMP0
READ (KLUN) SELF%NSTTYP
READ (KLUN) SELF%NHTYP
READ (KLUN) ZTMP0
SELF%RNLGINC = ZTMP0
READ (KLUN) ZTMP0
SELF%R4JP = ZTMP0
READ (KLUN) ZTMP0
SELF%RC2P1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RC2M1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RCOR0 = ZTMP0
READ (KLUN) ZTMP0
SELF%RCOR1 = ZTMP0
READ (KLUN) LNLOEN
IF (LNLOEN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NLOEN (IL1(1):IU1(1)))
  READ (KLUN) SELF%NLOEN
ENDIF
READ (KLUN) LNLOENG
IF (LNLOENG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NLOENG (IL1(1):IU1(1)))
  READ (KLUN) SELF%NLOENG
ENDIF
READ (KLUN) LNMEN
IF (LNMEN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NMEN (IL1(1):IU1(1)))
  READ (KLUN) SELF%NMEN
ENDIF
READ (KLUN) LNMENG
IF (LNMENG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NMENG (IL1(1):IU1(1)))
  READ (KLUN) SELF%NMENG
ENDIF
READ (KLUN) LNDGLU
IF (LNDGLU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NDGLU (IL1(1):IU1(1)))
  READ (KLUN) SELF%NDGLU
ENDIF
READ (KLUN) LNSTAGP
IF (LNSTAGP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NSTAGP (IL1(1):IU1(1)))
  READ (KLUN) SELF%NSTAGP
ENDIF
READ (KLUN) LNTSTAGP
IF (LNTSTAGP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NTSTAGP (IL1(1):IU1(1)))
  READ (KLUN) SELF%NTSTAGP
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TGEM (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TGEM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LNDGLU, LNGPTOTL, LNLOEN, LNLOENG, LNMEN, LNMENG, LNSTAGP, LNTSTAGP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LNGPTOTL = ALLOCATED (SELF%NGPTOTL)
IF (LNGPTOTL) THEN
  !$ACC ENTER DATA CREATE (SELF%NGPTOTL)
  !$ACC UPDATE DEVICE (SELF%NGPTOTL)
  !$ACC ENTER DATA ATTACH (SELF%NGPTOTL)
ENDIF

LNLOEN = ALLOCATED (SELF%NLOEN)
IF (LNLOEN) THEN
  !$ACC ENTER DATA CREATE (SELF%NLOEN)
  !$ACC UPDATE DEVICE (SELF%NLOEN)
  !$ACC ENTER DATA ATTACH (SELF%NLOEN)
ENDIF

LNLOENG = ALLOCATED (SELF%NLOENG)
IF (LNLOENG) THEN
  !$ACC ENTER DATA CREATE (SELF%NLOENG)
  !$ACC UPDATE DEVICE (SELF%NLOENG)
  !$ACC ENTER DATA ATTACH (SELF%NLOENG)
ENDIF

LNMEN = ALLOCATED (SELF%NMEN)
IF (LNMEN) THEN
  !$ACC ENTER DATA CREATE (SELF%NMEN)
  !$ACC UPDATE DEVICE (SELF%NMEN)
  !$ACC ENTER DATA ATTACH (SELF%NMEN)
ENDIF

LNMENG = ALLOCATED (SELF%NMENG)
IF (LNMENG) THEN
  !$ACC ENTER DATA CREATE (SELF%NMENG)
  !$ACC UPDATE DEVICE (SELF%NMENG)
  !$ACC ENTER DATA ATTACH (SELF%NMENG)
ENDIF

LNDGLU = ALLOCATED (SELF%NDGLU)
IF (LNDGLU) THEN
  !$ACC ENTER DATA CREATE (SELF%NDGLU)
  !$ACC UPDATE DEVICE (SELF%NDGLU)
  !$ACC ENTER DATA ATTACH (SELF%NDGLU)
ENDIF

LNSTAGP = ALLOCATED (SELF%NSTAGP)
IF (LNSTAGP) THEN
  !$ACC ENTER DATA CREATE (SELF%NSTAGP)
  !$ACC UPDATE DEVICE (SELF%NSTAGP)
  !$ACC ENTER DATA ATTACH (SELF%NSTAGP)
ENDIF

LNTSTAGP = ALLOCATED (SELF%NTSTAGP)
IF (LNTSTAGP) THEN
  !$ACC ENTER DATA CREATE (SELF%NTSTAGP)
  !$ACC UPDATE DEVICE (SELF%NTSTAGP)
  !$ACC ENTER DATA ATTACH (SELF%NTSTAGP)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TGEM (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TGEM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LNDGLU, LNGPTOTL, LNLOEN, LNLOENG, LNMEN, LNMENG, LNSTAGP, LNTSTAGP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LNGPTOTL = ALLOCATED (SELF%NGPTOTL)
IF (LNGPTOTL) THEN
  !$ACC EXIT DATA DETACH (SELF%NGPTOTL)
  !$ACC EXIT DATA DETACH (SELF%NGPTOTL)
ENDIF

LNLOEN = ALLOCATED (SELF%NLOEN)
IF (LNLOEN) THEN
  !$ACC EXIT DATA DETACH (SELF%NLOEN)
  !$ACC EXIT DATA DETACH (SELF%NLOEN)
ENDIF

LNLOENG = ALLOCATED (SELF%NLOENG)
IF (LNLOENG) THEN
  !$ACC EXIT DATA DETACH (SELF%NLOENG)
  !$ACC EXIT DATA DETACH (SELF%NLOENG)
ENDIF

LNMEN = ALLOCATED (SELF%NMEN)
IF (LNMEN) THEN
  !$ACC EXIT DATA DETACH (SELF%NMEN)
  !$ACC EXIT DATA DETACH (SELF%NMEN)
ENDIF

LNMENG = ALLOCATED (SELF%NMENG)
IF (LNMENG) THEN
  !$ACC EXIT DATA DETACH (SELF%NMENG)
  !$ACC EXIT DATA DETACH (SELF%NMENG)
ENDIF

LNDGLU = ALLOCATED (SELF%NDGLU)
IF (LNDGLU) THEN
  !$ACC EXIT DATA DETACH (SELF%NDGLU)
  !$ACC EXIT DATA DETACH (SELF%NDGLU)
ENDIF

LNSTAGP = ALLOCATED (SELF%NSTAGP)
IF (LNSTAGP) THEN
  !$ACC EXIT DATA DETACH (SELF%NSTAGP)
  !$ACC EXIT DATA DETACH (SELF%NSTAGP)
ENDIF

LNTSTAGP = ALLOCATED (SELF%NTSTAGP)
IF (LNTSTAGP) THEN
  !$ACC EXIT DATA DETACH (SELF%NTSTAGP)
  !$ACC EXIT DATA DETACH (SELF%NTSTAGP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
