MODULE UTIL_TRIP_MOD

USE YOMRIP, ONLY : TRIP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TRIP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRIP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TRIP
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TRIP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TRIP (SELF, KLUN)
USE UTIL_REGLATLON_FIELD_MOD
USE UTIL_TEAERC_MOD
USE UTIL_TEAERC_TEGEN_MOD
USE UTIL_TECMIP_MOD
USE UTIL_TEOZOC_MOD
USE UTIL_TRADGHG_MOD
IMPLICIT NONE
TYPE (TRIP), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%NSTART
WRITE (KLUN) SELF%NSTOP
WRITE (KLUN) SELF%CSTOP
WRITE (KLUN) SELF%NSTADD
WRITE (KLUN) SELF%NSTASS
WRITE (KLUN) SELF%NFOST
WRITE (KLUN) SELF%RSTATI
WRITE (KLUN) SELF%RTIMTR
WRITE (KLUN) SELF%RHGMT
WRITE (KLUN) SELF%REQTIM
WRITE (KLUN) SELF%RSOVR
WRITE (KLUN) SELF%RDEASO
WRITE (KLUN) SELF%RDECLI
WRITE (KLUN) SELF%RWSOVR
WRITE (KLUN) SELF%RIP0
WRITE (KLUN) SELF%RCODEC
WRITE (KLUN) SELF%RSIDEC
WRITE (KLUN) SELF%RCOVSR
WRITE (KLUN) SELF%RSIVSR
WRITE (KLUN) SELF%RCODECN
WRITE (KLUN) SELF%RSIDECN
WRITE (KLUN) SELF%RCOVSRN
WRITE (KLUN) SELF%RSIVSRN
WRITE (KLUN) SELF%RCODECF
WRITE (KLUN) SELF%RSIDECF
WRITE (KLUN) SELF%RCOVSRF
WRITE (KLUN) SELF%RSIVSRF
WRITE (KLUN) SELF%TSTEP
WRITE (KLUN) SELF%TDT
WRITE (KLUN) SELF%RDTSA
WRITE (KLUN) SELF%RDTSA2
WRITE (KLUN) SELF%RDTS62
WRITE (KLUN) SELF%RDTS22
WRITE (KLUN) SELF%RTDT
WRITE (KLUN) SELF%RDECLU
WRITE (KLUN) SELF%RTMOLT
WRITE (KLUN) SELF%RJUSMP
WRITE (KLUN) SELF%RLUNDI
WRITE (KLUN) SELF%RIP0LU
WRITE (KLUN) SELF%RCODECLU
WRITE (KLUN) SELF%RSIDECLU
WRITE (KLUN) SELF%RCOVSRLU
WRITE (KLUN) SELF%RSIVSRLU
CALL SAVE_TEOZOC (SELF%YREOZOC, KLUN)
CALL SAVE_TECMIP (SELF%YRECMIP, KLUN)
CALL SAVE_TRADGHG (SELF%YRERADGHG, KLUN)
CALL SAVE_TEAERC_TEGEN (SELF%YREAERC_TEGEN, KLUN)
CALL SAVE_TEAERC (SELF%YREAERC, KLUN)
CALL SAVE_REGLATLON_FIELD (SELF%RAERSO4, KLUN)
WRITE (KLUN) SELF%JPORDT
WRITE (KLUN) SELF%GCOEFS_ASCENSION_DROITE
WRITE (KLUN) SELF%GCOEFS_DECLINAISON
WRITE (KLUN) SELF%GCOEFS_DISTANCE
WRITE (KLUN) SELF%GTDEBUT
WRITE (KLUN) SELF%GTFIN
WRITE (KLUN) SELF%NINTT_MOON
WRITE (KLUN) SELF%NINTT_SUN
WRITE (KLUN) SELF%CGSOLEC_SUN
WRITE (KLUN) SELF%CGSOLEC_MOON
END SUBROUTINE

SUBROUTINE LOAD_TRIP (SELF, KLUN)
USE UTIL_REGLATLON_FIELD_MOD
USE UTIL_TEAERC_MOD
USE UTIL_TEAERC_TEGEN_MOD
USE UTIL_TECMIP_MOD
USE UTIL_TEOZOC_MOD
USE UTIL_TRADGHG_MOD
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TRIP), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) SELF%NSTART
READ (KLUN) SELF%NSTOP
READ (KLUN) SELF%CSTOP
READ (KLUN) SELF%NSTADD
READ (KLUN) SELF%NSTASS
READ (KLUN) SELF%NFOST
READ (KLUN) ZTMP0
SELF%RSTATI = ZTMP0
READ (KLUN) SELF%RTIMTR
READ (KLUN) ZTMP0
SELF%RHGMT = ZTMP0
READ (KLUN) ZTMP0
SELF%REQTIM = ZTMP0
READ (KLUN) ZTMP0
SELF%RSOVR = ZTMP0
READ (KLUN) ZTMP0
SELF%RDEASO = ZTMP0
READ (KLUN) ZTMP0
SELF%RDECLI = ZTMP0
READ (KLUN) ZTMP0
SELF%RWSOVR = ZTMP0
READ (KLUN) ZTMP0
SELF%RIP0 = ZTMP0
READ (KLUN) ZTMP0
SELF%RCODEC = ZTMP0
READ (KLUN) ZTMP0
SELF%RSIDEC = ZTMP0
READ (KLUN) ZTMP0
SELF%RCOVSR = ZTMP0
READ (KLUN) ZTMP0
SELF%RSIVSR = ZTMP0
READ (KLUN) ZTMP0
SELF%RCODECN = ZTMP0
READ (KLUN) ZTMP0
SELF%RSIDECN = ZTMP0
READ (KLUN) ZTMP0
SELF%RCOVSRN = ZTMP0
READ (KLUN) ZTMP0
SELF%RSIVSRN = ZTMP0
READ (KLUN) ZTMP0
SELF%RCODECF = ZTMP0
READ (KLUN) ZTMP0
SELF%RSIDECF = ZTMP0
READ (KLUN) ZTMP0
SELF%RCOVSRF = ZTMP0
READ (KLUN) ZTMP0
SELF%RSIVSRF = ZTMP0
READ (KLUN) ZTMP0
SELF%TSTEP = ZTMP0
READ (KLUN) ZTMP0
SELF%TDT = ZTMP0
READ (KLUN) ZTMP0
SELF%RDTSA = ZTMP0
READ (KLUN) ZTMP0
SELF%RDTSA2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDTS62 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDTS22 = ZTMP0
READ (KLUN) ZTMP0
SELF%RTDT = ZTMP0
READ (KLUN) ZTMP0
SELF%RDECLU = ZTMP0
READ (KLUN) ZTMP0
SELF%RTMOLT = ZTMP0
READ (KLUN) SELF%RJUSMP
READ (KLUN) ZTMP0
SELF%RLUNDI = ZTMP0
READ (KLUN) ZTMP0
SELF%RIP0LU = ZTMP0
READ (KLUN) ZTMP0
SELF%RCODECLU = ZTMP0
READ (KLUN) ZTMP0
SELF%RSIDECLU = ZTMP0
READ (KLUN) ZTMP0
SELF%RCOVSRLU = ZTMP0
READ (KLUN) ZTMP0
SELF%RSIVSRLU = ZTMP0
CALL LOAD_TEOZOC (SELF%YREOZOC, KLUN)
CALL LOAD_TECMIP (SELF%YRECMIP, KLUN)
CALL LOAD_TRADGHG (SELF%YRERADGHG, KLUN)
CALL LOAD_TEAERC_TEGEN (SELF%YREAERC_TEGEN, KLUN)
CALL LOAD_TEAERC (SELF%YREAERC, KLUN)
CALL LOAD_REGLATLON_FIELD (SELF%RAERSO4, KLUN)
READ (KLUN) SELF%JPORDT
READ (KLUN) SELF%GCOEFS_ASCENSION_DROITE
READ (KLUN) SELF%GCOEFS_DECLINAISON
READ (KLUN) SELF%GCOEFS_DISTANCE
READ (KLUN) SELF%GTDEBUT
READ (KLUN) SELF%GTFIN
READ (KLUN) SELF%NINTT_MOON
READ (KLUN) SELF%NINTT_SUN
READ (KLUN) SELF%CGSOLEC_SUN
READ (KLUN) SELF%CGSOLEC_MOON
END SUBROUTINE


SUBROUTINE COPY_TRIP (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_REGLATLON_FIELD_MOD
USE UTIL_TEAERC_MOD
USE UTIL_TEAERC_TEGEN_MOD
USE UTIL_TECMIP_MOD
USE UTIL_TEOZOC_MOD
USE UTIL_TRADGHG_MOD
IMPLICIT NONE
TYPE (TRIP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

CALL COPY_TEOZOC (SELF%YREOZOC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TECMIP (SELF%YRECMIP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TRADGHG (SELF%YRERADGHG, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TEAERC_TEGEN (SELF%YREAERC_TEGEN, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TEAERC (SELF%YREAERC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_REGLATLON_FIELD (SELF%RAERSO4, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE



     



SUBROUTINE WIPE_TRIP (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_REGLATLON_FIELD_MOD
USE UTIL_TEAERC_MOD
USE UTIL_TEAERC_TEGEN_MOD
USE UTIL_TECMIP_MOD
USE UTIL_TEOZOC_MOD
USE UTIL_TRADGHG_MOD
IMPLICIT NONE
TYPE (TRIP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

CALL WIPE_TEOZOC (SELF%YREOZOC, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TECMIP (SELF%YRECMIP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TRADGHG (SELF%YRERADGHG, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TEAERC_TEGEN (SELF%YREAERC_TEGEN, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TEAERC (SELF%YREAERC, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_REGLATLON_FIELD (SELF%RAERSO4, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
