MODULE UTIL_TEGSL_MOD

USE YEMGSL, ONLY : TEGSL

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEGSL
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEGSL
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEGSL
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEGSL
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEGSL (SELF, KLUN)

IMPLICIT NONE
TYPE (TEGSL), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%RIPORE
WRITE (KLUN) SELF%RJPORE
WRITE (KLUN) SELF%REGPK
WRITE (KLUN) SELF%RNOBILE
WRITE (KLUN) SELF%RHSUD
WRITE (KLUN) SELF%RMERCAT
WRITE (KLUN) SELF%RLON0R
WRITE (KLUN) SELF%RELONC
WRITE (KLUN) SELF%RELATC
END SUBROUTINE

SUBROUTINE LOAD_TEGSL (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TEGSL), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
SELF%RIPORE = ZTMP0
READ (KLUN) ZTMP0
SELF%RJPORE = ZTMP0
READ (KLUN) ZTMP0
SELF%REGPK = ZTMP0
READ (KLUN) ZTMP0
SELF%RNOBILE = ZTMP0
READ (KLUN) ZTMP0
SELF%RHSUD = ZTMP0
READ (KLUN) ZTMP0
SELF%RMERCAT = ZTMP0
READ (KLUN) ZTMP0
SELF%RLON0R = ZTMP0
READ (KLUN) ZTMP0
SELF%RELONC = ZTMP0
READ (KLUN) ZTMP0
SELF%RELATC = ZTMP0
END SUBROUTINE


SUBROUTINE COPY_TEGSL (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEGSL), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TEGSL (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEGSL), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
