MODULE UTIL_THWIND_MOD

USE INTDYN_MOD, ONLY : THWIND

INTERFACE SAVE
MODULE PROCEDURE SAVE_THWIND
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_THWIND
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_THWIND
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_THWIND
END INTERFACE



CONTAINS

SUBROUTINE SAVE_THWIND (SELF, KLUN)

IMPLICIT NONE
TYPE (THWIND), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%M_UH
WRITE (KLUN) SELF%M_VH
WRITE (KLUN) SELF%M_WWI
WRITE (KLUN) SELF%NDIM
END SUBROUTINE

SUBROUTINE LOAD_THWIND (SELF, KLUN)

IMPLICIT NONE
TYPE (THWIND), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%M_UH
READ (KLUN) SELF%M_VH
READ (KLUN) SELF%M_WWI
READ (KLUN) SELF%NDIM
END SUBROUTINE


SUBROUTINE COPY_THWIND (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (THWIND), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_THWIND (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (THWIND), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
