MODULE UTIL_TCTY_MOD

USE INTDYN_MOD, ONLY : TCTY

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCTY
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCTY
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCTY
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCTY
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCTY (SELF, KLUN)

IMPLICIT NONE
TYPE (TCTY), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%M_EVEL
WRITE (KLUN) SELF%M_VVEL
WRITE (KLUN) SELF%M_PSDIV
WRITE (KLUN) SELF%M_PSDVBC
WRITE (KLUN) SELF%M_DIVDP
WRITE (KLUN) SELF%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TCTY (SELF, KLUN)

IMPLICIT NONE
TYPE (TCTY), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%M_EVEL
READ (KLUN) SELF%M_VVEL
READ (KLUN) SELF%M_PSDIV
READ (KLUN) SELF%M_PSDVBC
READ (KLUN) SELF%M_DIVDP
READ (KLUN) SELF%NDIM
END SUBROUTINE


SUBROUTINE COPY_TCTY (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCTY), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TCTY (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCTY), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
