MODULE UTIL_TGMVT_MOD

USE INTDYN_MOD, ONLY : TGMVT

INTERFACE SAVE
MODULE PROCEDURE SAVE_TGMVT
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TGMVT
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TGMVT
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TGMVT
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TGMVT (SELF, KLUN)

IMPLICIT NONE
TYPE (TGMVT), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%M_U
WRITE (KLUN) SELF%M_V
WRITE (KLUN) SELF%M_T
WRITE (KLUN) SELF%M_DIV
WRITE (KLUN) SELF%M_SPD
WRITE (KLUN) SELF%M_SVD
WRITE (KLUN) SELF%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TGMVT (SELF, KLUN)

IMPLICIT NONE
TYPE (TGMVT), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%M_U
READ (KLUN) SELF%M_V
READ (KLUN) SELF%M_T
READ (KLUN) SELF%M_DIV
READ (KLUN) SELF%M_SPD
READ (KLUN) SELF%M_SVD
READ (KLUN) SELF%NDIM
END SUBROUTINE


SUBROUTINE COPY_TGMVT (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TGMVT), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TGMVT (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TGMVT), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
