MODULE UTIL_TGFLT_MOD

USE INTDYN_MOD, ONLY : TGFLT

INTERFACE SAVE
MODULE PROCEDURE SAVE_TGFLT
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TGFLT
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TGFLT
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TGFLT
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TGFLT (SELF, KLUN)

IMPLICIT NONE
TYPE (TGFLT), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%M_Q
WRITE (KLUN) SELF%M_L
WRITE (KLUN) SELF%M_I
WRITE (KLUN) SELF%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TGFLT (SELF, KLUN)

IMPLICIT NONE
TYPE (TGFLT), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%M_Q
READ (KLUN) SELF%M_L
READ (KLUN) SELF%M_I
READ (KLUN) SELF%NDIM
END SUBROUTINE


SUBROUTINE COPY_TGFLT (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TGFLT), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TGFLT (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TGFLT), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
