MODULE UTIL_TEOZOC_MOD

USE YOEOZOC, ONLY : TEOZOC

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEOZOC
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEOZOC
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEOZOC
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEOZOC
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEOZOC (SELF, KLUN)

IMPLICIT NONE
TYPE (TEOZOC), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LZOZCL, LZOZCLAQUA
LZOZCL = ALLOCATED (SELF%ZOZCL)
WRITE (KLUN) LZOZCL
IF (LZOZCL) THEN
  WRITE (KLUN) LBOUND (SELF%ZOZCL)
  WRITE (KLUN) UBOUND (SELF%ZOZCL)
  WRITE (KLUN) SELF%ZOZCL
ENDIF
LZOZCLAQUA = ALLOCATED (SELF%ZOZCLAQUA)
WRITE (KLUN) LZOZCLAQUA
IF (LZOZCLAQUA) THEN
  WRITE (KLUN) LBOUND (SELF%ZOZCLAQUA)
  WRITE (KLUN) UBOUND (SELF%ZOZCLAQUA)
  WRITE (KLUN) SELF%ZOZCLAQUA
ENDIF
WRITE (KLUN) SELF%COZQC
WRITE (KLUN) SELF%COZQS
WRITE (KLUN) SELF%COZHC
WRITE (KLUN) SELF%COZHS
WRITE (KLUN) SELF%RSINC
WRITE (KLUN) SELF%ROZT
WRITE (KLUN) SELF%RPROC
END SUBROUTINE

SUBROUTINE LOAD_TEOZOC (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TEOZOC), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LZOZCL, LZOZCLAQUA
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
READ (KLUN) LZOZCL
IF (LZOZCL) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%ZOZCL (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%ZOZCL,1):UBOUND(SELF%ZOZCL,1), LBOUND(SELF%ZOZCL,2):UBOUND(SELF%ZOZCL,2), LBOUND(SELF%ZOZCL,3):UBOUND(SELF%ZOZCL,3)))
  READ (KLUN) ZTMP3
  SELF%ZOZCL = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LZOZCLAQUA
IF (LZOZCLAQUA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%ZOZCLAQUA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%ZOZCLAQUA,1):UBOUND(SELF%ZOZCLAQUA,1), LBOUND(SELF%ZOZCLAQUA,2):UBOUND(SELF%ZOZCLAQUA,2)))
  READ (KLUN) ZTMP2
  SELF%ZOZCLAQUA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
ALLOCATE (ZTMP1(LBOUND(SELF%COZQC,1):UBOUND(SELF%COZQC,1)))
READ (KLUN) ZTMP1
SELF%COZQC = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%COZQS,1):UBOUND(SELF%COZQS,1)))
READ (KLUN) ZTMP1
SELF%COZQS = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%COZHC,1):UBOUND(SELF%COZHC,1)))
READ (KLUN) ZTMP1
SELF%COZHC = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%COZHS,1):UBOUND(SELF%COZHS,1)))
READ (KLUN) ZTMP1
SELF%COZHS = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RSINC,1):UBOUND(SELF%RSINC,1)))
READ (KLUN) ZTMP1
SELF%RSINC = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP2(LBOUND(SELF%ROZT,1):UBOUND(SELF%ROZT,1), LBOUND(SELF%ROZT,2):UBOUND(SELF%ROZT,2)))
READ (KLUN) ZTMP2
SELF%ROZT = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP1(LBOUND(SELF%RPROC,1):UBOUND(SELF%RPROC,1)))
READ (KLUN) ZTMP1
SELF%RPROC = ZTMP1
DEALLOCATE (ZTMP1)
END SUBROUTINE


SUBROUTINE COPY_TEOZOC (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEOZOC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LZOZCL, LZOZCLAQUA

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LZOZCL = ALLOCATED (SELF%ZOZCL)
IF (LZOZCL) THEN
  !$ACC ENTER DATA CREATE (SELF%ZOZCL)
  !$ACC UPDATE DEVICE (SELF%ZOZCL)
  !$ACC ENTER DATA ATTACH (SELF%ZOZCL)
ENDIF

LZOZCLAQUA = ALLOCATED (SELF%ZOZCLAQUA)
IF (LZOZCLAQUA) THEN
  !$ACC ENTER DATA CREATE (SELF%ZOZCLAQUA)
  !$ACC UPDATE DEVICE (SELF%ZOZCLAQUA)
  !$ACC ENTER DATA ATTACH (SELF%ZOZCLAQUA)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TEOZOC (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEOZOC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LZOZCL, LZOZCLAQUA

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LZOZCL = ALLOCATED (SELF%ZOZCL)
IF (LZOZCL) THEN
  !$ACC EXIT DATA DETACH (SELF%ZOZCL)
  !$ACC EXIT DATA DETACH (SELF%ZOZCL)
ENDIF

LZOZCLAQUA = ALLOCATED (SELF%ZOZCLAQUA)
IF (LZOZCLAQUA) THEN
  !$ACC EXIT DATA DETACH (SELF%ZOZCLAQUA)
  !$ACC EXIT DATA DETACH (SELF%ZOZCLAQUA)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
