MODULE UTIL_TCVER_MOD

USE YOMCVER, ONLY : TCVER

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCVER
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCVER
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCVER
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCVER
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCVER (SELF, KLUN)

IMPLICIT NONE
TYPE (TCVER), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LAPRXPK
WRITE (KLUN) SELF%NDLNPR
WRITE (KLUN) SELF%RHYDR0
WRITE (KLUN) SELF%REXP_VRAT
WRITE (KLUN) SELF%LREGETA
WRITE (KLUN) SELF%LVFE_REGETA
WRITE (KLUN) SELF%NVFE_TYPE
WRITE (KLUN) SELF%NVFE_ORDER
WRITE (KLUN) SELF%NVFE_INTERNALS
WRITE (KLUN) SELF%LVERTFE
WRITE (KLUN) SELF%LVFE_LAPL_BC
WRITE (KLUN) SELF%LVFE_GW
WRITE (KLUN) SELF%LVFE_GW_HALF
WRITE (KLUN) SELF%LVFE_GWMPA
WRITE (KLUN) SELF%LVFE_CHEB
WRITE (KLUN) SELF%LVFE_ECMWF
WRITE (KLUN) SELF%LVFE_NOBC
WRITE (KLUN) SELF%LVFE_VERBOSE
WRITE (KLUN) SELF%LVFE_NORMALIZE
WRITE (KLUN) SELF%LPERCENTILS
WRITE (KLUN) SELF%LVFE_COMPATIBLE
WRITE (KLUN) SELF%LVFE_FD_MIX
WRITE (KLUN) SELF%LVFE_LAPL_HALF
WRITE (KLUN) SELF%LCOMPATIBLE
WRITE (KLUN) SELF%LREFINE_NHPRE_BBC
WRITE (KLUN) SELF%RVFE_ALPHA
WRITE (KLUN) SELF%RVFE_BETA
WRITE (KLUN) SELF%RVFE_KNOT_STRETCH
WRITE (KLUN) SELF%RFAC1
WRITE (KLUN) SELF%RFAC2
WRITE (KLUN) SELF%CVFE_ETAH
END SUBROUTINE

SUBROUTINE LOAD_TCVER (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TCVER), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) SELF%LAPRXPK
READ (KLUN) SELF%NDLNPR
READ (KLUN) ZTMP0
SELF%RHYDR0 = ZTMP0
READ (KLUN) ZTMP0
SELF%REXP_VRAT = ZTMP0
READ (KLUN) SELF%LREGETA
READ (KLUN) SELF%LVFE_REGETA
READ (KLUN) SELF%NVFE_TYPE
READ (KLUN) SELF%NVFE_ORDER
READ (KLUN) SELF%NVFE_INTERNALS
READ (KLUN) SELF%LVERTFE
READ (KLUN) SELF%LVFE_LAPL_BC
READ (KLUN) SELF%LVFE_GW
READ (KLUN) SELF%LVFE_GW_HALF
READ (KLUN) SELF%LVFE_GWMPA
READ (KLUN) SELF%LVFE_CHEB
READ (KLUN) SELF%LVFE_ECMWF
READ (KLUN) SELF%LVFE_NOBC
READ (KLUN) SELF%LVFE_VERBOSE
READ (KLUN) SELF%LVFE_NORMALIZE
READ (KLUN) SELF%LPERCENTILS
READ (KLUN) SELF%LVFE_COMPATIBLE
READ (KLUN) SELF%LVFE_FD_MIX
READ (KLUN) SELF%LVFE_LAPL_HALF
READ (KLUN) SELF%LCOMPATIBLE
READ (KLUN) SELF%LREFINE_NHPRE_BBC
READ (KLUN) ZTMP0
SELF%RVFE_ALPHA = ZTMP0
READ (KLUN) ZTMP0
SELF%RVFE_BETA = ZTMP0
READ (KLUN) ZTMP0
SELF%RVFE_KNOT_STRETCH = ZTMP0
READ (KLUN) ZTMP0
SELF%RFAC1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RFAC2 = ZTMP0
READ (KLUN) SELF%CVFE_ETAH
END SUBROUTINE


SUBROUTINE COPY_TCVER (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCVER), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TCVER (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCVER), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
