MODULE UTIL_TEGEO_MOD

USE YEMGEO, ONLY : TEGEO

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEGEO
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEGEO
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEGEO
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEGEO
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEGEO (SELF, KLUN)

IMPLICIT NONE
TYPE (TEGEO), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%ERPK
WRITE (KLUN) SELF%ELON1
WRITE (KLUN) SELF%ELAT1
WRITE (KLUN) SELF%ELON2
WRITE (KLUN) SELF%ELAT2
WRITE (KLUN) SELF%ELON0
WRITE (KLUN) SELF%ELAT0
WRITE (KLUN) SELF%ELONC
WRITE (KLUN) SELF%ELATC
WRITE (KLUN) SELF%EDELX
WRITE (KLUN) SELF%EDELY
WRITE (KLUN) SELF%ELX
WRITE (KLUN) SELF%ELY
WRITE (KLUN) SELF%EXWN
WRITE (KLUN) SELF%EYWN
WRITE (KLUN) SELF%RCORI_ACAD
WRITE (KLUN) SELF%RLAT_ACAD
WRITE (KLUN) SELF%RLON_ACAD
WRITE (KLUN) SELF%LMAP
WRITE (KLUN) SELF%LMRT
WRITE (KLUN) SELF%LREDEL_IN_METRES
END SUBROUTINE

SUBROUTINE LOAD_TEGEO (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TEGEO), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
SELF%ERPK = ZTMP0
READ (KLUN) ZTMP0
SELF%ELON1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ELAT1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ELON2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ELAT2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ELON0 = ZTMP0
READ (KLUN) ZTMP0
SELF%ELAT0 = ZTMP0
READ (KLUN) ZTMP0
SELF%ELONC = ZTMP0
READ (KLUN) ZTMP0
SELF%ELATC = ZTMP0
READ (KLUN) ZTMP0
SELF%EDELX = ZTMP0
READ (KLUN) ZTMP0
SELF%EDELY = ZTMP0
READ (KLUN) ZTMP0
SELF%ELX = ZTMP0
READ (KLUN) ZTMP0
SELF%ELY = ZTMP0
READ (KLUN) ZTMP0
SELF%EXWN = ZTMP0
READ (KLUN) ZTMP0
SELF%EYWN = ZTMP0
READ (KLUN) ZTMP0
SELF%RCORI_ACAD = ZTMP0
READ (KLUN) ZTMP0
SELF%RLAT_ACAD = ZTMP0
READ (KLUN) ZTMP0
SELF%RLON_ACAD = ZTMP0
READ (KLUN) SELF%LMAP
READ (KLUN) SELF%LMRT
READ (KLUN) SELF%LREDEL_IN_METRES
END SUBROUTINE


SUBROUTINE COPY_TEGEO (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEGEO), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TEGEO (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEGEO), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
