MODULE UTIL_TDIMV_MOD

USE YOMDIMV, ONLY : TDIMV

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDIMV
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDIMV
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDIMV
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDIMV
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TDIMV (SELF, KLUN)

IMPLICIT NONE
TYPE (TDIMV), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%NFLEVG
WRITE (KLUN) SELF%NFLEVL
WRITE (KLUN) SELF%NFLEVLMX
WRITE (KLUN) SELF%NFLSUR
WRITE (KLUN) SELF%NFLSUL
WRITE (KLUN) SELF%NFLSA
WRITE (KLUN) SELF%NFLEN
WRITE (KLUN) SELF%NIOLEVG
END SUBROUTINE

SUBROUTINE LOAD_TDIMV (SELF, KLUN)

IMPLICIT NONE
TYPE (TDIMV), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%NFLEVG
READ (KLUN) SELF%NFLEVL
READ (KLUN) SELF%NFLEVLMX
READ (KLUN) SELF%NFLSUR
READ (KLUN) SELF%NFLSUL
READ (KLUN) SELF%NFLSA
READ (KLUN) SELF%NFLEN
READ (KLUN) SELF%NIOLEVG
END SUBROUTINE


SUBROUTINE COPY_TDIMV (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TDIMV), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TDIMV (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TDIMV), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
