MODULE UTIL_TTND_MOD

USE INTDYN_MOD, ONLY : TTND

INTERFACE SAVE
MODULE PROCEDURE SAVE_TTND
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TTND
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TTND
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TTND
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TTND (SELF, KLUN)

IMPLICIT NONE
TYPE (TTND), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%M_TNDU
WRITE (KLUN) SELF%M_TNDV
WRITE (KLUN) SELF%M_TNDU_NOC
WRITE (KLUN) SELF%M_TNDV_NOC
WRITE (KLUN) SELF%M_TNDT
WRITE (KLUN) SELF%M_TNDPD
WRITE (KLUN) SELF%M_TNDVD
WRITE (KLUN) SELF%M_TNDGW
WRITE (KLUN) SELF%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TTND (SELF, KLUN)

IMPLICIT NONE
TYPE (TTND), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%M_TNDU
READ (KLUN) SELF%M_TNDV
READ (KLUN) SELF%M_TNDU_NOC
READ (KLUN) SELF%M_TNDV_NOC
READ (KLUN) SELF%M_TNDT
READ (KLUN) SELF%M_TNDPD
READ (KLUN) SELF%M_TNDVD
READ (KLUN) SELF%M_TNDGW
READ (KLUN) SELF%NDIM
END SUBROUTINE


SUBROUTINE COPY_TTND (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TTND), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TTND (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TTND), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
