PROGRAM MAIN_SPNHSI

#ifdef __NVCOMPILER
USE NVTX
#endif

USE XRD_GETOPTIONS
USE XRD_UNIX_ENV

USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK

USE YOMMP0       , ONLY : MYSETV, MYSETN
USE YOMCT0       , ONLY : LELAM

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMCST       , ONLY : TCST
USE YOMDYN       , ONLY : TDYN
USE YOMDYNA      , ONLY : TDYNA
USE YOMLDDH      , ONLY : TLDDH
USE YOMRIP       , ONLY : TRIP

USE UTIL_GEOMETRY_MOD
USE UTIL_TCST_MOD
USE UTIL_TDYN_MOD
USE UTIL_TDYNA_MOD
USE UTIL_TLDDH_MOD
USE UTIL_TRIP_MOD

USE YOMDATA

IMPLICIT NONE

TYPE(TCST)          :: YDCST
TYPE(GEOMETRY)      :: YDGEOMETRY
TYPE(TLDDH)         :: YDLDDH
TYPE(TRIP)          :: YDRIP
TYPE(TDYN)          :: YDDYN
TYPE(TDYNA)         :: YDDYNA
INTEGER(KIND=JPIM)  :: KM 
INTEGER(KIND=JPIM)  :: KMLOC 
INTEGER(KIND=JPIM)  :: KSTA 
INTEGER(KIND=JPIM)  :: KEND 
INTEGER(KIND=JPIM)  :: KSPEC2V
LOGICAL             :: LDONEM
LOGICAL             :: LDOHD
LOGICAL             :: LESIDG
REAL(KIND=JPRB)    , POINTER :: PSPVORG(:,:) 
REAL(KIND=JPRB)    , POINTER :: PSPDIVG(:,:) 
REAL(KIND=JPRB)    , POINTER :: PSPTG(:,:) 
REAL(KIND=JPRB)    , POINTER :: PSPSPG(:) 
REAL(KIND=JPRB)    , POINTER :: PSPSPDG(:,:) 
REAL(KIND=JPRB)    , POINTER :: PSPSVDG(:,:) 
REAL(KIND=JPRB)    , POINTER :: PSPTNDSI_VORG(:,:)
REAL(KIND=JPRB)    , POINTER :: PSPTNDSI_DIVG(:,:)
REAL(KIND=JPRB)    , POINTER :: PSPTNDSI_TG(:,:)
REAL(KIND=JPRB)    , POINTER :: PSPTNDSI_SPDG(:,:)
REAL(KIND=JPRB)    , POINTER :: PSPTNDSI_SVDG(:,:)
REAL(KIND=JPRB)    , POINTER :: PSPAUXG(:,:)

#include "spnhsi.intfb.h"

CHARACTER (LEN=128) :: CLCASE_IN, CLCASE_OUT
CHARACTER (LEN=32) :: CLMETHOD
LOGICAL :: LLSTAT, LLDIFF

INTEGER :: ITIME,NTIME

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MAIN_SPNHSI',0,ZHOOK_HANDLE)

CALL INITOPTIONS

CALL GETOPTION ("--case-in", CLCASE_IN, MND=.TRUE.)

CLCASE_OUT = ''
CALL GETOPTION ("--case-out", CLCASE_OUT, MND=.FALSE.)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--stat", LLSTAT)
CALL GETOPTION ("--method", CLMETHOD, MND=.TRUE.)

NTIME = 1; CALL GETOPTION ("--times", NTIME)

CALL CHECKOPTIONS

CALL LOADALL

IF (TRIM (CLCASE_OUT) /= '') THEN
  CALL XRD_MKDIR (TRIM (CLCASE_OUT))
  CALL SAVEIALL
ENDIF

!$ACC DATA COPY (PSPVORG, PSPDIVG, PSPTG, PSPSPG, PSPSPDG, PSPSVDG, PSPTNDSI_VORG, PSPTNDSI_DIVG, &
!$ACC          & PSPTNDSI_TG, PSPTNDSI_SPDG, PSPTNDSI_SVDG, PSPAUXG) IF (TRIM (CLMETHOD) == 'openaccsingleblock')

IF (TRIM (CLMETHOD) == 'openaccsingleblock') THEN
  CALL ACDC_COPY (YDCST)
  CALL ACDC_COPY (YDGEOMETRY)
  CALL ACDC_COPY (YDLDDH)
  CALL ACDC_COPY (YDRIP)
  CALL ACDC_COPY (YDDYN)
  CALL ACDC_COPY (YDDYNA)
ENDIF

DO ITIME=1,NTIME

IF (TRIM (CLMETHOD) == 'nominal') THEN
  CALL SPNHSI(&
      & YDCST,YDGEOMETRY,YDLDDH,YDRIP,YDDYN,YDDYNA,KM,KMLOC,KSTA,KEND,KSPEC2V,LDONEM,LDOHD,&
      & LESIDG,&
      & PSPVORG,PSPDIVG,PSPTG,PSPSPG,PSPSPDG,PSPSVDG,&
      & PSPTNDSI_VORG,PSPTNDSI_DIVG,PSPTNDSI_TG,PSPTNDSI_SPDG,PSPTNDSI_SVDG,&
      & PSPAUXG)
ELSEIF (TRIM (CLMETHOD) == 'singleblock') THEN
  CALL SPNHSI_SINGLEBLOCK(&
      & YDCST,YDGEOMETRY,YDLDDH,YDRIP,YDDYN,YDDYNA,KM,KMLOC,KSTA,KEND,KSPEC2V,LDONEM,LDOHD,&
      & LESIDG,&
      & PSPVORG,PSPDIVG,PSPTG,PSPSPG,PSPSPDG,PSPSVDG,&
      & PSPTNDSI_VORG,PSPTNDSI_DIVG,PSPTNDSI_TG,PSPTNDSI_SPDG,PSPTNDSI_SVDG,&
      & PSPAUXG, LDACC=.FALSE.)
ELSEIF (TRIM (CLMETHOD) == 'openaccsingleblock') THEN

#ifdef __NVCOMPILER
CALL NVTXSTARTRANGE("SHALLOW_MF_OPENACC")
#endif

  CALL SPNHSI_SINGLEBLOCK(&
      & YDCST,YDGEOMETRY,YDLDDH,YDRIP,YDDYN,YDDYNA,KM,KMLOC,KSTA,KEND,KSPEC2V,LDONEM,LDOHD,&
      & LESIDG,&
      & PSPVORG,PSPDIVG,PSPTG,PSPSPG,PSPSPDG,PSPSVDG,&
      & PSPTNDSI_VORG,PSPTNDSI_DIVG,PSPTNDSI_TG,PSPTNDSI_SPDG,PSPTNDSI_SVDG,&
      & PSPAUXG, LDACC=.TRUE.)

#ifdef __NVCOMPILER
CALL NVTXENDRANGE()
#endif

ENDIF

ENDDO
!$ACC END DATA

IF (TRIM (CLMETHOD) == 'openaccsingleblock') THEN
  CALL ACDC_WIPE (YDDYNA)
  CALL ACDC_WIPE (YDDYN)
  CALL ACDC_WIPE (YDRIP)
  CALL ACDC_WIPE (YDLDDH)
  CALL ACDC_WIPE (YDGEOMETRY)
  CALL ACDC_WIPE (YDCST)
ENDIF

IF (TRIM (CLCASE_OUT) /= '') THEN
  CALL SAVEOALL
ENDIF

IF (LLDIFF) CALL DIFFALL

IF (LLSTAT) CALL STATALL

IF (LHOOK) CALL DR_HOOK('MAIN_SPNHSI',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE SAVEIALL

INTEGER :: ILUN

ILUN = 77

OPEN (ILUN, FILE=TRIM (CLCASE_OUT)//'/SPNHSI.CONST.DAT', FORM='UNFORMATTED')

WRITE (ILUN) MYSETN
WRITE (ILUN) MYSETV
WRITE (ILUN) LELAM

CALL ACDC_SAVE (YDCST     , ILUN)
CALL ACDC_SAVE (YDGEOMETRY, ILUN)
CALL ACDC_SAVE (YDLDDH    , ILUN)
CALL ACDC_SAVE (YDRIP     , ILUN)
CALL ACDC_SAVE (YDDYN     , ILUN)
CALL ACDC_SAVE (YDDYNA    , ILUN)

CLOSE (ILUN)

OPEN (ILUN, FILE=TRIM (CLCASE_OUT)//'/SPNHSI.IN.DAT', FORM='UNFORMATTED')

CALL SAVE (ILUN, KM           )
CALL SAVE (ILUN, KMLOC        )
CALL SAVE (ILUN, KSTA         )
CALL SAVE (ILUN, KEND         )
CALL SAVE (ILUN, KSPEC2V      )
CALL SAVE (ILUN, LDONEM       )
CALL SAVE (ILUN, LDOHD        )
CALL SAVE (ILUN, LESIDG       )

CALL SAVE (ILUN, PSPVORG      , KLBOUND=LBOUND (PSPVORG      ))  
CALL SAVE (ILUN, PSPDIVG      , KLBOUND=LBOUND (PSPDIVG      ))  
CALL SAVE (ILUN, PSPTG        , KLBOUND=LBOUND (PSPTG        ))
CALL SAVE (ILUN, PSPSPG       , KLBOUND=LBOUND (PSPSPG       ))
CALL SAVE (ILUN, PSPSPDG      , KLBOUND=LBOUND (PSPSPDG      ))  
CALL SAVE (ILUN, PSPSVDG      , KLBOUND=LBOUND (PSPSVDG      ))  
CALL SAVE (ILUN, PSPTNDSI_VORG, KLBOUND=LBOUND (PSPTNDSI_VORG))
CALL SAVE (ILUN, PSPTNDSI_DIVG, KLBOUND=LBOUND (PSPTNDSI_DIVG))
CALL SAVE (ILUN, PSPTNDSI_TG  , KLBOUND=LBOUND (PSPTNDSI_TG  ))  
CALL SAVE (ILUN, PSPTNDSI_SPDG, KLBOUND=LBOUND (PSPTNDSI_SPDG))
CALL SAVE (ILUN, PSPTNDSI_SVDG, KLBOUND=LBOUND (PSPTNDSI_SVDG))

CLOSE (ILUN)

END SUBROUTINE

SUBROUTINE SAVEOALL

INTEGER :: ILUN

ILUN = 77

OPEN (ILUN, FILE=TRIM (CLCASE_OUT)//'/SPNHSI.OUT.DAT', FORM='UNFORMATTED')

CALL SAVE (ILUN, PSPVORG      , KLBOUND=LBOUND (PSPVORG      ))  
CALL SAVE (ILUN, PSPDIVG      , KLBOUND=LBOUND (PSPDIVG      ))  
CALL SAVE (ILUN, PSPTG        , KLBOUND=LBOUND (PSPTG        ))
CALL SAVE (ILUN, PSPSPG       , KLBOUND=LBOUND (PSPSPG       ))
CALL SAVE (ILUN, PSPSPDG      , KLBOUND=LBOUND (PSPSPDG      ))  
CALL SAVE (ILUN, PSPSVDG      , KLBOUND=LBOUND (PSPSVDG      ))  
CALL SAVE (ILUN, PSPTNDSI_VORG, KLBOUND=LBOUND (PSPTNDSI_VORG))
CALL SAVE (ILUN, PSPTNDSI_DIVG, KLBOUND=LBOUND (PSPTNDSI_DIVG))
CALL SAVE (ILUN, PSPTNDSI_TG  , KLBOUND=LBOUND (PSPTNDSI_TG  ))  
CALL SAVE (ILUN, PSPTNDSI_SPDG, KLBOUND=LBOUND (PSPTNDSI_SPDG))
CALL SAVE (ILUN, PSPTNDSI_SVDG, KLBOUND=LBOUND (PSPTNDSI_SVDG))

CLOSE (ILUN)

END SUBROUTINE

SUBROUTINE LOADALL

INTEGER :: ILUN

ILUN = 77

OPEN (ILUN, FILE=TRIM (CLCASE_IN)//'/SPNHSI.CONST.DAT', FORM='UNFORMATTED')

READ (ILUN) MYSETN
READ (ILUN) MYSETV
READ (ILUN) LELAM

CALL ACDC_LOAD (YDCST     , ILUN)
CALL ACDC_LOAD (YDGEOMETRY, ILUN)
CALL ACDC_LOAD (YDLDDH    , ILUN)
CALL ACDC_LOAD (YDRIP     , ILUN)
CALL ACDC_LOAD (YDDYN     , ILUN)
CALL ACDC_LOAD (YDDYNA    , ILUN)

CLOSE (ILUN)

OPEN (ILUN, FILE=TRIM (CLCASE_IN)//'/SPNHSI.IN.DAT', FORM='UNFORMATTED')

CALL LOAD (ILUN, KM           ) 
CALL LOAD (ILUN, KMLOC        ) 
CALL LOAD (ILUN, KSTA         ) 
CALL LOAD (ILUN, KEND         ) 
CALL LOAD (ILUN, KSPEC2V      )
CALL LOAD (ILUN, LDONEM       ) 
CALL LOAD (ILUN, LDOHD        ) 
CALL LOAD (ILUN, LESIDG       ) 

CALL LOAD (ILUN, PSPVORG      )
CALL LOAD (ILUN, PSPDIVG      )
CALL LOAD (ILUN, PSPTG        )
CALL LOAD (ILUN, PSPSPG       )
CALL LOAD (ILUN, PSPSPDG      )
CALL LOAD (ILUN, PSPSVDG      )
CALL LOAD (ILUN, PSPTNDSI_VORG)
CALL LOAD (ILUN, PSPTNDSI_DIVG)
CALL LOAD (ILUN, PSPTNDSI_TG  )
CALL LOAD (ILUN, PSPTNDSI_SPDG)
CALL LOAD (ILUN, PSPTNDSI_SVDG)

ALLOCATE (PSPAUXG (KSPEC2V,YDGEOMETRY%YRDIMV%NFLEVG))

CLOSE (ILUN)

END SUBROUTINE

SUBROUTINE DIFFALL

INTEGER :: ILUN

ILUN = 77

OPEN (ILUN, FILE=TRIM (CLCASE_IN)//'/SPNHSI.OUT.DAT', FORM='UNFORMATTED')

CALL DIFF ("PSPVORG      ",  PSPVORG      , KLUN=ILUN)
CALL DIFF ("PSPDIVG      ",  PSPDIVG      , KLUN=ILUN)
CALL DIFF ("PSPTG        ",  PSPTG        , KLUN=ILUN)
CALL DIFF ("PSPSPG       ",  PSPSPG       , KLUN=ILUN)
CALL DIFF ("PSPSPDG      ",  PSPSPDG      , KLUN=ILUN)
CALL DIFF ("PSPSVDG      ",  PSPSVDG      , KLUN=ILUN)
!CALL DIFF ("PSPTNDSI_VORG",  PSPTNDSI_VORG, KLUN=ILUN)
!CALL DIFF ("PSPTNDSI_DIVG",  PSPTNDSI_DIVG, KLUN=ILUN)
!CALL DIFF ("PSPTNDSI_TG  ",  PSPTNDSI_TG  , KLUN=ILUN)
!CALL DIFF ("PSPTNDSI_SPDG",  PSPTNDSI_SPDG, KLUN=ILUN)
!CALL DIFF ("PSPTNDSI_SVDG",  PSPTNDSI_SVDG, KLUN=ILUN)

CLOSE (ILUN)

END SUBROUTINE

SUBROUTINE STATALL

INTEGER :: ILUN

ILUN = 77

OPEN (ILUN, FILE=TRIM (CLCASE_IN)//'/SPNHSI.OUT.DAT', FORM='UNFORMATTED')

CALL STAT ("PSPVORG      ",  PSPVORG      , KLUN=ILUN)
CALL STAT ("PSPDIVG      ",  PSPDIVG      , KLUN=ILUN)
CALL STAT ("PSPTG        ",  PSPTG        , KLUN=ILUN)
CALL STAT ("PSPSPG       ",  PSPSPG       , KLUN=ILUN)
CALL STAT ("PSPSPDG      ",  PSPSPDG      , KLUN=ILUN)
CALL STAT ("PSPSVDG      ",  PSPSVDG      , KLUN=ILUN)
!CALL STAT ("PSPTNDSI_VORG",  PSPTNDSI_VORG, KLUN=ILUN)
!CALL STAT ("PSPTNDSI_DIVG",  PSPTNDSI_DIVG, KLUN=ILUN)
!CALL STAT ("PSPTNDSI_TG  ",  PSPTNDSI_TG  , KLUN=ILUN)
!CALL STAT ("PSPTNDSI_SPDG",  PSPTNDSI_SPDG, KLUN=ILUN)
!CALL STAT ("PSPTNDSI_SVDG",  PSPTNDSI_SVDG, KLUN=ILUN)

CLOSE (ILUN)

END SUBROUTINE

END 

