INTERFACE
SUBROUTINE MXTURE(KLX,KLXS,KVX,KVXS,KIX,KIXS,KT1,KT2,PA,PB,PC,PD,PE,PY,PX)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN)  :: KLX
INTEGER(KIND=JPIM),INTENT(IN)  :: KLXS
INTEGER(KIND=JPIM),INTENT(IN)  :: KVX
INTEGER(KIND=JPIM),INTENT(IN)  :: KVXS
INTEGER(KIND=JPIM),INTENT(IN)  :: KIX
INTEGER(KIND=JPIM),INTENT(IN)  :: KIXS
INTEGER(KIND=JPIM),INTENT(IN)  :: KT1
INTEGER(KIND=JPIM),INTENT(IN)  :: KT2
REAL(KIND=JPRB) ,INTENT(IN)    :: PA(KLX,KVX)
REAL(KIND=JPRB) ,INTENT(IN)    :: PB(KLX,KVX)
REAL(KIND=JPRB) ,INTENT(IN)    :: PC(KLX,KVX)
REAL(KIND=JPRB) ,INTENT(IN)    :: PD(KLX,KVX)
REAL(KIND=JPRB) ,INTENT(IN)    :: PE(KLX,KVX)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PY(KIXS,KLX,KVXS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PX(KIXS,KLX,KVXS)
END SUBROUTINE MXTURE
END INTERFACE
