SUBROUTINE SPCSIDG_PART0TOT (YDGEOMETRY, YDDYN, YDRIP, KSTA, KEND, PSDIV,&
     & PSPDIVG,KM,KOFF,PLAPDI,PLAPIN)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN       , ONLY : TDYN
USE YOMRIP       , ONLY : TRIP
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TDYN)        ,INTENT(IN)    :: YDDYN
TYPE(TRIP)        ,INTENT(IN)    :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTA
INTEGER(KIND=JPIM),INTENT(IN)    :: KEND
INTEGER(KIND=JPIM),INTENT(IN)    :: KM
REAL(KIND=JPRB),   INTENT(INOUT) :: PSDIV  (KSTA:KEND,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB),   INTENT(IN)    :: PSPDIVG(KSTA:KEND,YDGEOMETRY%YRDIMV%NFLEVG)
INTEGER(KIND=JPIM),INTENT(IN)    :: KOFF
REAL(KIND=JPRB),   INTENT(IN)    :: PLAPDI(:)
REAL(KIND=JPRB),   INTENT(IN)    :: PLAPIN(:)


INTEGER(KIND=JPIM) :: JLEV,JSP
REAL (KIND=JPRB) :: ZBDT
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SPCSIDG_PART0TOT',0,ZHOOK_HANDLE)

ZBDT=YDDYN%RBTS2*YDRIP%TDT
IF (YDGEOMETRY%YRMP%NSPSTAF(0) .GT. 0) THEN
  !$OMP PARALLEL DO PRIVATE(JLEV,JSP)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JSP=KSTA,KEND
      IF (JSP .LE. 2*(YDGEOMETRY%YRDIM%NSMAX+1)) PSDIV(JSP,JLEV)=PSPDIVG(JSP,JLEV)-ZBDT*PLAPDI(KOFF+JSP)*PSDIV(JSP,JLEV)
      IF (JSP .GT. 2*(YDGEOMETRY%YRDIM%NSMAX+1)) PSDIV(JSP,JLEV)=PLAPIN(KOFF+JSP)*PSPDIVG(JSP,JLEV)-ZBDT*PSDIV(JSP,JLEV)
    ENDDO
  ENDDO
  !$OMP END PARALLEL DO
ELSE
  !$OMP PARALLEL DO PRIVATE(JLEV,JSP)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JSP=KSTA,KEND
       PSDIV(JSP,JLEV)=PLAPIN(KOFF+JSP)*PSPDIVG(JSP,JLEV)-ZBDT*PSDIV(JSP,JLEV) 
    ENDDO
  ENDDO
  !$OMP END PARALLEL DO
ENDIF

IF (LHOOK) CALL DR_HOOK('SPCSIDG_PART0TOT',1,ZHOOK_HANDLE)

END SUBROUTINE SPCSIDG_PART0TOT

