SUBROUTINE SPCSIDG_PART0NH (YDGEOMETRY, YDDYN, KSTA, KEND, PSRHS,&
     & PLAPIN,KM,KOFF,LDACC)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN       , ONLY : TDYN
USE YOMRIP       , ONLY : TRIP
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TDYN)        ,INTENT(IN)    :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTA
INTEGER(KIND=JPIM),INTENT(IN)    :: KEND
INTEGER(KIND=JPIM),INTENT(IN)    :: KM
REAL(KIND=JPRB),   INTENT(INOUT) :: PSRHS (KSTA:KEND,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB),   INTENT(IN)    :: PLAPIN(YDGEOMETRY%YRDIM%NSPEC2)
INTEGER(KIND=JPIM),INTENT(IN)    :: KOFF
LOGICAL, OPTIONAL, INTENT(IN)    :: LDACC

INTEGER(KIND=JPIM) :: JLEV,JSP
LOGICAL           :: LLACC

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SPCSIDG_PART0NH',0,ZHOOK_HANDLE)

LLACC=.FALSE.
IF (PRESENT(LDACC)) LLACC=LDACC

IF (LLACC) THEN

  IF (YDGEOMETRY%YRMP%NSPSTAF(0) .GT. 0) THEN
    !$ACC PARALLEL PRESENT(PSRHS,PLAPIN) PRIVATE(JSP,JLEV)
    !$ACC LOOP GANG VECTOR COLLAPSE(2)
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JSP=KSTA,KEND
        IF (JSP .GT. 2*(YDGEOMETRY%YRDIM%NSMAX+1)) PSRHS(JSP,JLEV)=PLAPIN(KOFF+JSP)*PSRHS(JSP,JLEV)
      ENDDO
    ENDDO
    !$ACC END PARALLEL 
  ELSE
    !$ACC PARALLEL PRESENT(PSRHS,PLAPIN) PRIVATE(JSP,JLEV)
    !$ACC LOOP GANG VECTOR COLLAPSE(2)
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JSP=KSTA,KEND
        PSRHS(JSP,JLEV)=PLAPIN(KOFF+JSP)*PSRHS(JSP,JLEV)
      ENDDO
    ENDDO
    !$ACC END PARALLEL
  ENDIF


ELSE

  IF (YDGEOMETRY%YRMP%NSPSTAF(0) .GT. 0) THEN
    !$OMP PARALLEL DO PRIVATE(JSP,JLEV)
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JSP=KSTA,KEND
        IF (JSP .GT. 2*(YDGEOMETRY%YRDIM%NSMAX+1)) PSRHS(JSP,JLEV)=PLAPIN(KOFF+JSP)*PSRHS(JSP,JLEV)
      ENDDO
    ENDDO
    !$OMP END PARALLEL DO
  ELSE
    !$OMP PARALLEL DO PRIVATE(JSP,JLEV)
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JSP=KSTA,KEND
        PSRHS(JSP,JLEV)=PLAPIN(KOFF+JSP)*PSRHS(JSP,JLEV)
      ENDDO
    ENDDO
    !$OMP END PARALLEL DO
  ENDIF

ENDIF

IF (LHOOK) CALL DR_HOOK('SPCSIDG_PART0NH',1,ZHOOK_HANDLE)

END SUBROUTINE SPCSIDG_PART0NH

