MODULE UTIL_TECMIP_MOD

USE YOECMIP, ONLY : TECMIP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TECMIP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TECMIP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TECMIP
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TECMIP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TECMIP (SELF, KLUN)

IMPLICIT NONE
TYPE (TECMIP), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LRLATCLI, LRLONCLI, LROZT1, LRPROC1, LRSINC1, LZOZCL
WRITE (KLUN) SELF%NRCP
WRITE (KLUN) SELF%NO3CMIP
WRITE (KLUN) SELF%NGHGCMIP
WRITE (KLUN) SELF%NCMIPFIXYR
WRITE (KLUN) SELF%NCURRYR
WRITE (KLUN) SELF%GHGDATADIR
WRITE (KLUN) SELF%CSOLARDATA
WRITE (KLUN) SELF%CO3DATADIR
WRITE (KLUN) SELF%CO3DATAFIL
LZOZCL = ALLOCATED (SELF%ZOZCL)
WRITE (KLUN) LZOZCL
IF (LZOZCL) THEN
  WRITE (KLUN) LBOUND (SELF%ZOZCL)
  WRITE (KLUN) UBOUND (SELF%ZOZCL)
  WRITE (KLUN) SELF%ZOZCL
ENDIF
LRSINC1 = ALLOCATED (SELF%RSINC1)
WRITE (KLUN) LRSINC1
IF (LRSINC1) THEN
  WRITE (KLUN) LBOUND (SELF%RSINC1)
  WRITE (KLUN) UBOUND (SELF%RSINC1)
  WRITE (KLUN) SELF%RSINC1
ENDIF
LRPROC1 = ALLOCATED (SELF%RPROC1)
WRITE (KLUN) LRPROC1
IF (LRPROC1) THEN
  WRITE (KLUN) LBOUND (SELF%RPROC1)
  WRITE (KLUN) UBOUND (SELF%RPROC1)
  WRITE (KLUN) SELF%RPROC1
ENDIF
LRLATCLI = ALLOCATED (SELF%RLATCLI)
WRITE (KLUN) LRLATCLI
IF (LRLATCLI) THEN
  WRITE (KLUN) LBOUND (SELF%RLATCLI)
  WRITE (KLUN) UBOUND (SELF%RLATCLI)
  WRITE (KLUN) SELF%RLATCLI
ENDIF
LRLONCLI = ALLOCATED (SELF%RLONCLI)
WRITE (KLUN) LRLONCLI
IF (LRLONCLI) THEN
  WRITE (KLUN) LBOUND (SELF%RLONCLI)
  WRITE (KLUN) UBOUND (SELF%RLONCLI)
  WRITE (KLUN) SELF%RLONCLI
ENDIF
LROZT1 = ALLOCATED (SELF%ROZT1)
WRITE (KLUN) LROZT1
IF (LROZT1) THEN
  WRITE (KLUN) LBOUND (SELF%ROZT1)
  WRITE (KLUN) UBOUND (SELF%ROZT1)
  WRITE (KLUN) SELF%ROZT1
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TECMIP (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TECMIP), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LRLATCLI, LRLONCLI, LROZT1, LRPROC1, LRSINC1, LZOZCL
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP4 (:,:,:,:)
READ (KLUN) SELF%NRCP
READ (KLUN) SELF%NO3CMIP
READ (KLUN) SELF%NGHGCMIP
READ (KLUN) SELF%NCMIPFIXYR
READ (KLUN) SELF%NCURRYR
READ (KLUN) SELF%GHGDATADIR
READ (KLUN) SELF%CSOLARDATA
READ (KLUN) SELF%CO3DATADIR
READ (KLUN) SELF%CO3DATAFIL
READ (KLUN) LZOZCL
IF (LZOZCL) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (SELF%ZOZCL (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(SELF%ZOZCL,1):UBOUND(SELF%ZOZCL,1), LBOUND(SELF%ZOZCL,2):UBOUND(SELF%ZOZCL,2), LBOUND(SELF%ZOZCL,3):UBOUND(SELF%ZOZCL,3), LBOUND(SELF%ZOZCL,4):UBOUND(SELF%ZOZCL,4)))
  READ (KLUN) ZTMP4
  SELF%ZOZCL = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
READ (KLUN) LRSINC1
IF (LRSINC1) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RSINC1 (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RSINC1,1):UBOUND(SELF%RSINC1,1)))
  READ (KLUN) ZTMP1
  SELF%RSINC1 = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRPROC1
IF (LRPROC1) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RPROC1 (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RPROC1,1):UBOUND(SELF%RPROC1,1)))
  READ (KLUN) ZTMP1
  SELF%RPROC1 = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLATCLI
IF (LRLATCLI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RLATCLI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RLATCLI,1):UBOUND(SELF%RLATCLI,1)))
  READ (KLUN) ZTMP1
  SELF%RLATCLI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLONCLI
IF (LRLONCLI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RLONCLI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RLONCLI,1):UBOUND(SELF%RLONCLI,1)))
  READ (KLUN) ZTMP1
  SELF%RLONCLI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LROZT1
IF (LROZT1) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%ROZT1 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%ROZT1,1):UBOUND(SELF%ROZT1,1), LBOUND(SELF%ROZT1,2):UBOUND(SELF%ROZT1,2), LBOUND(SELF%ROZT1,3):UBOUND(SELF%ROZT1,3)))
  READ (KLUN) ZTMP3
  SELF%ROZT1 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TECMIP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TECMIP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRLATCLI, LRLONCLI, LROZT1, LRPROC1, LRSINC1, LZOZCL

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LZOZCL = ALLOCATED (SELF%ZOZCL)
IF (LZOZCL) THEN
  !$ACC ENTER DATA CREATE (SELF%ZOZCL)
  !$ACC UPDATE DEVICE (SELF%ZOZCL)
  !$ACC ENTER DATA ATTACH (SELF%ZOZCL)
ENDIF

LRSINC1 = ALLOCATED (SELF%RSINC1)
IF (LRSINC1) THEN
  !$ACC ENTER DATA CREATE (SELF%RSINC1)
  !$ACC UPDATE DEVICE (SELF%RSINC1)
  !$ACC ENTER DATA ATTACH (SELF%RSINC1)
ENDIF

LRPROC1 = ALLOCATED (SELF%RPROC1)
IF (LRPROC1) THEN
  !$ACC ENTER DATA CREATE (SELF%RPROC1)
  !$ACC UPDATE DEVICE (SELF%RPROC1)
  !$ACC ENTER DATA ATTACH (SELF%RPROC1)
ENDIF

LRLATCLI = ALLOCATED (SELF%RLATCLI)
IF (LRLATCLI) THEN
  !$ACC ENTER DATA CREATE (SELF%RLATCLI)
  !$ACC UPDATE DEVICE (SELF%RLATCLI)
  !$ACC ENTER DATA ATTACH (SELF%RLATCLI)
ENDIF

LRLONCLI = ALLOCATED (SELF%RLONCLI)
IF (LRLONCLI) THEN
  !$ACC ENTER DATA CREATE (SELF%RLONCLI)
  !$ACC UPDATE DEVICE (SELF%RLONCLI)
  !$ACC ENTER DATA ATTACH (SELF%RLONCLI)
ENDIF

LROZT1 = ALLOCATED (SELF%ROZT1)
IF (LROZT1) THEN
  !$ACC ENTER DATA CREATE (SELF%ROZT1)
  !$ACC UPDATE DEVICE (SELF%ROZT1)
  !$ACC ENTER DATA ATTACH (SELF%ROZT1)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TECMIP (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TECMIP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRLATCLI, LRLONCLI, LROZT1, LRPROC1, LRSINC1, LZOZCL

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LZOZCL = ALLOCATED (SELF%ZOZCL)
IF (LZOZCL) THEN
  !$ACC EXIT DATA DETACH (SELF%ZOZCL)
  !$ACC EXIT DATA DETACH (SELF%ZOZCL)
ENDIF

LRSINC1 = ALLOCATED (SELF%RSINC1)
IF (LRSINC1) THEN
  !$ACC EXIT DATA DETACH (SELF%RSINC1)
  !$ACC EXIT DATA DETACH (SELF%RSINC1)
ENDIF

LRPROC1 = ALLOCATED (SELF%RPROC1)
IF (LRPROC1) THEN
  !$ACC EXIT DATA DETACH (SELF%RPROC1)
  !$ACC EXIT DATA DETACH (SELF%RPROC1)
ENDIF

LRLATCLI = ALLOCATED (SELF%RLATCLI)
IF (LRLATCLI) THEN
  !$ACC EXIT DATA DETACH (SELF%RLATCLI)
  !$ACC EXIT DATA DETACH (SELF%RLATCLI)
ENDIF

LRLONCLI = ALLOCATED (SELF%RLONCLI)
IF (LRLONCLI) THEN
  !$ACC EXIT DATA DETACH (SELF%RLONCLI)
  !$ACC EXIT DATA DETACH (SELF%RLONCLI)
ENDIF

LROZT1 = ALLOCATED (SELF%ROZT1)
IF (LROZT1) THEN
  !$ACC EXIT DATA DETACH (SELF%ROZT1)
  !$ACC EXIT DATA DETACH (SELF%ROZT1)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
