MODULE UTIL_GEOMETRY_MOD

USE TYPE_GEOMETRY, ONLY : GEOMETRY

INTERFACE SAVE
MODULE PROCEDURE SAVE_GEOMETRY
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_GEOMETRY
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_GEOMETRY
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_GEOMETRY
END INTERFACE



CONTAINS

SUBROUTINE SAVE_GEOMETRY (SELF, KLUN)
USE UTIL_TCSGLEG_MOD
USE UTIL_TDIMV_MOD
USE UTIL_TDIM_MOD
USE UTIL_TEDIM_MOD
USE UTIL_TEGEO_MOD
USE UTIL_TEGSL_MOD
USE UTIL_TEMMP_MOD
USE UTIL_TGEM_MOD
USE UTIL_TLAP_MOD
USE UTIL_TLEP_MOD
USE UTIL_TMP_MOD
USE UTIL_TSPGEOM_MOD
USE UTIL_TSTA_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVERTICAL_GEOM_MOD
IMPLICIT NONE
TYPE (GEOMETRY), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LNHX_GEOM
CALL SAVE_TVERTICAL_GEOM (SELF%YRVERT_GEOM, KLUN)
CALL SAVE_TSTA (SELF%YRSTA, KLUN)
CALL SAVE_TLAP (SELF%YRLAP, KLUN)
CALL SAVE_TCSGLEG (SELF%YRCSGLEG, KLUN)
CALL SAVE_TDIM (SELF%YRDIM, KLUN)
CALL SAVE_TDIMV (SELF%YRDIMV, KLUN)
CALL SAVE_TMP (SELF%YRMP, KLUN)
CALL SAVE_TGEM (SELF%YRGEM, KLUN)
WRITE (KLUN) SELF%AD_GEOM
CALL SAVE_TSPGEOM (SELF%YSPGEOM, KLUN)
CALL SAVE_TVAB (SELF%YVABIO, KLUN)
CALL SAVE_TEDIM (SELF%YREDIM, KLUN)
CALL SAVE_TEGEO (SELF%YREGEO, KLUN)
CALL SAVE_TEMMP (SELF%YREMP, KLUN)
CALL SAVE_TLEP (SELF%YRELAP, KLUN)
CALL SAVE_TEGSL (SELF%YREGSL, KLUN)
END SUBROUTINE

SUBROUTINE LOAD_GEOMETRY (SELF, KLUN)
USE UTIL_TCSGLEG_MOD
USE UTIL_TDIMV_MOD
USE UTIL_TDIM_MOD
USE UTIL_TEDIM_MOD
USE UTIL_TEGEO_MOD
USE UTIL_TEGSL_MOD
USE UTIL_TEMMP_MOD
USE UTIL_TGEM_MOD
USE UTIL_TLAP_MOD
USE UTIL_TLEP_MOD
USE UTIL_TMP_MOD
USE UTIL_TSPGEOM_MOD
USE UTIL_TSTA_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVERTICAL_GEOM_MOD

IMPLICIT NONE
TYPE (GEOMETRY), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%LNHX_GEOM
CALL LOAD_TVERTICAL_GEOM (SELF%YRVERT_GEOM, KLUN)
CALL LOAD_TSTA (SELF%YRSTA, KLUN)
CALL LOAD_TLAP (SELF%YRLAP, KLUN)
CALL LOAD_TCSGLEG (SELF%YRCSGLEG, KLUN)
CALL LOAD_TDIM (SELF%YRDIM, KLUN)
CALL LOAD_TDIMV (SELF%YRDIMV, KLUN)
CALL LOAD_TMP (SELF%YRMP, KLUN)
CALL LOAD_TGEM (SELF%YRGEM, KLUN)
READ (KLUN) SELF%AD_GEOM
CALL LOAD_TSPGEOM (SELF%YSPGEOM, KLUN)
CALL LOAD_TVAB (SELF%YVABIO, KLUN)
CALL LOAD_TEDIM (SELF%YREDIM, KLUN)
CALL LOAD_TEGEO (SELF%YREGEO, KLUN)
CALL LOAD_TEMMP (SELF%YREMP, KLUN)
CALL LOAD_TLEP (SELF%YRELAP, KLUN)
CALL LOAD_TEGSL (SELF%YREGSL, KLUN)
END SUBROUTINE


SUBROUTINE COPY_GEOMETRY (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_TCSGLEG_MOD
USE UTIL_TDIMV_MOD
USE UTIL_TDIM_MOD
USE UTIL_TEDIM_MOD
USE UTIL_TEGEO_MOD
USE UTIL_TEGSL_MOD
USE UTIL_TEMMP_MOD
USE UTIL_TGEM_MOD
USE UTIL_TLAP_MOD
USE UTIL_TLEP_MOD
USE UTIL_TMP_MOD
USE UTIL_TSPGEOM_MOD
USE UTIL_TSTA_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVERTICAL_GEOM_MOD
IMPLICIT NONE
TYPE (GEOMETRY), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

CALL COPY_TVERTICAL_GEOM (SELF%YRVERT_GEOM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TSTA (SELF%YRSTA, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TLAP (SELF%YRLAP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TCSGLEG (SELF%YRCSGLEG, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TDIM (SELF%YRDIM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TDIMV (SELF%YRDIMV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TMP (SELF%YRMP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TGEM (SELF%YRGEM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TSPGEOM (SELF%YSPGEOM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TVAB (SELF%YVABIO, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TEDIM (SELF%YREDIM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TEGEO (SELF%YREGEO, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TEMMP (SELF%YREMP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TLEP (SELF%YRELAP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TEGSL (SELF%YREGSL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE



     



SUBROUTINE WIPE_GEOMETRY (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_TCSGLEG_MOD
USE UTIL_TDIMV_MOD
USE UTIL_TDIM_MOD
USE UTIL_TEDIM_MOD
USE UTIL_TEGEO_MOD
USE UTIL_TEGSL_MOD
USE UTIL_TEMMP_MOD
USE UTIL_TGEM_MOD
USE UTIL_TLAP_MOD
USE UTIL_TLEP_MOD
USE UTIL_TMP_MOD
USE UTIL_TSPGEOM_MOD
USE UTIL_TSTA_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVERTICAL_GEOM_MOD
IMPLICIT NONE
TYPE (GEOMETRY), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

CALL WIPE_TVERTICAL_GEOM (SELF%YRVERT_GEOM, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TSTA (SELF%YRSTA, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TLAP (SELF%YRLAP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TCSGLEG (SELF%YRCSGLEG, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TDIM (SELF%YRDIM, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TDIMV (SELF%YRDIMV, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TMP (SELF%YRMP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TGEM (SELF%YRGEM, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TSPGEOM (SELF%YSPGEOM, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TVAB (SELF%YVABIO, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TEDIM (SELF%YREDIM, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TEGEO (SELF%YREGEO, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TEMMP (SELF%YREMP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TLEP (SELF%YRELAP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TEGSL (SELF%YREGSL, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
