MODULE UTIL_TSPGEOM_MOD

USE TYPE_SPGEOM, ONLY : TSPGEOM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TSPGEOM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSPGEOM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TSPGEOM
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TSPGEOM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TSPGEOM (SELF, KLUN)

IMPLICIT NONE
TYPE (TSPGEOM), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LGMR, LSCGMAP
LGMR = ALLOCATED (SELF%GMR)
WRITE (KLUN) LGMR
IF (LGMR) THEN
  WRITE (KLUN) LBOUND (SELF%GMR)
  WRITE (KLUN) UBOUND (SELF%GMR)
  WRITE (KLUN) SELF%GMR
ENDIF
LSCGMAP = ALLOCATED (SELF%SCGMAP)
WRITE (KLUN) LSCGMAP
IF (LSCGMAP) THEN
  WRITE (KLUN) LBOUND (SELF%SCGMAP)
  WRITE (KLUN) UBOUND (SELF%SCGMAP)
  WRITE (KLUN) SELF%SCGMAP
ENDIF
WRITE (KLUN) SELF%ESCGMAP
END SUBROUTINE

SUBROUTINE LOAD_TSPGEOM (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TSPGEOM), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LGMR, LSCGMAP
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
READ (KLUN) LGMR
IF (LGMR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%GMR (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%GMR,1):UBOUND(SELF%GMR,1), LBOUND(SELF%GMR,2):UBOUND(SELF%GMR,2)))
  READ (KLUN) ZTMP2
  SELF%GMR = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSCGMAP
IF (LSCGMAP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SCGMAP (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SCGMAP,1):UBOUND(SELF%SCGMAP,1), LBOUND(SELF%SCGMAP,2):UBOUND(SELF%SCGMAP,2)))
  READ (KLUN) ZTMP2
  SELF%SCGMAP = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
ALLOCATE (ZTMP1(LBOUND(SELF%ESCGMAP,1):UBOUND(SELF%ESCGMAP,1)))
READ (KLUN) ZTMP1
SELF%ESCGMAP = ZTMP1
DEALLOCATE (ZTMP1)
END SUBROUTINE


SUBROUTINE COPY_TSPGEOM (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TSPGEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGMR, LSCGMAP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LGMR = ALLOCATED (SELF%GMR)
IF (LGMR) THEN
  !$ACC ENTER DATA CREATE (SELF%GMR)
  !$ACC UPDATE DEVICE (SELF%GMR)
  !$ACC ENTER DATA ATTACH (SELF%GMR)
ENDIF

LSCGMAP = ALLOCATED (SELF%SCGMAP)
IF (LSCGMAP) THEN
  !$ACC ENTER DATA CREATE (SELF%SCGMAP)
  !$ACC UPDATE DEVICE (SELF%SCGMAP)
  !$ACC ENTER DATA ATTACH (SELF%SCGMAP)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TSPGEOM (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TSPGEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGMR, LSCGMAP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LGMR = ALLOCATED (SELF%GMR)
IF (LGMR) THEN
  !$ACC EXIT DATA DETACH (SELF%GMR)
  !$ACC EXIT DATA DETACH (SELF%GMR)
ENDIF

LSCGMAP = ALLOCATED (SELF%SCGMAP)
IF (LSCGMAP) THEN
  !$ACC EXIT DATA DETACH (SELF%SCGMAP)
  !$ACC EXIT DATA DETACH (SELF%SCGMAP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
