MODULE UTIL_TXYBDER_MOD

USE INTDYN_MOD, ONLY : TXYBDER

INTERFACE SAVE
MODULE PROCEDURE SAVE_TXYBDER
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TXYBDER
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TXYBDER
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TXYBDER
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TXYBDER (SELF, KLUN)

IMPLICIT NONE
TYPE (TXYBDER), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%M_LNPRL
WRITE (KLUN) SELF%M_LNPRM
WRITE (KLUN) SELF%M_ALPHL
WRITE (KLUN) SELF%M_ALPHM
WRITE (KLUN) SELF%M_ALPHPLL
WRITE (KLUN) SELF%M_ALPHPLM
WRITE (KLUN) SELF%M_COEFD
WRITE (KLUN) SELF%M_COEFA
WRITE (KLUN) SELF%M_COEFAPL
WRITE (KLUN) SELF%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TXYBDER (SELF, KLUN)

IMPLICIT NONE
TYPE (TXYBDER), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%M_LNPRL
READ (KLUN) SELF%M_LNPRM
READ (KLUN) SELF%M_ALPHL
READ (KLUN) SELF%M_ALPHM
READ (KLUN) SELF%M_ALPHPLL
READ (KLUN) SELF%M_ALPHPLM
READ (KLUN) SELF%M_COEFD
READ (KLUN) SELF%M_COEFA
READ (KLUN) SELF%M_COEFAPL
READ (KLUN) SELF%NDIM
END SUBROUTINE


SUBROUTINE COPY_TXYBDER (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TXYBDER), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TXYBDER (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TXYBDER), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
