MODULE UTIL_TEDIM_MOD

USE YEMDIM, ONLY : TEDIM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEDIM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEDIM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEDIM
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEDIM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEDIM (SELF, KLUN)

IMPLICIT NONE
TYPE (TEDIM), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LNISMAX, LNISNAX
WRITE (KLUN) SELF%NSECPLG
WRITE (KLUN) SELF%NBZONG
WRITE (KLUN) SELF%NBZONL
WRITE (KLUN) SELF%NBZONU
WRITE (KLUN) SELF%NNOEXTZG
WRITE (KLUN) SELF%NNOEXTZL
LNISMAX = ASSOCIATED (SELF%NISMAX)
WRITE (KLUN) LNISMAX
IF (LNISMAX) THEN
  WRITE (KLUN) LBOUND (SELF%NISMAX)
  WRITE (KLUN) UBOUND (SELF%NISMAX)
  WRITE (KLUN) SELF%NISMAX
ENDIF
LNISNAX = ASSOCIATED (SELF%NISNAX)
WRITE (KLUN) LNISNAX
IF (LNISNAX) THEN
  WRITE (KLUN) LBOUND (SELF%NISNAX)
  WRITE (KLUN) UBOUND (SELF%NISNAX)
  WRITE (KLUN) SELF%NISNAX
ENDIF
WRITE (KLUN) SELF%LBIPINCI
WRITE (KLUN) SELF%NBIPINCIX
WRITE (KLUN) SELF%NBIPINCIY
WRITE (KLUN) SELF%NEDOM
END SUBROUTINE

SUBROUTINE LOAD_TEDIM (SELF, KLUN)

IMPLICIT NONE
TYPE (TEDIM), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LNISMAX, LNISNAX
READ (KLUN) SELF%NSECPLG
READ (KLUN) SELF%NBZONG
READ (KLUN) SELF%NBZONL
READ (KLUN) SELF%NBZONU
READ (KLUN) SELF%NNOEXTZG
READ (KLUN) SELF%NNOEXTZL
READ (KLUN) LNISMAX
IF (LNISMAX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NISMAX (IL1(1):IU1(1)))
  READ (KLUN) SELF%NISMAX
ELSE
  NULLIFY (SELF%NISMAX)
ENDIF
READ (KLUN) LNISNAX
IF (LNISNAX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NISNAX (IL1(1):IU1(1)))
  READ (KLUN) SELF%NISNAX
ELSE
  NULLIFY (SELF%NISNAX)
ENDIF
READ (KLUN) SELF%LBIPINCI
READ (KLUN) SELF%NBIPINCIX
READ (KLUN) SELF%NBIPINCIY
READ (KLUN) SELF%NEDOM
END SUBROUTINE


SUBROUTINE COPY_TEDIM (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEDIM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LNISMAX, LNISNAX

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LNISMAX = ASSOCIATED (SELF%NISMAX)
IF (LNISMAX) THEN
  !$ACC ENTER DATA CREATE (SELF%NISMAX)
  !$ACC UPDATE DEVICE (SELF%NISMAX)
  !$ACC ENTER DATA ATTACH (SELF%NISMAX)
ENDIF

LNISNAX = ASSOCIATED (SELF%NISNAX)
IF (LNISNAX) THEN
  !$ACC ENTER DATA CREATE (SELF%NISNAX)
  !$ACC UPDATE DEVICE (SELF%NISNAX)
  !$ACC ENTER DATA ATTACH (SELF%NISNAX)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TEDIM (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEDIM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LNISMAX, LNISNAX

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LNISMAX = ASSOCIATED (SELF%NISMAX)
IF (LNISMAX) THEN
  !$ACC EXIT DATA DETACH (SELF%NISMAX)
  !$ACC EXIT DATA DETACH (SELF%NISMAX)
ENDIF

LNISNAX = ASSOCIATED (SELF%NISNAX)
IF (LNISNAX) THEN
  !$ACC EXIT DATA DETACH (SELF%NISNAX)
  !$ACC EXIT DATA DETACH (SELF%NISNAX)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
