MODULE UTIL_TLAP_MOD

USE YOMLAP, ONLY : TLAP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TLAP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLAP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TLAP
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TLAP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TLAP (SELF, KLUN)

IMPLICIT NONE
TYPE (TLAP), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LMYMS, LNASM0, LNASM0G, LNASN0, LNSE0L, LNSPZERO, LNVALUE, LRLAPDI, LRLAPIN
LNASN0 = ALLOCATED (SELF%NASN0)
WRITE (KLUN) LNASN0
IF (LNASN0) THEN
  WRITE (KLUN) LBOUND (SELF%NASN0)
  WRITE (KLUN) UBOUND (SELF%NASN0)
  WRITE (KLUN) SELF%NASN0
ENDIF
LNASM0 = ALLOCATED (SELF%NASM0)
WRITE (KLUN) LNASM0
IF (LNASM0) THEN
  WRITE (KLUN) LBOUND (SELF%NASM0)
  WRITE (KLUN) UBOUND (SELF%NASM0)
  WRITE (KLUN) SELF%NASM0
ENDIF
LNASM0G = ALLOCATED (SELF%NASM0G)
WRITE (KLUN) LNASM0G
IF (LNASM0G) THEN
  WRITE (KLUN) LBOUND (SELF%NASM0G)
  WRITE (KLUN) UBOUND (SELF%NASM0G)
  WRITE (KLUN) SELF%NASM0G
ENDIF
LNVALUE = ALLOCATED (SELF%NVALUE)
WRITE (KLUN) LNVALUE
IF (LNVALUE) THEN
  WRITE (KLUN) LBOUND (SELF%NVALUE)
  WRITE (KLUN) UBOUND (SELF%NVALUE)
  WRITE (KLUN) SELF%NVALUE
ENDIF
LMYMS = ALLOCATED (SELF%MYMS)
WRITE (KLUN) LMYMS
IF (LMYMS) THEN
  WRITE (KLUN) LBOUND (SELF%MYMS)
  WRITE (KLUN) UBOUND (SELF%MYMS)
  WRITE (KLUN) SELF%MYMS
ENDIF
LNSPZERO = ALLOCATED (SELF%NSPZERO)
WRITE (KLUN) LNSPZERO
IF (LNSPZERO) THEN
  WRITE (KLUN) LBOUND (SELF%NSPZERO)
  WRITE (KLUN) UBOUND (SELF%NSPZERO)
  WRITE (KLUN) SELF%NSPZERO
ENDIF
LNSE0L = ALLOCATED (SELF%NSE0L)
WRITE (KLUN) LNSE0L
IF (LNSE0L) THEN
  WRITE (KLUN) LBOUND (SELF%NSE0L)
  WRITE (KLUN) UBOUND (SELF%NSE0L)
  WRITE (KLUN) SELF%NSE0L
ENDIF
LRLAPDI = ALLOCATED (SELF%RLAPDI)
WRITE (KLUN) LRLAPDI
IF (LRLAPDI) THEN
  WRITE (KLUN) LBOUND (SELF%RLAPDI)
  WRITE (KLUN) UBOUND (SELF%RLAPDI)
  WRITE (KLUN) SELF%RLAPDI
ENDIF
LRLAPIN = ALLOCATED (SELF%RLAPIN)
WRITE (KLUN) LRLAPIN
IF (LRLAPIN) THEN
  WRITE (KLUN) LBOUND (SELF%RLAPIN)
  WRITE (KLUN) UBOUND (SELF%RLAPIN)
  WRITE (KLUN) SELF%RLAPIN
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TLAP (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TLAP), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LMYMS, LNASM0, LNASM0G, LNASN0, LNSE0L, LNSPZERO, LNVALUE, LRLAPDI, LRLAPIN
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
READ (KLUN) LNASN0
IF (LNASN0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NASN0 (IL1(1):IU1(1)))
  READ (KLUN) SELF%NASN0
ENDIF
READ (KLUN) LNASM0
IF (LNASM0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NASM0 (IL1(1):IU1(1)))
  READ (KLUN) SELF%NASM0
ENDIF
READ (KLUN) LNASM0G
IF (LNASM0G) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NASM0G (IL1(1):IU1(1)))
  READ (KLUN) SELF%NASM0G
ENDIF
READ (KLUN) LNVALUE
IF (LNVALUE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NVALUE (IL1(1):IU1(1)))
  READ (KLUN) SELF%NVALUE
ENDIF
READ (KLUN) LMYMS
IF (LMYMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%MYMS (IL1(1):IU1(1)))
  READ (KLUN) SELF%MYMS
ENDIF
READ (KLUN) LNSPZERO
IF (LNSPZERO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NSPZERO (IL1(1):IU1(1)))
  READ (KLUN) SELF%NSPZERO
ENDIF
READ (KLUN) LNSE0L
IF (LNSE0L) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NSE0L (IL1(1):IU1(1)))
  READ (KLUN) SELF%NSE0L
ENDIF
READ (KLUN) LRLAPDI
IF (LRLAPDI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RLAPDI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RLAPDI,1):UBOUND(SELF%RLAPDI,1)))
  READ (KLUN) ZTMP1
  SELF%RLAPDI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLAPIN
IF (LRLAPIN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RLAPIN (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RLAPIN,1):UBOUND(SELF%RLAPIN,1)))
  READ (KLUN) ZTMP1
  SELF%RLAPIN = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TLAP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TLAP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LMYMS, LNASM0, LNASM0G, LNASN0, LNSE0L, LNSPZERO, LNVALUE, LRLAPDI, LRLAPIN

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LNASN0 = ALLOCATED (SELF%NASN0)
IF (LNASN0) THEN
  !$ACC ENTER DATA CREATE (SELF%NASN0)
  !$ACC UPDATE DEVICE (SELF%NASN0)
  !$ACC ENTER DATA ATTACH (SELF%NASN0)
ENDIF

LNASM0 = ALLOCATED (SELF%NASM0)
IF (LNASM0) THEN
  !$ACC ENTER DATA CREATE (SELF%NASM0)
  !$ACC UPDATE DEVICE (SELF%NASM0)
  !$ACC ENTER DATA ATTACH (SELF%NASM0)
ENDIF

LNASM0G = ALLOCATED (SELF%NASM0G)
IF (LNASM0G) THEN
  !$ACC ENTER DATA CREATE (SELF%NASM0G)
  !$ACC UPDATE DEVICE (SELF%NASM0G)
  !$ACC ENTER DATA ATTACH (SELF%NASM0G)
ENDIF

LNVALUE = ALLOCATED (SELF%NVALUE)
IF (LNVALUE) THEN
  !$ACC ENTER DATA CREATE (SELF%NVALUE)
  !$ACC UPDATE DEVICE (SELF%NVALUE)
  !$ACC ENTER DATA ATTACH (SELF%NVALUE)
ENDIF

LMYMS = ALLOCATED (SELF%MYMS)
IF (LMYMS) THEN
  !$ACC ENTER DATA CREATE (SELF%MYMS)
  !$ACC UPDATE DEVICE (SELF%MYMS)
  !$ACC ENTER DATA ATTACH (SELF%MYMS)
ENDIF

LNSPZERO = ALLOCATED (SELF%NSPZERO)
IF (LNSPZERO) THEN
  !$ACC ENTER DATA CREATE (SELF%NSPZERO)
  !$ACC UPDATE DEVICE (SELF%NSPZERO)
  !$ACC ENTER DATA ATTACH (SELF%NSPZERO)
ENDIF

LNSE0L = ALLOCATED (SELF%NSE0L)
IF (LNSE0L) THEN
  !$ACC ENTER DATA CREATE (SELF%NSE0L)
  !$ACC UPDATE DEVICE (SELF%NSE0L)
  !$ACC ENTER DATA ATTACH (SELF%NSE0L)
ENDIF

LRLAPDI = ALLOCATED (SELF%RLAPDI)
IF (LRLAPDI) THEN
  !$ACC ENTER DATA CREATE (SELF%RLAPDI)
  !$ACC UPDATE DEVICE (SELF%RLAPDI)
  !$ACC ENTER DATA ATTACH (SELF%RLAPDI)
ENDIF

LRLAPIN = ALLOCATED (SELF%RLAPIN)
IF (LRLAPIN) THEN
  !$ACC ENTER DATA CREATE (SELF%RLAPIN)
  !$ACC UPDATE DEVICE (SELF%RLAPIN)
  !$ACC ENTER DATA ATTACH (SELF%RLAPIN)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TLAP (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TLAP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LMYMS, LNASM0, LNASM0G, LNASN0, LNSE0L, LNSPZERO, LNVALUE, LRLAPDI, LRLAPIN

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LNASN0 = ALLOCATED (SELF%NASN0)
IF (LNASN0) THEN
  !$ACC EXIT DATA DETACH (SELF%NASN0)
  !$ACC EXIT DATA DETACH (SELF%NASN0)
ENDIF

LNASM0 = ALLOCATED (SELF%NASM0)
IF (LNASM0) THEN
  !$ACC EXIT DATA DETACH (SELF%NASM0)
  !$ACC EXIT DATA DETACH (SELF%NASM0)
ENDIF

LNASM0G = ALLOCATED (SELF%NASM0G)
IF (LNASM0G) THEN
  !$ACC EXIT DATA DETACH (SELF%NASM0G)
  !$ACC EXIT DATA DETACH (SELF%NASM0G)
ENDIF

LNVALUE = ALLOCATED (SELF%NVALUE)
IF (LNVALUE) THEN
  !$ACC EXIT DATA DETACH (SELF%NVALUE)
  !$ACC EXIT DATA DETACH (SELF%NVALUE)
ENDIF

LMYMS = ALLOCATED (SELF%MYMS)
IF (LMYMS) THEN
  !$ACC EXIT DATA DETACH (SELF%MYMS)
  !$ACC EXIT DATA DETACH (SELF%MYMS)
ENDIF

LNSPZERO = ALLOCATED (SELF%NSPZERO)
IF (LNSPZERO) THEN
  !$ACC EXIT DATA DETACH (SELF%NSPZERO)
  !$ACC EXIT DATA DETACH (SELF%NSPZERO)
ENDIF

LNSE0L = ALLOCATED (SELF%NSE0L)
IF (LNSE0L) THEN
  !$ACC EXIT DATA DETACH (SELF%NSE0L)
  !$ACC EXIT DATA DETACH (SELF%NSE0L)
ENDIF

LRLAPDI = ALLOCATED (SELF%RLAPDI)
IF (LRLAPDI) THEN
  !$ACC EXIT DATA DETACH (SELF%RLAPDI)
  !$ACC EXIT DATA DETACH (SELF%RLAPDI)
ENDIF

LRLAPIN = ALLOCATED (SELF%RLAPIN)
IF (LRLAPIN) THEN
  !$ACC EXIT DATA DETACH (SELF%RLAPIN)
  !$ACC EXIT DATA DETACH (SELF%RLAPIN)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
