MODULE UTIL_TSWE_MOD

USE YOMSWE, ONLY : TSWE

INTERFACE SAVE
MODULE PROCEDURE SAVE_TSWE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSWE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TSWE
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TSWE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TSWE (SELF, KLUN)

IMPLICIT NONE
TYPE (TSWE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%ALPHASWE
WRITE (KLUN) SELF%GMUCENSWE
END SUBROUTINE

SUBROUTINE LOAD_TSWE (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TSWE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
SELF%ALPHASWE = ZTMP0
READ (KLUN) ZTMP0
SELF%GMUCENSWE = ZTMP0
END SUBROUTINE


SUBROUTINE COPY_TSWE (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TSWE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TSWE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TSWE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
