MODULE UTIL_TMP_MOD

USE YOMMP, ONLY : TMP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TMP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TMP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TMP
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TMP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TMP (SELF, KLUN)

IMPLICIT NONE
TYPE (TMP), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP
LNUMPP = ALLOCATED (SELF%NUMPP)
WRITE (KLUN) LNUMPP
IF (LNUMPP) THEN
  WRITE (KLUN) LBOUND (SELF%NUMPP)
  WRITE (KLUN) UBOUND (SELF%NUMPP)
  WRITE (KLUN) SELF%NUMPP
ENDIF
LNPROCM = ALLOCATED (SELF%NPROCM)
WRITE (KLUN) LNPROCM
IF (LNPROCM) THEN
  WRITE (KLUN) LBOUND (SELF%NPROCM)
  WRITE (KLUN) UBOUND (SELF%NPROCM)
  WRITE (KLUN) SELF%NPROCM
ENDIF
LNPTRMS = ALLOCATED (SELF%NPTRMS)
WRITE (KLUN) LNPTRMS
IF (LNPTRMS) THEN
  WRITE (KLUN) LBOUND (SELF%NPTRMS)
  WRITE (KLUN) UBOUND (SELF%NPTRMS)
  WRITE (KLUN) SELF%NPTRMS
ENDIF
LNALLMS = ALLOCATED (SELF%NALLMS)
WRITE (KLUN) LNALLMS
IF (LNALLMS) THEN
  WRITE (KLUN) LBOUND (SELF%NALLMS)
  WRITE (KLUN) UBOUND (SELF%NALLMS)
  WRITE (KLUN) SELF%NALLMS
ENDIF
LNPTRLS = ALLOCATED (SELF%NPTRLS)
WRITE (KLUN) LNPTRLS
IF (LNPTRLS) THEN
  WRITE (KLUN) LBOUND (SELF%NPTRLS)
  WRITE (KLUN) UBOUND (SELF%NPTRLS)
  WRITE (KLUN) SELF%NPTRLS
ENDIF
LNPTRSV = ALLOCATED (SELF%NPTRSV)
WRITE (KLUN) LNPTRSV
IF (LNPTRSV) THEN
  WRITE (KLUN) LBOUND (SELF%NPTRSV)
  WRITE (KLUN) UBOUND (SELF%NPTRSV)
  WRITE (KLUN) SELF%NPTRSV
ENDIF
LNPTRSVF = ALLOCATED (SELF%NPTRSVF)
WRITE (KLUN) LNPTRSVF
IF (LNPTRSVF) THEN
  WRITE (KLUN) LBOUND (SELF%NPTRSVF)
  WRITE (KLUN) UBOUND (SELF%NPTRSVF)
  WRITE (KLUN) SELF%NPTRSVF
ENDIF
LNPTRMF = ALLOCATED (SELF%NPTRMF)
WRITE (KLUN) LNPTRMF
IF (LNPTRMF) THEN
  WRITE (KLUN) LBOUND (SELF%NPTRMF)
  WRITE (KLUN) UBOUND (SELF%NPTRMF)
  WRITE (KLUN) SELF%NPTRMF
ENDIF
LNSPSTAF = ALLOCATED (SELF%NSPSTAF)
WRITE (KLUN) LNSPSTAF
IF (LNSPSTAF) THEN
  WRITE (KLUN) LBOUND (SELF%NSPSTAF)
  WRITE (KLUN) UBOUND (SELF%NSPSTAF)
  WRITE (KLUN) SELF%NSPSTAF
ENDIF
LNUMLL = ALLOCATED (SELF%NUMLL)
WRITE (KLUN) LNUMLL
IF (LNUMLL) THEN
  WRITE (KLUN) LBOUND (SELF%NUMLL)
  WRITE (KLUN) UBOUND (SELF%NUMLL)
  WRITE (KLUN) SELF%NUMLL
ENDIF
LNPTRLL = ALLOCATED (SELF%NPTRLL)
WRITE (KLUN) LNPTRLL
IF (LNPTRLL) THEN
  WRITE (KLUN) LBOUND (SELF%NPTRLL)
  WRITE (KLUN) UBOUND (SELF%NPTRLL)
  WRITE (KLUN) SELF%NPTRLL
ENDIF
LMYLEVS = ALLOCATED (SELF%MYLEVS)
WRITE (KLUN) LMYLEVS
IF (LMYLEVS) THEN
  WRITE (KLUN) LBOUND (SELF%MYLEVS)
  WRITE (KLUN) UBOUND (SELF%MYLEVS)
  WRITE (KLUN) SELF%MYLEVS
ENDIF
LNPSURF = ALLOCATED (SELF%NPSURF)
WRITE (KLUN) LNPSURF
IF (LNPSURF) THEN
  WRITE (KLUN) LBOUND (SELF%NPSURF)
  WRITE (KLUN) UBOUND (SELF%NPSURF)
  WRITE (KLUN) SELF%NPSURF
ENDIF
LNSTA = ALLOCATED (SELF%NSTA)
WRITE (KLUN) LNSTA
IF (LNSTA) THEN
  WRITE (KLUN) LBOUND (SELF%NSTA)
  WRITE (KLUN) UBOUND (SELF%NSTA)
  WRITE (KLUN) SELF%NSTA
ENDIF
LNONL = ALLOCATED (SELF%NONL)
WRITE (KLUN) LNONL
IF (LNONL) THEN
  WRITE (KLUN) LBOUND (SELF%NONL)
  WRITE (KLUN) UBOUND (SELF%NONL)
  WRITE (KLUN) SELF%NONL
ENDIF
LNPTRFRSTLAT = ALLOCATED (SELF%NPTRFRSTLAT)
WRITE (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  WRITE (KLUN) LBOUND (SELF%NPTRFRSTLAT)
  WRITE (KLUN) UBOUND (SELF%NPTRFRSTLAT)
  WRITE (KLUN) SELF%NPTRFRSTLAT
ENDIF
LNPTRLSTLAT = ALLOCATED (SELF%NPTRLSTLAT)
WRITE (KLUN) LNPTRLSTLAT
IF (LNPTRLSTLAT) THEN
  WRITE (KLUN) LBOUND (SELF%NPTRLSTLAT)
  WRITE (KLUN) UBOUND (SELF%NPTRLSTLAT)
  WRITE (KLUN) SELF%NPTRLSTLAT
ENDIF
LNPTRLAT = ALLOCATED (SELF%NPTRLAT)
WRITE (KLUN) LNPTRLAT
IF (LNPTRLAT) THEN
  WRITE (KLUN) LBOUND (SELF%NPTRLAT)
  WRITE (KLUN) UBOUND (SELF%NPTRLAT)
  WRITE (KLUN) SELF%NPTRLAT
ENDIF
LNFRSTLAT = ALLOCATED (SELF%NFRSTLAT)
WRITE (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  WRITE (KLUN) LBOUND (SELF%NFRSTLAT)
  WRITE (KLUN) UBOUND (SELF%NFRSTLAT)
  WRITE (KLUN) SELF%NFRSTLAT
ENDIF
LNLSTLAT = ALLOCATED (SELF%NLSTLAT)
WRITE (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  WRITE (KLUN) LBOUND (SELF%NLSTLAT)
  WRITE (KLUN) UBOUND (SELF%NLSTLAT)
  WRITE (KLUN) SELF%NLSTLAT
ENDIF
LNBSETLEV = ALLOCATED (SELF%NBSETLEV)
WRITE (KLUN) LNBSETLEV
IF (LNBSETLEV) THEN
  WRITE (KLUN) LBOUND (SELF%NBSETLEV)
  WRITE (KLUN) UBOUND (SELF%NBSETLEV)
  WRITE (KLUN) SELF%NBSETLEV
ENDIF
LNGLOBALINDEX = ALLOCATED (SELF%NGLOBALINDEX)
WRITE (KLUN) LNGLOBALINDEX
IF (LNGLOBALINDEX) THEN
  WRITE (KLUN) LBOUND (SELF%NGLOBALINDEX)
  WRITE (KLUN) UBOUND (SELF%NGLOBALINDEX)
  WRITE (KLUN) SELF%NGLOBALINDEX
ENDIF
LNGLOBALAT = ALLOCATED (SELF%NGLOBALAT)
WRITE (KLUN) LNGLOBALAT
IF (LNGLOBALAT) THEN
  WRITE (KLUN) LBOUND (SELF%NGLOBALAT)
  WRITE (KLUN) UBOUND (SELF%NGLOBALAT)
  WRITE (KLUN) SELF%NGLOBALAT
ENDIF
LNGLOBALPROC = ALLOCATED (SELF%NGLOBALPROC)
WRITE (KLUN) LNGLOBALPROC
IF (LNGLOBALPROC) THEN
  WRITE (KLUN) LBOUND (SELF%NGLOBALPROC)
  WRITE (KLUN) UBOUND (SELF%NGLOBALPROC)
  WRITE (KLUN) SELF%NGLOBALPROC
ENDIF
LNLOCALINDEX = ALLOCATED (SELF%NLOCALINDEX)
WRITE (KLUN) LNLOCALINDEX
IF (LNLOCALINDEX) THEN
  WRITE (KLUN) LBOUND (SELF%NLOCALINDEX)
  WRITE (KLUN) UBOUND (SELF%NLOCALINDEX)
  WRITE (KLUN) SELF%NLOCALINDEX
ENDIF
LNLATGPP = ALLOCATED (SELF%NLATGPP)
WRITE (KLUN) LNLATGPP
IF (LNLATGPP) THEN
  WRITE (KLUN) LBOUND (SELF%NLATGPP)
  WRITE (KLUN) UBOUND (SELF%NLATGPP)
  WRITE (KLUN) SELF%NLATGPP
ENDIF
LNLONGPP = ALLOCATED (SELF%NLONGPP)
WRITE (KLUN) LNLONGPP
IF (LNLONGPP) THEN
  WRITE (KLUN) LBOUND (SELF%NLONGPP)
  WRITE (KLUN) UBOUND (SELF%NLONGPP)
  WRITE (KLUN) SELF%NLONGPP
ENDIF
LLSPLITLAT = ALLOCATED (SELF%LSPLITLAT)
WRITE (KLUN) LLSPLITLAT
IF (LLSPLITLAT) THEN
  WRITE (KLUN) LBOUND (SELF%LSPLITLAT)
  WRITE (KLUN) UBOUND (SELF%LSPLITLAT)
  WRITE (KLUN) SELF%LSPLITLAT
ENDIF
LMYLATS = ALLOCATED (SELF%MYLATS)
WRITE (KLUN) LMYLATS
IF (LMYLATS) THEN
  WRITE (KLUN) LBOUND (SELF%MYLATS)
  WRITE (KLUN) UBOUND (SELF%MYLATS)
  WRITE (KLUN) SELF%MYLATS
ENDIF
WRITE (KLUN) SELF%NPSP
WRITE (KLUN) SELF%NSPEC2V
WRITE (KLUN) SELF%NSPEC2VF
WRITE (KLUN) SELF%NSPEC2VDDH
WRITE (KLUN) SELF%NSPEC2V_NH
WRITE (KLUN) SELF%NSPEC2V_NHX
WRITE (KLUN) SELF%NBSETSP
WRITE (KLUN) SELF%NFRSTLOFF
WRITE (KLUN) SELF%MYFRSTACTLAT
WRITE (KLUN) SELF%MYLSTACTLAT
WRITE (KLUN) SELF%NPTRFLOFF
LNPOSSP = ALLOCATED (SELF%NPOSSP)
WRITE (KLUN) LNPOSSP
IF (LNPOSSP) THEN
  WRITE (KLUN) LBOUND (SELF%NPOSSP)
  WRITE (KLUN) UBOUND (SELF%NPOSSP)
  WRITE (KLUN) SELF%NPOSSP
ENDIF
LNDIM0G = ALLOCATED (SELF%NDIM0G)
WRITE (KLUN) LNDIM0G
IF (LNDIM0G) THEN
  WRITE (KLUN) LBOUND (SELF%NDIM0G)
  WRITE (KLUN) UBOUND (SELF%NDIM0G)
  WRITE (KLUN) SELF%NDIM0G
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TMP (SELF, KLUN)

IMPLICIT NONE
TYPE (TMP), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP
READ (KLUN) LNUMPP
IF (LNUMPP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NUMPP (IL1(1):IU1(1)))
  READ (KLUN) SELF%NUMPP
ENDIF
READ (KLUN) LNPROCM
IF (LNPROCM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPROCM (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPROCM
ENDIF
READ (KLUN) LNPTRMS
IF (LNPTRMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPTRMS (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPTRMS
ENDIF
READ (KLUN) LNALLMS
IF (LNALLMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NALLMS (IL1(1):IU1(1)))
  READ (KLUN) SELF%NALLMS
ENDIF
READ (KLUN) LNPTRLS
IF (LNPTRLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPTRLS (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPTRLS
ENDIF
READ (KLUN) LNPTRSV
IF (LNPTRSV) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPTRSV (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPTRSV
ENDIF
READ (KLUN) LNPTRSVF
IF (LNPTRSVF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPTRSVF (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPTRSVF
ENDIF
READ (KLUN) LNPTRMF
IF (LNPTRMF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPTRMF (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPTRMF
ENDIF
READ (KLUN) LNSPSTAF
IF (LNSPSTAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NSPSTAF (IL1(1):IU1(1)))
  READ (KLUN) SELF%NSPSTAF
ENDIF
READ (KLUN) LNUMLL
IF (LNUMLL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NUMLL (IL1(1):IU1(1)))
  READ (KLUN) SELF%NUMLL
ENDIF
READ (KLUN) LNPTRLL
IF (LNPTRLL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPTRLL (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPTRLL
ENDIF
READ (KLUN) LMYLEVS
IF (LMYLEVS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%MYLEVS (IL1(1):IU1(1)))
  READ (KLUN) SELF%MYLEVS
ENDIF
READ (KLUN) LNPSURF
IF (LNPSURF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPSURF (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPSURF
ENDIF
READ (KLUN) LNSTA
IF (LNSTA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%NSTA (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%NSTA
ENDIF
READ (KLUN) LNONL
IF (LNONL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%NONL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%NONL
ENDIF
READ (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPTRFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPTRFRSTLAT
ENDIF
READ (KLUN) LNPTRLSTLAT
IF (LNPTRLSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPTRLSTLAT (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPTRLSTLAT
ENDIF
READ (KLUN) LNPTRLAT
IF (LNPTRLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPTRLAT (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPTRLAT
ENDIF
READ (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) SELF%NFRSTLAT
ENDIF
READ (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NLSTLAT (IL1(1):IU1(1)))
  READ (KLUN) SELF%NLSTLAT
ENDIF
READ (KLUN) LNBSETLEV
IF (LNBSETLEV) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NBSETLEV (IL1(1):IU1(1)))
  READ (KLUN) SELF%NBSETLEV
ENDIF
READ (KLUN) LNGLOBALINDEX
IF (LNGLOBALINDEX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NGLOBALINDEX (IL1(1):IU1(1)))
  READ (KLUN) SELF%NGLOBALINDEX
ENDIF
READ (KLUN) LNGLOBALAT
IF (LNGLOBALAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NGLOBALAT (IL1(1):IU1(1)))
  READ (KLUN) SELF%NGLOBALAT
ENDIF
READ (KLUN) LNGLOBALPROC
IF (LNGLOBALPROC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NGLOBALPROC (IL1(1):IU1(1)))
  READ (KLUN) SELF%NGLOBALPROC
ENDIF
READ (KLUN) LNLOCALINDEX
IF (LNLOCALINDEX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NLOCALINDEX (IL1(1):IU1(1)))
  READ (KLUN) SELF%NLOCALINDEX
ENDIF
READ (KLUN) LNLATGPP
IF (LNLATGPP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%NLATGPP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%NLATGPP
ENDIF
READ (KLUN) LNLONGPP
IF (LNLONGPP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%NLONGPP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%NLONGPP
ENDIF
READ (KLUN) LLSPLITLAT
IF (LLSPLITLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%LSPLITLAT (IL1(1):IU1(1)))
  READ (KLUN) SELF%LSPLITLAT
ENDIF
READ (KLUN) LMYLATS
IF (LMYLATS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%MYLATS (IL1(1):IU1(1)))
  READ (KLUN) SELF%MYLATS
ENDIF
READ (KLUN) SELF%NPSP
READ (KLUN) SELF%NSPEC2V
READ (KLUN) SELF%NSPEC2VF
READ (KLUN) SELF%NSPEC2VDDH
READ (KLUN) SELF%NSPEC2V_NH
READ (KLUN) SELF%NSPEC2V_NHX
READ (KLUN) SELF%NBSETSP
READ (KLUN) SELF%NFRSTLOFF
READ (KLUN) SELF%MYFRSTACTLAT
READ (KLUN) SELF%MYLSTACTLAT
READ (KLUN) SELF%NPTRFLOFF
READ (KLUN) LNPOSSP
IF (LNPOSSP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPOSSP (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPOSSP
ENDIF
READ (KLUN) LNDIM0G
IF (LNDIM0G) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NDIM0G (IL1(1):IU1(1)))
  READ (KLUN) SELF%NDIM0G
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TMP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TMP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LNUMPP = ALLOCATED (SELF%NUMPP)
IF (LNUMPP) THEN
  !$ACC ENTER DATA CREATE (SELF%NUMPP)
  !$ACC UPDATE DEVICE (SELF%NUMPP)
  !$ACC ENTER DATA ATTACH (SELF%NUMPP)
ENDIF

LNPROCM = ALLOCATED (SELF%NPROCM)
IF (LNPROCM) THEN
  !$ACC ENTER DATA CREATE (SELF%NPROCM)
  !$ACC UPDATE DEVICE (SELF%NPROCM)
  !$ACC ENTER DATA ATTACH (SELF%NPROCM)
ENDIF

LNPTRMS = ALLOCATED (SELF%NPTRMS)
IF (LNPTRMS) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRMS)
  !$ACC UPDATE DEVICE (SELF%NPTRMS)
  !$ACC ENTER DATA ATTACH (SELF%NPTRMS)
ENDIF

LNALLMS = ALLOCATED (SELF%NALLMS)
IF (LNALLMS) THEN
  !$ACC ENTER DATA CREATE (SELF%NALLMS)
  !$ACC UPDATE DEVICE (SELF%NALLMS)
  !$ACC ENTER DATA ATTACH (SELF%NALLMS)
ENDIF

LNPTRLS = ALLOCATED (SELF%NPTRLS)
IF (LNPTRLS) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRLS)
  !$ACC UPDATE DEVICE (SELF%NPTRLS)
  !$ACC ENTER DATA ATTACH (SELF%NPTRLS)
ENDIF

LNPTRSV = ALLOCATED (SELF%NPTRSV)
IF (LNPTRSV) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRSV)
  !$ACC UPDATE DEVICE (SELF%NPTRSV)
  !$ACC ENTER DATA ATTACH (SELF%NPTRSV)
ENDIF

LNPTRSVF = ALLOCATED (SELF%NPTRSVF)
IF (LNPTRSVF) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRSVF)
  !$ACC UPDATE DEVICE (SELF%NPTRSVF)
  !$ACC ENTER DATA ATTACH (SELF%NPTRSVF)
ENDIF

LNPTRMF = ALLOCATED (SELF%NPTRMF)
IF (LNPTRMF) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRMF)
  !$ACC UPDATE DEVICE (SELF%NPTRMF)
  !$ACC ENTER DATA ATTACH (SELF%NPTRMF)
ENDIF

LNSPSTAF = ALLOCATED (SELF%NSPSTAF)
IF (LNSPSTAF) THEN
  !$ACC ENTER DATA CREATE (SELF%NSPSTAF)
  !$ACC UPDATE DEVICE (SELF%NSPSTAF)
  !$ACC ENTER DATA ATTACH (SELF%NSPSTAF)
ENDIF

LNUMLL = ALLOCATED (SELF%NUMLL)
IF (LNUMLL) THEN
  !$ACC ENTER DATA CREATE (SELF%NUMLL)
  !$ACC UPDATE DEVICE (SELF%NUMLL)
  !$ACC ENTER DATA ATTACH (SELF%NUMLL)
ENDIF

LNPTRLL = ALLOCATED (SELF%NPTRLL)
IF (LNPTRLL) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRLL)
  !$ACC UPDATE DEVICE (SELF%NPTRLL)
  !$ACC ENTER DATA ATTACH (SELF%NPTRLL)
ENDIF

LMYLEVS = ALLOCATED (SELF%MYLEVS)
IF (LMYLEVS) THEN
  !$ACC ENTER DATA CREATE (SELF%MYLEVS)
  !$ACC UPDATE DEVICE (SELF%MYLEVS)
  !$ACC ENTER DATA ATTACH (SELF%MYLEVS)
ENDIF

LNPSURF = ALLOCATED (SELF%NPSURF)
IF (LNPSURF) THEN
  !$ACC ENTER DATA CREATE (SELF%NPSURF)
  !$ACC UPDATE DEVICE (SELF%NPSURF)
  !$ACC ENTER DATA ATTACH (SELF%NPSURF)
ENDIF

LNSTA = ALLOCATED (SELF%NSTA)
IF (LNSTA) THEN
  !$ACC ENTER DATA CREATE (SELF%NSTA)
  !$ACC UPDATE DEVICE (SELF%NSTA)
  !$ACC ENTER DATA ATTACH (SELF%NSTA)
ENDIF

LNONL = ALLOCATED (SELF%NONL)
IF (LNONL) THEN
  !$ACC ENTER DATA CREATE (SELF%NONL)
  !$ACC UPDATE DEVICE (SELF%NONL)
  !$ACC ENTER DATA ATTACH (SELF%NONL)
ENDIF

LNPTRFRSTLAT = ALLOCATED (SELF%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRFRSTLAT)
  !$ACC UPDATE DEVICE (SELF%NPTRFRSTLAT)
  !$ACC ENTER DATA ATTACH (SELF%NPTRFRSTLAT)
ENDIF

LNPTRLSTLAT = ALLOCATED (SELF%NPTRLSTLAT)
IF (LNPTRLSTLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRLSTLAT)
  !$ACC UPDATE DEVICE (SELF%NPTRLSTLAT)
  !$ACC ENTER DATA ATTACH (SELF%NPTRLSTLAT)
ENDIF

LNPTRLAT = ALLOCATED (SELF%NPTRLAT)
IF (LNPTRLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRLAT)
  !$ACC UPDATE DEVICE (SELF%NPTRLAT)
  !$ACC ENTER DATA ATTACH (SELF%NPTRLAT)
ENDIF

LNFRSTLAT = ALLOCATED (SELF%NFRSTLAT)
IF (LNFRSTLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NFRSTLAT)
  !$ACC UPDATE DEVICE (SELF%NFRSTLAT)
  !$ACC ENTER DATA ATTACH (SELF%NFRSTLAT)
ENDIF

LNLSTLAT = ALLOCATED (SELF%NLSTLAT)
IF (LNLSTLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NLSTLAT)
  !$ACC UPDATE DEVICE (SELF%NLSTLAT)
  !$ACC ENTER DATA ATTACH (SELF%NLSTLAT)
ENDIF

LNBSETLEV = ALLOCATED (SELF%NBSETLEV)
IF (LNBSETLEV) THEN
  !$ACC ENTER DATA CREATE (SELF%NBSETLEV)
  !$ACC UPDATE DEVICE (SELF%NBSETLEV)
  !$ACC ENTER DATA ATTACH (SELF%NBSETLEV)
ENDIF

LNGLOBALINDEX = ALLOCATED (SELF%NGLOBALINDEX)
IF (LNGLOBALINDEX) THEN
  !$ACC ENTER DATA CREATE (SELF%NGLOBALINDEX)
  !$ACC UPDATE DEVICE (SELF%NGLOBALINDEX)
  !$ACC ENTER DATA ATTACH (SELF%NGLOBALINDEX)
ENDIF

LNGLOBALAT = ALLOCATED (SELF%NGLOBALAT)
IF (LNGLOBALAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NGLOBALAT)
  !$ACC UPDATE DEVICE (SELF%NGLOBALAT)
  !$ACC ENTER DATA ATTACH (SELF%NGLOBALAT)
ENDIF

LNGLOBALPROC = ALLOCATED (SELF%NGLOBALPROC)
IF (LNGLOBALPROC) THEN
  !$ACC ENTER DATA CREATE (SELF%NGLOBALPROC)
  !$ACC UPDATE DEVICE (SELF%NGLOBALPROC)
  !$ACC ENTER DATA ATTACH (SELF%NGLOBALPROC)
ENDIF

LNLOCALINDEX = ALLOCATED (SELF%NLOCALINDEX)
IF (LNLOCALINDEX) THEN
  !$ACC ENTER DATA CREATE (SELF%NLOCALINDEX)
  !$ACC UPDATE DEVICE (SELF%NLOCALINDEX)
  !$ACC ENTER DATA ATTACH (SELF%NLOCALINDEX)
ENDIF

LNLATGPP = ALLOCATED (SELF%NLATGPP)
IF (LNLATGPP) THEN
  !$ACC ENTER DATA CREATE (SELF%NLATGPP)
  !$ACC UPDATE DEVICE (SELF%NLATGPP)
  !$ACC ENTER DATA ATTACH (SELF%NLATGPP)
ENDIF

LNLONGPP = ALLOCATED (SELF%NLONGPP)
IF (LNLONGPP) THEN
  !$ACC ENTER DATA CREATE (SELF%NLONGPP)
  !$ACC UPDATE DEVICE (SELF%NLONGPP)
  !$ACC ENTER DATA ATTACH (SELF%NLONGPP)
ENDIF

LLSPLITLAT = ALLOCATED (SELF%LSPLITLAT)
IF (LLSPLITLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%LSPLITLAT)
  !$ACC UPDATE DEVICE (SELF%LSPLITLAT)
  !$ACC ENTER DATA ATTACH (SELF%LSPLITLAT)
ENDIF

LMYLATS = ALLOCATED (SELF%MYLATS)
IF (LMYLATS) THEN
  !$ACC ENTER DATA CREATE (SELF%MYLATS)
  !$ACC UPDATE DEVICE (SELF%MYLATS)
  !$ACC ENTER DATA ATTACH (SELF%MYLATS)
ENDIF

LNPOSSP = ALLOCATED (SELF%NPOSSP)
IF (LNPOSSP) THEN
  !$ACC ENTER DATA CREATE (SELF%NPOSSP)
  !$ACC UPDATE DEVICE (SELF%NPOSSP)
  !$ACC ENTER DATA ATTACH (SELF%NPOSSP)
ENDIF

LNDIM0G = ALLOCATED (SELF%NDIM0G)
IF (LNDIM0G) THEN
  !$ACC ENTER DATA CREATE (SELF%NDIM0G)
  !$ACC UPDATE DEVICE (SELF%NDIM0G)
  !$ACC ENTER DATA ATTACH (SELF%NDIM0G)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TMP (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TMP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LNUMPP = ALLOCATED (SELF%NUMPP)
IF (LNUMPP) THEN
  !$ACC EXIT DATA DETACH (SELF%NUMPP)
  !$ACC EXIT DATA DETACH (SELF%NUMPP)
ENDIF

LNPROCM = ALLOCATED (SELF%NPROCM)
IF (LNPROCM) THEN
  !$ACC EXIT DATA DETACH (SELF%NPROCM)
  !$ACC EXIT DATA DETACH (SELF%NPROCM)
ENDIF

LNPTRMS = ALLOCATED (SELF%NPTRMS)
IF (LNPTRMS) THEN
  !$ACC EXIT DATA DETACH (SELF%NPTRMS)
  !$ACC EXIT DATA DETACH (SELF%NPTRMS)
ENDIF

LNALLMS = ALLOCATED (SELF%NALLMS)
IF (LNALLMS) THEN
  !$ACC EXIT DATA DETACH (SELF%NALLMS)
  !$ACC EXIT DATA DETACH (SELF%NALLMS)
ENDIF

LNPTRLS = ALLOCATED (SELF%NPTRLS)
IF (LNPTRLS) THEN
  !$ACC EXIT DATA DETACH (SELF%NPTRLS)
  !$ACC EXIT DATA DETACH (SELF%NPTRLS)
ENDIF

LNPTRSV = ALLOCATED (SELF%NPTRSV)
IF (LNPTRSV) THEN
  !$ACC EXIT DATA DETACH (SELF%NPTRSV)
  !$ACC EXIT DATA DETACH (SELF%NPTRSV)
ENDIF

LNPTRSVF = ALLOCATED (SELF%NPTRSVF)
IF (LNPTRSVF) THEN
  !$ACC EXIT DATA DETACH (SELF%NPTRSVF)
  !$ACC EXIT DATA DETACH (SELF%NPTRSVF)
ENDIF

LNPTRMF = ALLOCATED (SELF%NPTRMF)
IF (LNPTRMF) THEN
  !$ACC EXIT DATA DETACH (SELF%NPTRMF)
  !$ACC EXIT DATA DETACH (SELF%NPTRMF)
ENDIF

LNSPSTAF = ALLOCATED (SELF%NSPSTAF)
IF (LNSPSTAF) THEN
  !$ACC EXIT DATA DETACH (SELF%NSPSTAF)
  !$ACC EXIT DATA DETACH (SELF%NSPSTAF)
ENDIF

LNUMLL = ALLOCATED (SELF%NUMLL)
IF (LNUMLL) THEN
  !$ACC EXIT DATA DETACH (SELF%NUMLL)
  !$ACC EXIT DATA DETACH (SELF%NUMLL)
ENDIF

LNPTRLL = ALLOCATED (SELF%NPTRLL)
IF (LNPTRLL) THEN
  !$ACC EXIT DATA DETACH (SELF%NPTRLL)
  !$ACC EXIT DATA DETACH (SELF%NPTRLL)
ENDIF

LMYLEVS = ALLOCATED (SELF%MYLEVS)
IF (LMYLEVS) THEN
  !$ACC EXIT DATA DETACH (SELF%MYLEVS)
  !$ACC EXIT DATA DETACH (SELF%MYLEVS)
ENDIF

LNPSURF = ALLOCATED (SELF%NPSURF)
IF (LNPSURF) THEN
  !$ACC EXIT DATA DETACH (SELF%NPSURF)
  !$ACC EXIT DATA DETACH (SELF%NPSURF)
ENDIF

LNSTA = ALLOCATED (SELF%NSTA)
IF (LNSTA) THEN
  !$ACC EXIT DATA DETACH (SELF%NSTA)
  !$ACC EXIT DATA DETACH (SELF%NSTA)
ENDIF

LNONL = ALLOCATED (SELF%NONL)
IF (LNONL) THEN
  !$ACC EXIT DATA DETACH (SELF%NONL)
  !$ACC EXIT DATA DETACH (SELF%NONL)
ENDIF

LNPTRFRSTLAT = ALLOCATED (SELF%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  !$ACC EXIT DATA DETACH (SELF%NPTRFRSTLAT)
  !$ACC EXIT DATA DETACH (SELF%NPTRFRSTLAT)
ENDIF

LNPTRLSTLAT = ALLOCATED (SELF%NPTRLSTLAT)
IF (LNPTRLSTLAT) THEN
  !$ACC EXIT DATA DETACH (SELF%NPTRLSTLAT)
  !$ACC EXIT DATA DETACH (SELF%NPTRLSTLAT)
ENDIF

LNPTRLAT = ALLOCATED (SELF%NPTRLAT)
IF (LNPTRLAT) THEN
  !$ACC EXIT DATA DETACH (SELF%NPTRLAT)
  !$ACC EXIT DATA DETACH (SELF%NPTRLAT)
ENDIF

LNFRSTLAT = ALLOCATED (SELF%NFRSTLAT)
IF (LNFRSTLAT) THEN
  !$ACC EXIT DATA DETACH (SELF%NFRSTLAT)
  !$ACC EXIT DATA DETACH (SELF%NFRSTLAT)
ENDIF

LNLSTLAT = ALLOCATED (SELF%NLSTLAT)
IF (LNLSTLAT) THEN
  !$ACC EXIT DATA DETACH (SELF%NLSTLAT)
  !$ACC EXIT DATA DETACH (SELF%NLSTLAT)
ENDIF

LNBSETLEV = ALLOCATED (SELF%NBSETLEV)
IF (LNBSETLEV) THEN
  !$ACC EXIT DATA DETACH (SELF%NBSETLEV)
  !$ACC EXIT DATA DETACH (SELF%NBSETLEV)
ENDIF

LNGLOBALINDEX = ALLOCATED (SELF%NGLOBALINDEX)
IF (LNGLOBALINDEX) THEN
  !$ACC EXIT DATA DETACH (SELF%NGLOBALINDEX)
  !$ACC EXIT DATA DETACH (SELF%NGLOBALINDEX)
ENDIF

LNGLOBALAT = ALLOCATED (SELF%NGLOBALAT)
IF (LNGLOBALAT) THEN
  !$ACC EXIT DATA DETACH (SELF%NGLOBALAT)
  !$ACC EXIT DATA DETACH (SELF%NGLOBALAT)
ENDIF

LNGLOBALPROC = ALLOCATED (SELF%NGLOBALPROC)
IF (LNGLOBALPROC) THEN
  !$ACC EXIT DATA DETACH (SELF%NGLOBALPROC)
  !$ACC EXIT DATA DETACH (SELF%NGLOBALPROC)
ENDIF

LNLOCALINDEX = ALLOCATED (SELF%NLOCALINDEX)
IF (LNLOCALINDEX) THEN
  !$ACC EXIT DATA DETACH (SELF%NLOCALINDEX)
  !$ACC EXIT DATA DETACH (SELF%NLOCALINDEX)
ENDIF

LNLATGPP = ALLOCATED (SELF%NLATGPP)
IF (LNLATGPP) THEN
  !$ACC EXIT DATA DETACH (SELF%NLATGPP)
  !$ACC EXIT DATA DETACH (SELF%NLATGPP)
ENDIF

LNLONGPP = ALLOCATED (SELF%NLONGPP)
IF (LNLONGPP) THEN
  !$ACC EXIT DATA DETACH (SELF%NLONGPP)
  !$ACC EXIT DATA DETACH (SELF%NLONGPP)
ENDIF

LLSPLITLAT = ALLOCATED (SELF%LSPLITLAT)
IF (LLSPLITLAT) THEN
  !$ACC EXIT DATA DETACH (SELF%LSPLITLAT)
  !$ACC EXIT DATA DETACH (SELF%LSPLITLAT)
ENDIF

LMYLATS = ALLOCATED (SELF%MYLATS)
IF (LMYLATS) THEN
  !$ACC EXIT DATA DETACH (SELF%MYLATS)
  !$ACC EXIT DATA DETACH (SELF%MYLATS)
ENDIF

LNPOSSP = ALLOCATED (SELF%NPOSSP)
IF (LNPOSSP) THEN
  !$ACC EXIT DATA DETACH (SELF%NPOSSP)
  !$ACC EXIT DATA DETACH (SELF%NPOSSP)
ENDIF

LNDIM0G = ALLOCATED (SELF%NDIM0G)
IF (LNDIM0G) THEN
  !$ACC EXIT DATA DETACH (SELF%NDIM0G)
  !$ACC EXIT DATA DETACH (SELF%NDIM0G)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
