MODULE UTIL_TLEP_MOD

USE YEMLAP, ONLY : TLEP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TLEP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLEP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TLEP
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TLEP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TLEP (SELF, KLUN)

IMPLICIT NONE
TYPE (TLEP), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LMVALUE, LNCPL2M, LNCPL2N, LNCPL4M, LNCPL4N, LNCPLM, LNCPLN, LNESM0, LNESM0G, LNESPZERO
LOGICAL :: LNPME, LNPNE, LRLEPDIM, LRLEPDIN, LRLEPINM, LRLEPINN
LNCPL2M = ALLOCATED (SELF%NCPL2M)
WRITE (KLUN) LNCPL2M
IF (LNCPL2M) THEN
  WRITE (KLUN) LBOUND (SELF%NCPL2M)
  WRITE (KLUN) UBOUND (SELF%NCPL2M)
  WRITE (KLUN) SELF%NCPL2M
ENDIF
LNCPL4M = ALLOCATED (SELF%NCPL4M)
WRITE (KLUN) LNCPL4M
IF (LNCPL4M) THEN
  WRITE (KLUN) LBOUND (SELF%NCPL4M)
  WRITE (KLUN) UBOUND (SELF%NCPL4M)
  WRITE (KLUN) SELF%NCPL4M
ENDIF
LNCPLM = ALLOCATED (SELF%NCPLM)
WRITE (KLUN) LNCPLM
IF (LNCPLM) THEN
  WRITE (KLUN) LBOUND (SELF%NCPLM)
  WRITE (KLUN) UBOUND (SELF%NCPLM)
  WRITE (KLUN) SELF%NCPLM
ENDIF
LNCPL2N = ALLOCATED (SELF%NCPL2N)
WRITE (KLUN) LNCPL2N
IF (LNCPL2N) THEN
  WRITE (KLUN) LBOUND (SELF%NCPL2N)
  WRITE (KLUN) UBOUND (SELF%NCPL2N)
  WRITE (KLUN) SELF%NCPL2N
ENDIF
LNCPL4N = ALLOCATED (SELF%NCPL4N)
WRITE (KLUN) LNCPL4N
IF (LNCPL4N) THEN
  WRITE (KLUN) LBOUND (SELF%NCPL4N)
  WRITE (KLUN) UBOUND (SELF%NCPL4N)
  WRITE (KLUN) SELF%NCPL4N
ENDIF
LNCPLN = ALLOCATED (SELF%NCPLN)
WRITE (KLUN) LNCPLN
IF (LNCPLN) THEN
  WRITE (KLUN) LBOUND (SELF%NCPLN)
  WRITE (KLUN) UBOUND (SELF%NCPLN)
  WRITE (KLUN) SELF%NCPLN
ENDIF
LRLEPDIN = ALLOCATED (SELF%RLEPDIN)
WRITE (KLUN) LRLEPDIN
IF (LRLEPDIN) THEN
  WRITE (KLUN) LBOUND (SELF%RLEPDIN)
  WRITE (KLUN) UBOUND (SELF%RLEPDIN)
  WRITE (KLUN) SELF%RLEPDIN
ENDIF
LRLEPINN = ALLOCATED (SELF%RLEPINN)
WRITE (KLUN) LRLEPINN
IF (LRLEPINN) THEN
  WRITE (KLUN) LBOUND (SELF%RLEPINN)
  WRITE (KLUN) UBOUND (SELF%RLEPINN)
  WRITE (KLUN) SELF%RLEPINN
ENDIF
LRLEPDIM = ALLOCATED (SELF%RLEPDIM)
WRITE (KLUN) LRLEPDIM
IF (LRLEPDIM) THEN
  WRITE (KLUN) LBOUND (SELF%RLEPDIM)
  WRITE (KLUN) UBOUND (SELF%RLEPDIM)
  WRITE (KLUN) SELF%RLEPDIM
ENDIF
LRLEPINM = ALLOCATED (SELF%RLEPINM)
WRITE (KLUN) LRLEPINM
IF (LRLEPINM) THEN
  WRITE (KLUN) LBOUND (SELF%RLEPINM)
  WRITE (KLUN) UBOUND (SELF%RLEPINM)
  WRITE (KLUN) SELF%RLEPINM
ENDIF
LNESM0 = ALLOCATED (SELF%NESM0)
WRITE (KLUN) LNESM0
IF (LNESM0) THEN
  WRITE (KLUN) LBOUND (SELF%NESM0)
  WRITE (KLUN) UBOUND (SELF%NESM0)
  WRITE (KLUN) SELF%NESM0
ENDIF
LNESPZERO = ALLOCATED (SELF%NESPZERO)
WRITE (KLUN) LNESPZERO
IF (LNESPZERO) THEN
  WRITE (KLUN) LBOUND (SELF%NESPZERO)
  WRITE (KLUN) UBOUND (SELF%NESPZERO)
  WRITE (KLUN) SELF%NESPZERO
ENDIF
LNESM0G = ALLOCATED (SELF%NESM0G)
WRITE (KLUN) LNESM0G
IF (LNESM0G) THEN
  WRITE (KLUN) LBOUND (SELF%NESM0G)
  WRITE (KLUN) UBOUND (SELF%NESM0G)
  WRITE (KLUN) SELF%NESM0G
ENDIF
LNPME = ALLOCATED (SELF%NPME)
WRITE (KLUN) LNPME
IF (LNPME) THEN
  WRITE (KLUN) LBOUND (SELF%NPME)
  WRITE (KLUN) UBOUND (SELF%NPME)
  WRITE (KLUN) SELF%NPME
ENDIF
LNPNE = ALLOCATED (SELF%NPNE)
WRITE (KLUN) LNPNE
IF (LNPNE) THEN
  WRITE (KLUN) LBOUND (SELF%NPNE)
  WRITE (KLUN) UBOUND (SELF%NPNE)
  WRITE (KLUN) SELF%NPNE
ENDIF
LMVALUE = ALLOCATED (SELF%MVALUE)
WRITE (KLUN) LMVALUE
IF (LMVALUE) THEN
  WRITE (KLUN) LBOUND (SELF%MVALUE)
  WRITE (KLUN) UBOUND (SELF%MVALUE)
  WRITE (KLUN) SELF%MVALUE
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TLEP (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TLEP), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LMVALUE, LNCPL2M, LNCPL2N, LNCPL4M, LNCPL4N, LNCPLM, LNCPLN, LNESM0, LNESM0G, LNESPZERO
LOGICAL :: LNPME, LNPNE, LRLEPDIM, LRLEPDIN, LRLEPINM, LRLEPINN
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
READ (KLUN) LNCPL2M
IF (LNCPL2M) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NCPL2M (IL1(1):IU1(1)))
  READ (KLUN) SELF%NCPL2M
ENDIF
READ (KLUN) LNCPL4M
IF (LNCPL4M) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NCPL4M (IL1(1):IU1(1)))
  READ (KLUN) SELF%NCPL4M
ENDIF
READ (KLUN) LNCPLM
IF (LNCPLM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NCPLM (IL1(1):IU1(1)))
  READ (KLUN) SELF%NCPLM
ENDIF
READ (KLUN) LNCPL2N
IF (LNCPL2N) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NCPL2N (IL1(1):IU1(1)))
  READ (KLUN) SELF%NCPL2N
ENDIF
READ (KLUN) LNCPL4N
IF (LNCPL4N) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NCPL4N (IL1(1):IU1(1)))
  READ (KLUN) SELF%NCPL4N
ENDIF
READ (KLUN) LNCPLN
IF (LNCPLN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NCPLN (IL1(1):IU1(1)))
  READ (KLUN) SELF%NCPLN
ENDIF
READ (KLUN) LRLEPDIN
IF (LRLEPDIN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RLEPDIN (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RLEPDIN,1):UBOUND(SELF%RLEPDIN,1)))
  READ (KLUN) ZTMP1
  SELF%RLEPDIN = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLEPINN
IF (LRLEPINN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RLEPINN (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RLEPINN,1):UBOUND(SELF%RLEPINN,1)))
  READ (KLUN) ZTMP1
  SELF%RLEPINN = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLEPDIM
IF (LRLEPDIM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RLEPDIM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RLEPDIM,1):UBOUND(SELF%RLEPDIM,1)))
  READ (KLUN) ZTMP1
  SELF%RLEPDIM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLEPINM
IF (LRLEPINM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RLEPINM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RLEPINM,1):UBOUND(SELF%RLEPINM,1)))
  READ (KLUN) ZTMP1
  SELF%RLEPINM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LNESM0
IF (LNESM0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NESM0 (IL1(1):IU1(1)))
  READ (KLUN) SELF%NESM0
ENDIF
READ (KLUN) LNESPZERO
IF (LNESPZERO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NESPZERO (IL1(1):IU1(1)))
  READ (KLUN) SELF%NESPZERO
ENDIF
READ (KLUN) LNESM0G
IF (LNESM0G) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NESM0G (IL1(1):IU1(1)))
  READ (KLUN) SELF%NESM0G
ENDIF
READ (KLUN) LNPME
IF (LNPME) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPME (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPME
ENDIF
READ (KLUN) LNPNE
IF (LNPNE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPNE (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPNE
ENDIF
READ (KLUN) LMVALUE
IF (LMVALUE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%MVALUE (IL1(1):IU1(1)))
  READ (KLUN) SELF%MVALUE
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TLEP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TLEP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LMVALUE, LNCPL2M, LNCPL2N, LNCPL4M, LNCPL4N, LNCPLM, LNCPLN, LNESM0, LNESM0G, LNESPZERO
LOGICAL :: LNPME, LNPNE, LRLEPDIM, LRLEPDIN, LRLEPINM, LRLEPINN

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LNCPL2M = ALLOCATED (SELF%NCPL2M)
IF (LNCPL2M) THEN
  !$ACC ENTER DATA CREATE (SELF%NCPL2M)
  !$ACC UPDATE DEVICE (SELF%NCPL2M)
  !$ACC ENTER DATA ATTACH (SELF%NCPL2M)
ENDIF

LNCPL4M = ALLOCATED (SELF%NCPL4M)
IF (LNCPL4M) THEN
  !$ACC ENTER DATA CREATE (SELF%NCPL4M)
  !$ACC UPDATE DEVICE (SELF%NCPL4M)
  !$ACC ENTER DATA ATTACH (SELF%NCPL4M)
ENDIF

LNCPLM = ALLOCATED (SELF%NCPLM)
IF (LNCPLM) THEN
  !$ACC ENTER DATA CREATE (SELF%NCPLM)
  !$ACC UPDATE DEVICE (SELF%NCPLM)
  !$ACC ENTER DATA ATTACH (SELF%NCPLM)
ENDIF

LNCPL2N = ALLOCATED (SELF%NCPL2N)
IF (LNCPL2N) THEN
  !$ACC ENTER DATA CREATE (SELF%NCPL2N)
  !$ACC UPDATE DEVICE (SELF%NCPL2N)
  !$ACC ENTER DATA ATTACH (SELF%NCPL2N)
ENDIF

LNCPL4N = ALLOCATED (SELF%NCPL4N)
IF (LNCPL4N) THEN
  !$ACC ENTER DATA CREATE (SELF%NCPL4N)
  !$ACC UPDATE DEVICE (SELF%NCPL4N)
  !$ACC ENTER DATA ATTACH (SELF%NCPL4N)
ENDIF

LNCPLN = ALLOCATED (SELF%NCPLN)
IF (LNCPLN) THEN
  !$ACC ENTER DATA CREATE (SELF%NCPLN)
  !$ACC UPDATE DEVICE (SELF%NCPLN)
  !$ACC ENTER DATA ATTACH (SELF%NCPLN)
ENDIF

LRLEPDIN = ALLOCATED (SELF%RLEPDIN)
IF (LRLEPDIN) THEN
  !$ACC ENTER DATA CREATE (SELF%RLEPDIN)
  !$ACC UPDATE DEVICE (SELF%RLEPDIN)
  !$ACC ENTER DATA ATTACH (SELF%RLEPDIN)
ENDIF

LRLEPINN = ALLOCATED (SELF%RLEPINN)
IF (LRLEPINN) THEN
  !$ACC ENTER DATA CREATE (SELF%RLEPINN)
  !$ACC UPDATE DEVICE (SELF%RLEPINN)
  !$ACC ENTER DATA ATTACH (SELF%RLEPINN)
ENDIF

LRLEPDIM = ALLOCATED (SELF%RLEPDIM)
IF (LRLEPDIM) THEN
  !$ACC ENTER DATA CREATE (SELF%RLEPDIM)
  !$ACC UPDATE DEVICE (SELF%RLEPDIM)
  !$ACC ENTER DATA ATTACH (SELF%RLEPDIM)
ENDIF

LRLEPINM = ALLOCATED (SELF%RLEPINM)
IF (LRLEPINM) THEN
  !$ACC ENTER DATA CREATE (SELF%RLEPINM)
  !$ACC UPDATE DEVICE (SELF%RLEPINM)
  !$ACC ENTER DATA ATTACH (SELF%RLEPINM)
ENDIF

LNESM0 = ALLOCATED (SELF%NESM0)
IF (LNESM0) THEN
  !$ACC ENTER DATA CREATE (SELF%NESM0)
  !$ACC UPDATE DEVICE (SELF%NESM0)
  !$ACC ENTER DATA ATTACH (SELF%NESM0)
ENDIF

LNESPZERO = ALLOCATED (SELF%NESPZERO)
IF (LNESPZERO) THEN
  !$ACC ENTER DATA CREATE (SELF%NESPZERO)
  !$ACC UPDATE DEVICE (SELF%NESPZERO)
  !$ACC ENTER DATA ATTACH (SELF%NESPZERO)
ENDIF

LNESM0G = ALLOCATED (SELF%NESM0G)
IF (LNESM0G) THEN
  !$ACC ENTER DATA CREATE (SELF%NESM0G)
  !$ACC UPDATE DEVICE (SELF%NESM0G)
  !$ACC ENTER DATA ATTACH (SELF%NESM0G)
ENDIF

LNPME = ALLOCATED (SELF%NPME)
IF (LNPME) THEN
  !$ACC ENTER DATA CREATE (SELF%NPME)
  !$ACC UPDATE DEVICE (SELF%NPME)
  !$ACC ENTER DATA ATTACH (SELF%NPME)
ENDIF

LNPNE = ALLOCATED (SELF%NPNE)
IF (LNPNE) THEN
  !$ACC ENTER DATA CREATE (SELF%NPNE)
  !$ACC UPDATE DEVICE (SELF%NPNE)
  !$ACC ENTER DATA ATTACH (SELF%NPNE)
ENDIF

LMVALUE = ALLOCATED (SELF%MVALUE)
IF (LMVALUE) THEN
  !$ACC ENTER DATA CREATE (SELF%MVALUE)
  !$ACC UPDATE DEVICE (SELF%MVALUE)
  !$ACC ENTER DATA ATTACH (SELF%MVALUE)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TLEP (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TLEP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LMVALUE, LNCPL2M, LNCPL2N, LNCPL4M, LNCPL4N, LNCPLM, LNCPLN, LNESM0, LNESM0G, LNESPZERO
LOGICAL :: LNPME, LNPNE, LRLEPDIM, LRLEPDIN, LRLEPINM, LRLEPINN

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LNCPL2M = ALLOCATED (SELF%NCPL2M)
IF (LNCPL2M) THEN
  !$ACC EXIT DATA DETACH (SELF%NCPL2M)
  !$ACC EXIT DATA DETACH (SELF%NCPL2M)
ENDIF

LNCPL4M = ALLOCATED (SELF%NCPL4M)
IF (LNCPL4M) THEN
  !$ACC EXIT DATA DETACH (SELF%NCPL4M)
  !$ACC EXIT DATA DETACH (SELF%NCPL4M)
ENDIF

LNCPLM = ALLOCATED (SELF%NCPLM)
IF (LNCPLM) THEN
  !$ACC EXIT DATA DETACH (SELF%NCPLM)
  !$ACC EXIT DATA DETACH (SELF%NCPLM)
ENDIF

LNCPL2N = ALLOCATED (SELF%NCPL2N)
IF (LNCPL2N) THEN
  !$ACC EXIT DATA DETACH (SELF%NCPL2N)
  !$ACC EXIT DATA DETACH (SELF%NCPL2N)
ENDIF

LNCPL4N = ALLOCATED (SELF%NCPL4N)
IF (LNCPL4N) THEN
  !$ACC EXIT DATA DETACH (SELF%NCPL4N)
  !$ACC EXIT DATA DETACH (SELF%NCPL4N)
ENDIF

LNCPLN = ALLOCATED (SELF%NCPLN)
IF (LNCPLN) THEN
  !$ACC EXIT DATA DETACH (SELF%NCPLN)
  !$ACC EXIT DATA DETACH (SELF%NCPLN)
ENDIF

LRLEPDIN = ALLOCATED (SELF%RLEPDIN)
IF (LRLEPDIN) THEN
  !$ACC EXIT DATA DETACH (SELF%RLEPDIN)
  !$ACC EXIT DATA DETACH (SELF%RLEPDIN)
ENDIF

LRLEPINN = ALLOCATED (SELF%RLEPINN)
IF (LRLEPINN) THEN
  !$ACC EXIT DATA DETACH (SELF%RLEPINN)
  !$ACC EXIT DATA DETACH (SELF%RLEPINN)
ENDIF

LRLEPDIM = ALLOCATED (SELF%RLEPDIM)
IF (LRLEPDIM) THEN
  !$ACC EXIT DATA DETACH (SELF%RLEPDIM)
  !$ACC EXIT DATA DETACH (SELF%RLEPDIM)
ENDIF

LRLEPINM = ALLOCATED (SELF%RLEPINM)
IF (LRLEPINM) THEN
  !$ACC EXIT DATA DETACH (SELF%RLEPINM)
  !$ACC EXIT DATA DETACH (SELF%RLEPINM)
ENDIF

LNESM0 = ALLOCATED (SELF%NESM0)
IF (LNESM0) THEN
  !$ACC EXIT DATA DETACH (SELF%NESM0)
  !$ACC EXIT DATA DETACH (SELF%NESM0)
ENDIF

LNESPZERO = ALLOCATED (SELF%NESPZERO)
IF (LNESPZERO) THEN
  !$ACC EXIT DATA DETACH (SELF%NESPZERO)
  !$ACC EXIT DATA DETACH (SELF%NESPZERO)
ENDIF

LNESM0G = ALLOCATED (SELF%NESM0G)
IF (LNESM0G) THEN
  !$ACC EXIT DATA DETACH (SELF%NESM0G)
  !$ACC EXIT DATA DETACH (SELF%NESM0G)
ENDIF

LNPME = ALLOCATED (SELF%NPME)
IF (LNPME) THEN
  !$ACC EXIT DATA DETACH (SELF%NPME)
  !$ACC EXIT DATA DETACH (SELF%NPME)
ENDIF

LNPNE = ALLOCATED (SELF%NPNE)
IF (LNPNE) THEN
  !$ACC EXIT DATA DETACH (SELF%NPNE)
  !$ACC EXIT DATA DETACH (SELF%NPNE)
ENDIF

LMVALUE = ALLOCATED (SELF%MVALUE)
IF (LMVALUE) THEN
  !$ACC EXIT DATA DETACH (SELF%MVALUE)
  !$ACC EXIT DATA DETACH (SELF%MVALUE)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
