MODULE UTIL_TRCP_MOD

USE INTDYN_MOD, ONLY : TRCP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TRCP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRCP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TRCP
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TRCP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TRCP (SELF, KLUN)

IMPLICIT NONE
TYPE (TRCP), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%M_CP
WRITE (KLUN) SELF%M_R
WRITE (KLUN) SELF%M_KAP
WRITE (KLUN) SELF%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TRCP (SELF, KLUN)

IMPLICIT NONE
TYPE (TRCP), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%M_CP
READ (KLUN) SELF%M_R
READ (KLUN) SELF%M_KAP
READ (KLUN) SELF%NDIM
END SUBROUTINE


SUBROUTINE COPY_TRCP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TRCP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TRCP (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TRCP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
