MODULE UTIL_TCST_MOD

USE YOMCST, ONLY : TCST

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCST
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCST
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCST
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCST
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCST (SELF, KLUN)

IMPLICIT NONE
TYPE (TCST), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%RPI
WRITE (KLUN) SELF%RCLUM
WRITE (KLUN) SELF%RHPLA
WRITE (KLUN) SELF%RKBOL
WRITE (KLUN) SELF%RNAVO
WRITE (KLUN) SELF%RDAY
WRITE (KLUN) SELF%RDAYI
WRITE (KLUN) SELF%RHOUR
WRITE (KLUN) SELF%REA
WRITE (KLUN) SELF%REPSM
WRITE (KLUN) SELF%RSIYEA
WRITE (KLUN) SELF%RSIDAY
WRITE (KLUN) SELF%ROMEGA
WRITE (KLUN) SELF%RA
WRITE (KLUN) SELF%RG
WRITE (KLUN) SELF%R1SA
WRITE (KLUN) SELF%DEG2RAD
WRITE (KLUN) SELF%RSIGMA
WRITE (KLUN) SELF%RI0
WRITE (KLUN) SELF%R
WRITE (KLUN) SELF%RMD
WRITE (KLUN) SELF%RMV
WRITE (KLUN) SELF%RMO3
WRITE (KLUN) SELF%RD
WRITE (KLUN) SELF%RV
WRITE (KLUN) SELF%RCPD
WRITE (KLUN) SELF%RCPV
WRITE (KLUN) SELF%RCVD
WRITE (KLUN) SELF%RCVV
WRITE (KLUN) SELF%RKAPPA
WRITE (KLUN) SELF%RETV
WRITE (KLUN) SELF%RMCO2
WRITE (KLUN) SELF%RMCH4
WRITE (KLUN) SELF%RMN2O
WRITE (KLUN) SELF%RMCO
WRITE (KLUN) SELF%RMHCHO
WRITE (KLUN) SELF%RMNO2
WRITE (KLUN) SELF%RMSO2
WRITE (KLUN) SELF%RMSO4
WRITE (KLUN) SELF%RMCFC11
WRITE (KLUN) SELF%RMCFC12
WRITE (KLUN) SELF%RMHCFC22
WRITE (KLUN) SELF%RMCCL4
WRITE (KLUN) SELF%RCW
WRITE (KLUN) SELF%RCS
WRITE (KLUN) SELF%RATM
WRITE (KLUN) SELF%RTT
WRITE (KLUN) SELF%RLVTT
WRITE (KLUN) SELF%RLSTT
WRITE (KLUN) SELF%RLVZER
WRITE (KLUN) SELF%RLSZER
WRITE (KLUN) SELF%RLMLT
WRITE (KLUN) SELF%RDT
WRITE (KLUN) SELF%RESTT
WRITE (KLUN) SELF%RGAMW
WRITE (KLUN) SELF%RBETW
WRITE (KLUN) SELF%RALPW
WRITE (KLUN) SELF%RGAMS
WRITE (KLUN) SELF%RBETS
WRITE (KLUN) SELF%RALPS
WRITE (KLUN) SELF%RALPD
WRITE (KLUN) SELF%RBETD
WRITE (KLUN) SELF%RGAMD
WRITE (KLUN) SELF%RK1
WRITE (KLUN) SELF%RK2
WRITE (KLUN) SELF%RK3
WRITE (KLUN) SELF%RGNSSSAT
WRITE (KLUN) SELF%RGNSSEAR
WRITE (KLUN) SELF%RAWGS
WRITE (KLUN) SELF%REWGS
WRITE (KLUN) SELF%RFWGS
WRITE (KLUN) SELF%RGEQU
WRITE (KLUN) SELF%RGRAT
WRITE (KLUN) SELF%RKSSOM
END SUBROUTINE

SUBROUTINE LOAD_TCST (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TCST), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
SELF%RPI = ZTMP0
READ (KLUN) ZTMP0
SELF%RCLUM = ZTMP0
READ (KLUN) ZTMP0
SELF%RHPLA = ZTMP0
READ (KLUN) ZTMP0
SELF%RKBOL = ZTMP0
READ (KLUN) ZTMP0
SELF%RNAVO = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAY = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAYI = ZTMP0
READ (KLUN) ZTMP0
SELF%RHOUR = ZTMP0
READ (KLUN) ZTMP0
SELF%REA = ZTMP0
READ (KLUN) ZTMP0
SELF%REPSM = ZTMP0
READ (KLUN) ZTMP0
SELF%RSIYEA = ZTMP0
READ (KLUN) ZTMP0
SELF%RSIDAY = ZTMP0
READ (KLUN) ZTMP0
SELF%ROMEGA = ZTMP0
READ (KLUN) ZTMP0
SELF%RA = ZTMP0
READ (KLUN) ZTMP0
SELF%RG = ZTMP0
READ (KLUN) ZTMP0
SELF%R1SA = ZTMP0
READ (KLUN) ZTMP0
SELF%DEG2RAD = ZTMP0
READ (KLUN) ZTMP0
SELF%RSIGMA = ZTMP0
READ (KLUN) ZTMP0
SELF%RI0 = ZTMP0
READ (KLUN) ZTMP0
SELF%R = ZTMP0
READ (KLUN) ZTMP0
SELF%RMD = ZTMP0
READ (KLUN) ZTMP0
SELF%RMV = ZTMP0
READ (KLUN) ZTMP0
SELF%RMO3 = ZTMP0
READ (KLUN) ZTMP0
SELF%RD = ZTMP0
READ (KLUN) ZTMP0
SELF%RV = ZTMP0
READ (KLUN) ZTMP0
SELF%RCPD = ZTMP0
READ (KLUN) ZTMP0
SELF%RCPV = ZTMP0
READ (KLUN) ZTMP0
SELF%RCVD = ZTMP0
READ (KLUN) ZTMP0
SELF%RCVV = ZTMP0
READ (KLUN) ZTMP0
SELF%RKAPPA = ZTMP0
READ (KLUN) ZTMP0
SELF%RETV = ZTMP0
READ (KLUN) ZTMP0
SELF%RMCO2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RMCH4 = ZTMP0
READ (KLUN) ZTMP0
SELF%RMN2O = ZTMP0
READ (KLUN) ZTMP0
SELF%RMCO = ZTMP0
READ (KLUN) ZTMP0
SELF%RMHCHO = ZTMP0
READ (KLUN) ZTMP0
SELF%RMNO2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RMSO2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RMSO4 = ZTMP0
READ (KLUN) ZTMP0
SELF%RMCFC11 = ZTMP0
READ (KLUN) ZTMP0
SELF%RMCFC12 = ZTMP0
READ (KLUN) ZTMP0
SELF%RMHCFC22 = ZTMP0
READ (KLUN) ZTMP0
SELF%RMCCL4 = ZTMP0
READ (KLUN) ZTMP0
SELF%RCW = ZTMP0
READ (KLUN) ZTMP0
SELF%RCS = ZTMP0
READ (KLUN) ZTMP0
SELF%RATM = ZTMP0
READ (KLUN) ZTMP0
SELF%RTT = ZTMP0
READ (KLUN) ZTMP0
SELF%RLVTT = ZTMP0
READ (KLUN) ZTMP0
SELF%RLSTT = ZTMP0
READ (KLUN) ZTMP0
SELF%RLVZER = ZTMP0
READ (KLUN) ZTMP0
SELF%RLSZER = ZTMP0
READ (KLUN) ZTMP0
SELF%RLMLT = ZTMP0
READ (KLUN) ZTMP0
SELF%RDT = ZTMP0
READ (KLUN) ZTMP0
SELF%RESTT = ZTMP0
READ (KLUN) ZTMP0
SELF%RGAMW = ZTMP0
READ (KLUN) ZTMP0
SELF%RBETW = ZTMP0
READ (KLUN) ZTMP0
SELF%RALPW = ZTMP0
READ (KLUN) ZTMP0
SELF%RGAMS = ZTMP0
READ (KLUN) ZTMP0
SELF%RBETS = ZTMP0
READ (KLUN) ZTMP0
SELF%RALPS = ZTMP0
READ (KLUN) ZTMP0
SELF%RALPD = ZTMP0
READ (KLUN) ZTMP0
SELF%RBETD = ZTMP0
READ (KLUN) ZTMP0
SELF%RGAMD = ZTMP0
READ (KLUN) ZTMP0
SELF%RK1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RK2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RK3 = ZTMP0
READ (KLUN) ZTMP0
SELF%RGNSSSAT = ZTMP0
READ (KLUN) ZTMP0
SELF%RGNSSEAR = ZTMP0
READ (KLUN) ZTMP0
SELF%RAWGS = ZTMP0
READ (KLUN) ZTMP0
SELF%REWGS = ZTMP0
READ (KLUN) ZTMP0
SELF%RFWGS = ZTMP0
READ (KLUN) ZTMP0
SELF%RGEQU = ZTMP0
READ (KLUN) ZTMP0
SELF%RGRAT = ZTMP0
READ (KLUN) ZTMP0
SELF%RKSSOM = ZTMP0
END SUBROUTINE


SUBROUTINE COPY_TCST (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCST), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TCST (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCST), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
