MODULE UTIL_TEAERC_MOD

USE YOEAERC, ONLY : TEAERC

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEAERC
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEAERC
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEAERC
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEAERC
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEAERC (SELF, KLUN)

IMPLICIT NONE
TYPE (TEAERC), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LAER_TYPE, LCOLUMN_MASS, LCOLUMN_MASS_MON, LCUM_FRACTION, LEPOCH, LISPECIES_INDEX, LIS_SPECIES_4D, LMMR, LMMR_MON1, LMMR_MON2
LOGICAL :: LPRESSURE, LPRESSURE_MON1, LPRESSURE_MON2, LSCALE_HEIGHT_MON, LVAR_NAME
LCOLUMN_MASS_MON = ALLOCATED (SELF%COLUMN_MASS_MON)
WRITE (KLUN) LCOLUMN_MASS_MON
IF (LCOLUMN_MASS_MON) THEN
  WRITE (KLUN) LBOUND (SELF%COLUMN_MASS_MON)
  WRITE (KLUN) UBOUND (SELF%COLUMN_MASS_MON)
  WRITE (KLUN) SELF%COLUMN_MASS_MON
ENDIF
LSCALE_HEIGHT_MON = ALLOCATED (SELF%SCALE_HEIGHT_MON)
WRITE (KLUN) LSCALE_HEIGHT_MON
IF (LSCALE_HEIGHT_MON) THEN
  WRITE (KLUN) LBOUND (SELF%SCALE_HEIGHT_MON)
  WRITE (KLUN) UBOUND (SELF%SCALE_HEIGHT_MON)
  WRITE (KLUN) SELF%SCALE_HEIGHT_MON
ENDIF
LCOLUMN_MASS = ALLOCATED (SELF%COLUMN_MASS)
WRITE (KLUN) LCOLUMN_MASS
IF (LCOLUMN_MASS) THEN
  WRITE (KLUN) LBOUND (SELF%COLUMN_MASS)
  WRITE (KLUN) UBOUND (SELF%COLUMN_MASS)
  WRITE (KLUN) SELF%COLUMN_MASS
ENDIF
LCUM_FRACTION = ALLOCATED (SELF%CUM_FRACTION)
WRITE (KLUN) LCUM_FRACTION
IF (LCUM_FRACTION) THEN
  WRITE (KLUN) LBOUND (SELF%CUM_FRACTION)
  WRITE (KLUN) UBOUND (SELF%CUM_FRACTION)
  WRITE (KLUN) SELF%CUM_FRACTION
ENDIF
LAER_TYPE = ALLOCATED (SELF%AER_TYPE)
WRITE (KLUN) LAER_TYPE
IF (LAER_TYPE) THEN
  WRITE (KLUN) LBOUND (SELF%AER_TYPE)
  WRITE (KLUN) UBOUND (SELF%AER_TYPE)
  WRITE (KLUN) SELF%AER_TYPE
ENDIF
LMMR_MON1 = ALLOCATED (SELF%MMR_MON1)
WRITE (KLUN) LMMR_MON1
IF (LMMR_MON1) THEN
  WRITE (KLUN) LBOUND (SELF%MMR_MON1)
  WRITE (KLUN) UBOUND (SELF%MMR_MON1)
  WRITE (KLUN) SELF%MMR_MON1
ENDIF
LMMR_MON2 = ALLOCATED (SELF%MMR_MON2)
WRITE (KLUN) LMMR_MON2
IF (LMMR_MON2) THEN
  WRITE (KLUN) LBOUND (SELF%MMR_MON2)
  WRITE (KLUN) UBOUND (SELF%MMR_MON2)
  WRITE (KLUN) SELF%MMR_MON2
ENDIF
LPRESSURE_MON1 = ASSOCIATED (SELF%PRESSURE_MON1)
WRITE (KLUN) LPRESSURE_MON1
IF (LPRESSURE_MON1) THEN
  WRITE (KLUN) LBOUND (SELF%PRESSURE_MON1)
  WRITE (KLUN) UBOUND (SELF%PRESSURE_MON1)
  WRITE (KLUN) SELF%PRESSURE_MON1
ENDIF
LPRESSURE_MON2 = ASSOCIATED (SELF%PRESSURE_MON2)
WRITE (KLUN) LPRESSURE_MON2
IF (LPRESSURE_MON2) THEN
  WRITE (KLUN) LBOUND (SELF%PRESSURE_MON2)
  WRITE (KLUN) UBOUND (SELF%PRESSURE_MON2)
  WRITE (KLUN) SELF%PRESSURE_MON2
ENDIF
LMMR = ALLOCATED (SELF%MMR)
WRITE (KLUN) LMMR
IF (LMMR) THEN
  WRITE (KLUN) LBOUND (SELF%MMR)
  WRITE (KLUN) UBOUND (SELF%MMR)
  WRITE (KLUN) SELF%MMR
ENDIF
LPRESSURE = ALLOCATED (SELF%PRESSURE)
WRITE (KLUN) LPRESSURE
IF (LPRESSURE) THEN
  WRITE (KLUN) LBOUND (SELF%PRESSURE)
  WRITE (KLUN) UBOUND (SELF%PRESSURE)
  WRITE (KLUN) SELF%PRESSURE
ENDIF
LEPOCH = ALLOCATED (SELF%EPOCH)
WRITE (KLUN) LEPOCH
IF (LEPOCH) THEN
  WRITE (KLUN) LBOUND (SELF%EPOCH)
  WRITE (KLUN) UBOUND (SELF%EPOCH)
  WRITE (KLUN) SELF%EPOCH
ENDIF
WRITE (KLUN) SELF%YEAR1
WRITE (KLUN) SELF%YEAR2
WRITE (KLUN) SELF%MON1
WRITE (KLUN) SELF%MON2
WRITE (KLUN) SELF%FILE_NAME
LVAR_NAME = ALLOCATED (SELF%VAR_NAME)
WRITE (KLUN) LVAR_NAME
IF (LVAR_NAME) THEN
  WRITE (KLUN) LBOUND (SELF%VAR_NAME)
  WRITE (KLUN) UBOUND (SELF%VAR_NAME)
  WRITE (KLUN) SELF%VAR_NAME
ENDIF
LIS_SPECIES_4D = ALLOCATED (SELF%IS_SPECIES_4D)
WRITE (KLUN) LIS_SPECIES_4D
IF (LIS_SPECIES_4D) THEN
  WRITE (KLUN) LBOUND (SELF%IS_SPECIES_4D)
  WRITE (KLUN) UBOUND (SELF%IS_SPECIES_4D)
  WRITE (KLUN) SELF%IS_SPECIES_4D
ENDIF
LISPECIES_INDEX = ALLOCATED (SELF%ISPECIES_INDEX)
WRITE (KLUN) LISPECIES_INDEX
IF (LISPECIES_INDEX) THEN
  WRITE (KLUN) LBOUND (SELF%ISPECIES_INDEX)
  WRITE (KLUN) UBOUND (SELF%ISPECIES_INDEX)
  WRITE (KLUN) SELF%ISPECIES_INDEX
ENDIF
WRITE (KLUN) SELF%NLAT
WRITE (KLUN) SELF%NLON
WRITE (KLUN) SELF%NLEV
WRITE (KLUN) SELF%NMON
WRITE (KLUN) SELF%NAER
WRITE (KLUN) SELF%LAT1
WRITE (KLUN) SELF%LON1
WRITE (KLUN) SELF%DLAT
WRITE (KLUN) SELF%DLON
WRITE (KLUN) SELF%IS_INITIALISED
WRITE (KLUN) SELF%DIMENSIONALITY
END SUBROUTINE

SUBROUTINE LOAD_TEAERC (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TEAERC), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LAER_TYPE, LCOLUMN_MASS, LCOLUMN_MASS_MON, LCUM_FRACTION, LEPOCH, LISPECIES_INDEX, LIS_SPECIES_4D, LMMR, LMMR_MON1, LMMR_MON2
LOGICAL :: LPRESSURE, LPRESSURE_MON1, LPRESSURE_MON2, LSCALE_HEIGHT_MON, LVAR_NAME
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP4 (:,:,:,:)
READ (KLUN) LCOLUMN_MASS_MON
IF (LCOLUMN_MASS_MON) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (SELF%COLUMN_MASS_MON (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(SELF%COLUMN_MASS_MON,1):UBOUND(SELF%COLUMN_MASS_MON,1), LBOUND(SELF%COLUMN_MASS_MON,2):UBOUND(SELF%COLUMN_MASS_MON,2), LBOUND(SELF%COLUMN_MASS_MON,3):UBOUND(SELF%COLUMN_MASS_MON,3), LBOUND(SELF%COLUMN_MASS_MON,4):UBOUND(SELF%COLUMN_MASS_MON,4)))
  READ (KLUN) ZTMP4
  SELF%COLUMN_MASS_MON = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
READ (KLUN) LSCALE_HEIGHT_MON
IF (LSCALE_HEIGHT_MON) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SCALE_HEIGHT_MON (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SCALE_HEIGHT_MON,1):UBOUND(SELF%SCALE_HEIGHT_MON,1), LBOUND(SELF%SCALE_HEIGHT_MON,2):UBOUND(SELF%SCALE_HEIGHT_MON,2)))
  READ (KLUN) ZTMP2
  SELF%SCALE_HEIGHT_MON = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LCOLUMN_MASS
IF (LCOLUMN_MASS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%COLUMN_MASS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%COLUMN_MASS,1):UBOUND(SELF%COLUMN_MASS,1), LBOUND(SELF%COLUMN_MASS,2):UBOUND(SELF%COLUMN_MASS,2), LBOUND(SELF%COLUMN_MASS,3):UBOUND(SELF%COLUMN_MASS,3)))
  READ (KLUN) ZTMP3
  SELF%COLUMN_MASS = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LCUM_FRACTION
IF (LCUM_FRACTION) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%CUM_FRACTION (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%CUM_FRACTION,1):UBOUND(SELF%CUM_FRACTION,1), LBOUND(SELF%CUM_FRACTION,2):UBOUND(SELF%CUM_FRACTION,2)))
  READ (KLUN) ZTMP2
  SELF%CUM_FRACTION = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LAER_TYPE
IF (LAER_TYPE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%AER_TYPE (IL1(1):IU1(1)))
  READ (KLUN) SELF%AER_TYPE
ENDIF
READ (KLUN) LMMR_MON1
IF (LMMR_MON1) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (SELF%MMR_MON1 (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(SELF%MMR_MON1,1):UBOUND(SELF%MMR_MON1,1), LBOUND(SELF%MMR_MON1,2):UBOUND(SELF%MMR_MON1,2), LBOUND(SELF%MMR_MON1,3):UBOUND(SELF%MMR_MON1,3), LBOUND(SELF%MMR_MON1,4):UBOUND(SELF%MMR_MON1,4)))
  READ (KLUN) ZTMP4
  SELF%MMR_MON1 = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
READ (KLUN) LMMR_MON2
IF (LMMR_MON2) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (SELF%MMR_MON2 (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(SELF%MMR_MON2,1):UBOUND(SELF%MMR_MON2,1), LBOUND(SELF%MMR_MON2,2):UBOUND(SELF%MMR_MON2,2), LBOUND(SELF%MMR_MON2,3):UBOUND(SELF%MMR_MON2,3), LBOUND(SELF%MMR_MON2,4):UBOUND(SELF%MMR_MON2,4)))
  READ (KLUN) ZTMP4
  SELF%MMR_MON2 = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
READ (KLUN) LPRESSURE_MON1
IF (LPRESSURE_MON1) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%PRESSURE_MON1 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%PRESSURE_MON1,1):UBOUND(SELF%PRESSURE_MON1,1), LBOUND(SELF%PRESSURE_MON1,2):UBOUND(SELF%PRESSURE_MON1,2), LBOUND(SELF%PRESSURE_MON1,3):UBOUND(SELF%PRESSURE_MON1,3)))
  READ (KLUN) ZTMP3
  SELF%PRESSURE_MON1 = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (SELF%PRESSURE_MON1)
ENDIF
READ (KLUN) LPRESSURE_MON2
IF (LPRESSURE_MON2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%PRESSURE_MON2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%PRESSURE_MON2,1):UBOUND(SELF%PRESSURE_MON2,1), LBOUND(SELF%PRESSURE_MON2,2):UBOUND(SELF%PRESSURE_MON2,2), LBOUND(SELF%PRESSURE_MON2,3):UBOUND(SELF%PRESSURE_MON2,3)))
  READ (KLUN) ZTMP3
  SELF%PRESSURE_MON2 = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (SELF%PRESSURE_MON2)
ENDIF
READ (KLUN) LMMR
IF (LMMR) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (SELF%MMR (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(SELF%MMR,1):UBOUND(SELF%MMR,1), LBOUND(SELF%MMR,2):UBOUND(SELF%MMR,2), LBOUND(SELF%MMR,3):UBOUND(SELF%MMR,3), LBOUND(SELF%MMR,4):UBOUND(SELF%MMR,4)))
  READ (KLUN) ZTMP4
  SELF%MMR = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
READ (KLUN) LPRESSURE
IF (LPRESSURE) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%PRESSURE (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%PRESSURE,1):UBOUND(SELF%PRESSURE,1), LBOUND(SELF%PRESSURE,2):UBOUND(SELF%PRESSURE,2), LBOUND(SELF%PRESSURE,3):UBOUND(SELF%PRESSURE,3)))
  READ (KLUN) ZTMP3
  SELF%PRESSURE = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LEPOCH
IF (LEPOCH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%EPOCH (IL1(1):IU1(1)))
  READ (KLUN) SELF%EPOCH
ENDIF
READ (KLUN) SELF%YEAR1
READ (KLUN) SELF%YEAR2
READ (KLUN) SELF%MON1
READ (KLUN) SELF%MON2
READ (KLUN) SELF%FILE_NAME
READ (KLUN) LVAR_NAME
IF (LVAR_NAME) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%VAR_NAME (IL1(1):IU1(1)))
  READ (KLUN) SELF%VAR_NAME
ENDIF
READ (KLUN) LIS_SPECIES_4D
IF (LIS_SPECIES_4D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%IS_SPECIES_4D (IL1(1):IU1(1)))
  READ (KLUN) SELF%IS_SPECIES_4D
ENDIF
READ (KLUN) LISPECIES_INDEX
IF (LISPECIES_INDEX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%ISPECIES_INDEX (IL1(1):IU1(1)))
  READ (KLUN) SELF%ISPECIES_INDEX
ENDIF
READ (KLUN) SELF%NLAT
READ (KLUN) SELF%NLON
READ (KLUN) SELF%NLEV
READ (KLUN) SELF%NMON
READ (KLUN) SELF%NAER
READ (KLUN) ZTMP0
SELF%LAT1 = ZTMP0
READ (KLUN) ZTMP0
SELF%LON1 = ZTMP0
READ (KLUN) ZTMP0
SELF%DLAT = ZTMP0
READ (KLUN) ZTMP0
SELF%DLON = ZTMP0
READ (KLUN) SELF%IS_INITIALISED
READ (KLUN) SELF%DIMENSIONALITY
END SUBROUTINE


SUBROUTINE COPY_TEAERC (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEAERC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LAER_TYPE, LCOLUMN_MASS, LCOLUMN_MASS_MON, LCUM_FRACTION, LEPOCH, LISPECIES_INDEX, LIS_SPECIES_4D, LMMR, LMMR_MON1, LMMR_MON2
LOGICAL :: LPRESSURE, LPRESSURE_MON1, LPRESSURE_MON2, LSCALE_HEIGHT_MON, LVAR_NAME

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LCOLUMN_MASS_MON = ALLOCATED (SELF%COLUMN_MASS_MON)
IF (LCOLUMN_MASS_MON) THEN
  !$ACC ENTER DATA CREATE (SELF%COLUMN_MASS_MON)
  !$ACC UPDATE DEVICE (SELF%COLUMN_MASS_MON)
  !$ACC ENTER DATA ATTACH (SELF%COLUMN_MASS_MON)
ENDIF

LSCALE_HEIGHT_MON = ALLOCATED (SELF%SCALE_HEIGHT_MON)
IF (LSCALE_HEIGHT_MON) THEN
  !$ACC ENTER DATA CREATE (SELF%SCALE_HEIGHT_MON)
  !$ACC UPDATE DEVICE (SELF%SCALE_HEIGHT_MON)
  !$ACC ENTER DATA ATTACH (SELF%SCALE_HEIGHT_MON)
ENDIF

LCOLUMN_MASS = ALLOCATED (SELF%COLUMN_MASS)
IF (LCOLUMN_MASS) THEN
  !$ACC ENTER DATA CREATE (SELF%COLUMN_MASS)
  !$ACC UPDATE DEVICE (SELF%COLUMN_MASS)
  !$ACC ENTER DATA ATTACH (SELF%COLUMN_MASS)
ENDIF

LCUM_FRACTION = ALLOCATED (SELF%CUM_FRACTION)
IF (LCUM_FRACTION) THEN
  !$ACC ENTER DATA CREATE (SELF%CUM_FRACTION)
  !$ACC UPDATE DEVICE (SELF%CUM_FRACTION)
  !$ACC ENTER DATA ATTACH (SELF%CUM_FRACTION)
ENDIF

LAER_TYPE = ALLOCATED (SELF%AER_TYPE)
IF (LAER_TYPE) THEN
  !$ACC ENTER DATA CREATE (SELF%AER_TYPE)
  !$ACC UPDATE DEVICE (SELF%AER_TYPE)
  !$ACC ENTER DATA ATTACH (SELF%AER_TYPE)
ENDIF

LMMR_MON1 = ALLOCATED (SELF%MMR_MON1)
IF (LMMR_MON1) THEN
  !$ACC ENTER DATA CREATE (SELF%MMR_MON1)
  !$ACC UPDATE DEVICE (SELF%MMR_MON1)
  !$ACC ENTER DATA ATTACH (SELF%MMR_MON1)
ENDIF

LMMR_MON2 = ALLOCATED (SELF%MMR_MON2)
IF (LMMR_MON2) THEN
  !$ACC ENTER DATA CREATE (SELF%MMR_MON2)
  !$ACC UPDATE DEVICE (SELF%MMR_MON2)
  !$ACC ENTER DATA ATTACH (SELF%MMR_MON2)
ENDIF

LPRESSURE_MON1 = ASSOCIATED (SELF%PRESSURE_MON1)
IF (LPRESSURE_MON1) THEN
  !$ACC ENTER DATA CREATE (SELF%PRESSURE_MON1)
  !$ACC UPDATE DEVICE (SELF%PRESSURE_MON1)
  !$ACC ENTER DATA ATTACH (SELF%PRESSURE_MON1)
ENDIF

LPRESSURE_MON2 = ASSOCIATED (SELF%PRESSURE_MON2)
IF (LPRESSURE_MON2) THEN
  !$ACC ENTER DATA CREATE (SELF%PRESSURE_MON2)
  !$ACC UPDATE DEVICE (SELF%PRESSURE_MON2)
  !$ACC ENTER DATA ATTACH (SELF%PRESSURE_MON2)
ENDIF

LMMR = ALLOCATED (SELF%MMR)
IF (LMMR) THEN
  !$ACC ENTER DATA CREATE (SELF%MMR)
  !$ACC UPDATE DEVICE (SELF%MMR)
  !$ACC ENTER DATA ATTACH (SELF%MMR)
ENDIF

LPRESSURE = ALLOCATED (SELF%PRESSURE)
IF (LPRESSURE) THEN
  !$ACC ENTER DATA CREATE (SELF%PRESSURE)
  !$ACC UPDATE DEVICE (SELF%PRESSURE)
  !$ACC ENTER DATA ATTACH (SELF%PRESSURE)
ENDIF

LEPOCH = ALLOCATED (SELF%EPOCH)
IF (LEPOCH) THEN
  !$ACC ENTER DATA CREATE (SELF%EPOCH)
  !$ACC UPDATE DEVICE (SELF%EPOCH)
  !$ACC ENTER DATA ATTACH (SELF%EPOCH)
ENDIF

LVAR_NAME = ALLOCATED (SELF%VAR_NAME)
IF (LVAR_NAME) THEN
  !$ACC ENTER DATA CREATE (SELF%VAR_NAME)
  !$ACC UPDATE DEVICE (SELF%VAR_NAME)
  !$ACC ENTER DATA ATTACH (SELF%VAR_NAME)
ENDIF

LIS_SPECIES_4D = ALLOCATED (SELF%IS_SPECIES_4D)
IF (LIS_SPECIES_4D) THEN
  !$ACC ENTER DATA CREATE (SELF%IS_SPECIES_4D)
  !$ACC UPDATE DEVICE (SELF%IS_SPECIES_4D)
  !$ACC ENTER DATA ATTACH (SELF%IS_SPECIES_4D)
ENDIF

LISPECIES_INDEX = ALLOCATED (SELF%ISPECIES_INDEX)
IF (LISPECIES_INDEX) THEN
  !$ACC ENTER DATA CREATE (SELF%ISPECIES_INDEX)
  !$ACC UPDATE DEVICE (SELF%ISPECIES_INDEX)
  !$ACC ENTER DATA ATTACH (SELF%ISPECIES_INDEX)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TEAERC (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEAERC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LAER_TYPE, LCOLUMN_MASS, LCOLUMN_MASS_MON, LCUM_FRACTION, LEPOCH, LISPECIES_INDEX, LIS_SPECIES_4D, LMMR, LMMR_MON1, LMMR_MON2
LOGICAL :: LPRESSURE, LPRESSURE_MON1, LPRESSURE_MON2, LSCALE_HEIGHT_MON, LVAR_NAME

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LCOLUMN_MASS_MON = ALLOCATED (SELF%COLUMN_MASS_MON)
IF (LCOLUMN_MASS_MON) THEN
  !$ACC EXIT DATA DETACH (SELF%COLUMN_MASS_MON)
  !$ACC EXIT DATA DETACH (SELF%COLUMN_MASS_MON)
ENDIF

LSCALE_HEIGHT_MON = ALLOCATED (SELF%SCALE_HEIGHT_MON)
IF (LSCALE_HEIGHT_MON) THEN
  !$ACC EXIT DATA DETACH (SELF%SCALE_HEIGHT_MON)
  !$ACC EXIT DATA DETACH (SELF%SCALE_HEIGHT_MON)
ENDIF

LCOLUMN_MASS = ALLOCATED (SELF%COLUMN_MASS)
IF (LCOLUMN_MASS) THEN
  !$ACC EXIT DATA DETACH (SELF%COLUMN_MASS)
  !$ACC EXIT DATA DETACH (SELF%COLUMN_MASS)
ENDIF

LCUM_FRACTION = ALLOCATED (SELF%CUM_FRACTION)
IF (LCUM_FRACTION) THEN
  !$ACC EXIT DATA DETACH (SELF%CUM_FRACTION)
  !$ACC EXIT DATA DETACH (SELF%CUM_FRACTION)
ENDIF

LAER_TYPE = ALLOCATED (SELF%AER_TYPE)
IF (LAER_TYPE) THEN
  !$ACC EXIT DATA DETACH (SELF%AER_TYPE)
  !$ACC EXIT DATA DETACH (SELF%AER_TYPE)
ENDIF

LMMR_MON1 = ALLOCATED (SELF%MMR_MON1)
IF (LMMR_MON1) THEN
  !$ACC EXIT DATA DETACH (SELF%MMR_MON1)
  !$ACC EXIT DATA DETACH (SELF%MMR_MON1)
ENDIF

LMMR_MON2 = ALLOCATED (SELF%MMR_MON2)
IF (LMMR_MON2) THEN
  !$ACC EXIT DATA DETACH (SELF%MMR_MON2)
  !$ACC EXIT DATA DETACH (SELF%MMR_MON2)
ENDIF

LPRESSURE_MON1 = ASSOCIATED (SELF%PRESSURE_MON1)
IF (LPRESSURE_MON1) THEN
  !$ACC EXIT DATA DETACH (SELF%PRESSURE_MON1)
  !$ACC EXIT DATA DETACH (SELF%PRESSURE_MON1)
ENDIF

LPRESSURE_MON2 = ASSOCIATED (SELF%PRESSURE_MON2)
IF (LPRESSURE_MON2) THEN
  !$ACC EXIT DATA DETACH (SELF%PRESSURE_MON2)
  !$ACC EXIT DATA DETACH (SELF%PRESSURE_MON2)
ENDIF

LMMR = ALLOCATED (SELF%MMR)
IF (LMMR) THEN
  !$ACC EXIT DATA DETACH (SELF%MMR)
  !$ACC EXIT DATA DETACH (SELF%MMR)
ENDIF

LPRESSURE = ALLOCATED (SELF%PRESSURE)
IF (LPRESSURE) THEN
  !$ACC EXIT DATA DETACH (SELF%PRESSURE)
  !$ACC EXIT DATA DETACH (SELF%PRESSURE)
ENDIF

LEPOCH = ALLOCATED (SELF%EPOCH)
IF (LEPOCH) THEN
  !$ACC EXIT DATA DETACH (SELF%EPOCH)
  !$ACC EXIT DATA DETACH (SELF%EPOCH)
ENDIF

LVAR_NAME = ALLOCATED (SELF%VAR_NAME)
IF (LVAR_NAME) THEN
  !$ACC EXIT DATA DETACH (SELF%VAR_NAME)
  !$ACC EXIT DATA DETACH (SELF%VAR_NAME)
ENDIF

LIS_SPECIES_4D = ALLOCATED (SELF%IS_SPECIES_4D)
IF (LIS_SPECIES_4D) THEN
  !$ACC EXIT DATA DETACH (SELF%IS_SPECIES_4D)
  !$ACC EXIT DATA DETACH (SELF%IS_SPECIES_4D)
ENDIF

LISPECIES_INDEX = ALLOCATED (SELF%ISPECIES_INDEX)
IF (LISPECIES_INDEX) THEN
  !$ACC EXIT DATA DETACH (SELF%ISPECIES_INDEX)
  !$ACC EXIT DATA DETACH (SELF%ISPECIES_INDEX)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
