MODULE UTIL_TVAB_MOD

USE YOMVERT, ONLY : TVAB

INTERFACE SAVE
MODULE PROCEDURE SAVE_TVAB
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVAB
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TVAB
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TVAB
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TVAB (SELF, KLUN)

IMPLICIT NONE
TYPE (TVAB), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LVAF, LVAH, LVALH, LVBF, LVBH, LVC, LVDELA, LVDELB, LVRATF, LVRATH
LVALH = ALLOCATED (SELF%VALH)
WRITE (KLUN) LVALH
IF (LVALH) THEN
  WRITE (KLUN) LBOUND (SELF%VALH)
  WRITE (KLUN) UBOUND (SELF%VALH)
  WRITE (KLUN) SELF%VALH
ENDIF
LVBH = ALLOCATED (SELF%VBH)
WRITE (KLUN) LVBH
IF (LVBH) THEN
  WRITE (KLUN) LBOUND (SELF%VBH)
  WRITE (KLUN) UBOUND (SELF%VBH)
  WRITE (KLUN) SELF%VBH
ENDIF
LVAH = ALLOCATED (SELF%VAH)
WRITE (KLUN) LVAH
IF (LVAH) THEN
  WRITE (KLUN) LBOUND (SELF%VAH)
  WRITE (KLUN) UBOUND (SELF%VAH)
  WRITE (KLUN) SELF%VAH
ENDIF
LVC = ALLOCATED (SELF%VC)
WRITE (KLUN) LVC
IF (LVC) THEN
  WRITE (KLUN) LBOUND (SELF%VC)
  WRITE (KLUN) UBOUND (SELF%VC)
  WRITE (KLUN) SELF%VC
ENDIF
LVAF = ALLOCATED (SELF%VAF)
WRITE (KLUN) LVAF
IF (LVAF) THEN
  WRITE (KLUN) LBOUND (SELF%VAF)
  WRITE (KLUN) UBOUND (SELF%VAF)
  WRITE (KLUN) SELF%VAF
ENDIF
LVBF = ALLOCATED (SELF%VBF)
WRITE (KLUN) LVBF
IF (LVBF) THEN
  WRITE (KLUN) LBOUND (SELF%VBF)
  WRITE (KLUN) UBOUND (SELF%VBF)
  WRITE (KLUN) SELF%VBF
ENDIF
LVDELA = ALLOCATED (SELF%VDELA)
WRITE (KLUN) LVDELA
IF (LVDELA) THEN
  WRITE (KLUN) LBOUND (SELF%VDELA)
  WRITE (KLUN) UBOUND (SELF%VDELA)
  WRITE (KLUN) SELF%VDELA
ENDIF
LVDELB = ALLOCATED (SELF%VDELB)
WRITE (KLUN) LVDELB
IF (LVDELB) THEN
  WRITE (KLUN) LBOUND (SELF%VDELB)
  WRITE (KLUN) UBOUND (SELF%VDELB)
  WRITE (KLUN) SELF%VDELB
ENDIF
LVRATH = ALLOCATED (SELF%VRATH)
WRITE (KLUN) LVRATH
IF (LVRATH) THEN
  WRITE (KLUN) LBOUND (SELF%VRATH)
  WRITE (KLUN) UBOUND (SELF%VRATH)
  WRITE (KLUN) SELF%VRATH
ENDIF
LVRATF = ALLOCATED (SELF%VRATF)
WRITE (KLUN) LVRATF
IF (LVRATF) THEN
  WRITE (KLUN) LBOUND (SELF%VRATF)
  WRITE (KLUN) UBOUND (SELF%VRATF)
  WRITE (KLUN) SELF%VRATF
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TVAB (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TVAB), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LVAF, LVAH, LVALH, LVBF, LVBH, LVC, LVDELA, LVDELB, LVRATF, LVRATH
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
READ (KLUN) LVALH
IF (LVALH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%VALH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%VALH,1):UBOUND(SELF%VALH,1)))
  READ (KLUN) ZTMP1
  SELF%VALH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LVBH
IF (LVBH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%VBH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%VBH,1):UBOUND(SELF%VBH,1)))
  READ (KLUN) ZTMP1
  SELF%VBH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LVAH
IF (LVAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%VAH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%VAH,1):UBOUND(SELF%VAH,1)))
  READ (KLUN) ZTMP1
  SELF%VAH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LVC
IF (LVC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%VC (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%VC,1):UBOUND(SELF%VC,1)))
  READ (KLUN) ZTMP1
  SELF%VC = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LVAF
IF (LVAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%VAF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%VAF,1):UBOUND(SELF%VAF,1)))
  READ (KLUN) ZTMP1
  SELF%VAF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LVBF
IF (LVBF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%VBF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%VBF,1):UBOUND(SELF%VBF,1)))
  READ (KLUN) ZTMP1
  SELF%VBF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LVDELA
IF (LVDELA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%VDELA (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%VDELA,1):UBOUND(SELF%VDELA,1)))
  READ (KLUN) ZTMP1
  SELF%VDELA = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LVDELB
IF (LVDELB) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%VDELB (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%VDELB,1):UBOUND(SELF%VDELB,1)))
  READ (KLUN) ZTMP1
  SELF%VDELB = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LVRATH
IF (LVRATH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%VRATH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%VRATH,1):UBOUND(SELF%VRATH,1)))
  READ (KLUN) ZTMP1
  SELF%VRATH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LVRATF
IF (LVRATF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%VRATF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%VRATF,1):UBOUND(SELF%VRATF,1)))
  READ (KLUN) ZTMP1
  SELF%VRATF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TVAB (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TVAB), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LVAF, LVAH, LVALH, LVBF, LVBH, LVC, LVDELA, LVDELB, LVRATF, LVRATH

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LVALH = ALLOCATED (SELF%VALH)
IF (LVALH) THEN
  !$ACC ENTER DATA CREATE (SELF%VALH)
  !$ACC UPDATE DEVICE (SELF%VALH)
  !$ACC ENTER DATA ATTACH (SELF%VALH)
ENDIF

LVBH = ALLOCATED (SELF%VBH)
IF (LVBH) THEN
  !$ACC ENTER DATA CREATE (SELF%VBH)
  !$ACC UPDATE DEVICE (SELF%VBH)
  !$ACC ENTER DATA ATTACH (SELF%VBH)
ENDIF

LVAH = ALLOCATED (SELF%VAH)
IF (LVAH) THEN
  !$ACC ENTER DATA CREATE (SELF%VAH)
  !$ACC UPDATE DEVICE (SELF%VAH)
  !$ACC ENTER DATA ATTACH (SELF%VAH)
ENDIF

LVC = ALLOCATED (SELF%VC)
IF (LVC) THEN
  !$ACC ENTER DATA CREATE (SELF%VC)
  !$ACC UPDATE DEVICE (SELF%VC)
  !$ACC ENTER DATA ATTACH (SELF%VC)
ENDIF

LVAF = ALLOCATED (SELF%VAF)
IF (LVAF) THEN
  !$ACC ENTER DATA CREATE (SELF%VAF)
  !$ACC UPDATE DEVICE (SELF%VAF)
  !$ACC ENTER DATA ATTACH (SELF%VAF)
ENDIF

LVBF = ALLOCATED (SELF%VBF)
IF (LVBF) THEN
  !$ACC ENTER DATA CREATE (SELF%VBF)
  !$ACC UPDATE DEVICE (SELF%VBF)
  !$ACC ENTER DATA ATTACH (SELF%VBF)
ENDIF

LVDELA = ALLOCATED (SELF%VDELA)
IF (LVDELA) THEN
  !$ACC ENTER DATA CREATE (SELF%VDELA)
  !$ACC UPDATE DEVICE (SELF%VDELA)
  !$ACC ENTER DATA ATTACH (SELF%VDELA)
ENDIF

LVDELB = ALLOCATED (SELF%VDELB)
IF (LVDELB) THEN
  !$ACC ENTER DATA CREATE (SELF%VDELB)
  !$ACC UPDATE DEVICE (SELF%VDELB)
  !$ACC ENTER DATA ATTACH (SELF%VDELB)
ENDIF

LVRATH = ALLOCATED (SELF%VRATH)
IF (LVRATH) THEN
  !$ACC ENTER DATA CREATE (SELF%VRATH)
  !$ACC UPDATE DEVICE (SELF%VRATH)
  !$ACC ENTER DATA ATTACH (SELF%VRATH)
ENDIF

LVRATF = ALLOCATED (SELF%VRATF)
IF (LVRATF) THEN
  !$ACC ENTER DATA CREATE (SELF%VRATF)
  !$ACC UPDATE DEVICE (SELF%VRATF)
  !$ACC ENTER DATA ATTACH (SELF%VRATF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TVAB (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TVAB), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LVAF, LVAH, LVALH, LVBF, LVBH, LVC, LVDELA, LVDELB, LVRATF, LVRATH

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LVALH = ALLOCATED (SELF%VALH)
IF (LVALH) THEN
  !$ACC EXIT DATA DETACH (SELF%VALH)
  !$ACC EXIT DATA DETACH (SELF%VALH)
ENDIF

LVBH = ALLOCATED (SELF%VBH)
IF (LVBH) THEN
  !$ACC EXIT DATA DETACH (SELF%VBH)
  !$ACC EXIT DATA DETACH (SELF%VBH)
ENDIF

LVAH = ALLOCATED (SELF%VAH)
IF (LVAH) THEN
  !$ACC EXIT DATA DETACH (SELF%VAH)
  !$ACC EXIT DATA DETACH (SELF%VAH)
ENDIF

LVC = ALLOCATED (SELF%VC)
IF (LVC) THEN
  !$ACC EXIT DATA DETACH (SELF%VC)
  !$ACC EXIT DATA DETACH (SELF%VC)
ENDIF

LVAF = ALLOCATED (SELF%VAF)
IF (LVAF) THEN
  !$ACC EXIT DATA DETACH (SELF%VAF)
  !$ACC EXIT DATA DETACH (SELF%VAF)
ENDIF

LVBF = ALLOCATED (SELF%VBF)
IF (LVBF) THEN
  !$ACC EXIT DATA DETACH (SELF%VBF)
  !$ACC EXIT DATA DETACH (SELF%VBF)
ENDIF

LVDELA = ALLOCATED (SELF%VDELA)
IF (LVDELA) THEN
  !$ACC EXIT DATA DETACH (SELF%VDELA)
  !$ACC EXIT DATA DETACH (SELF%VDELA)
ENDIF

LVDELB = ALLOCATED (SELF%VDELB)
IF (LVDELB) THEN
  !$ACC EXIT DATA DETACH (SELF%VDELB)
  !$ACC EXIT DATA DETACH (SELF%VDELB)
ENDIF

LVRATH = ALLOCATED (SELF%VRATH)
IF (LVRATH) THEN
  !$ACC EXIT DATA DETACH (SELF%VRATH)
  !$ACC EXIT DATA DETACH (SELF%VRATH)
ENDIF

LVRATF = ALLOCATED (SELF%VRATF)
IF (LVRATF) THEN
  !$ACC EXIT DATA DETACH (SELF%VRATF)
  !$ACC EXIT DATA DETACH (SELF%VRATF)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
