MODULE UTIL_TLDDH_MOD

USE YOMLDDH, ONLY : TLDDH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TLDDH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLDDH
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TLDDH
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TLDDH
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TLDDH (SELF, KLUN)

IMPLICIT NONE
TYPE (TLDDH), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LSDDH
WRITE (KLUN) SELF%LHDGLB
WRITE (KLUN) SELF%LHDZON
WRITE (KLUN) SELF%LHDDOP
WRITE (KLUN) SELF%LHDLFA
WRITE (KLUN) SELF%LHDHKS
WRITE (KLUN) SELF%LHDMCI
WRITE (KLUN) SELF%LHDENT
WRITE (KLUN) SELF%LHDPRG
WRITE (KLUN) SELF%LHDPRZ
WRITE (KLUN) SELF%LHDPRD
WRITE (KLUN) SELF%LHDPR
WRITE (KLUN) SELF%LHDEFG
WRITE (KLUN) SELF%LHDEFZ
WRITE (KLUN) SELF%LHDEFD
WRITE (KLUN) SELF%LHDLIST
WRITE (KLUN) SELF%LHDOUFG
WRITE (KLUN) SELF%LHDOUFZ
WRITE (KLUN) SELF%LHDOUFD
WRITE (KLUN) SELF%LHDOUP
WRITE (KLUN) SELF%LHDFIL
WRITE (KLUN) SELF%LONLYVAR
WRITE (KLUN) SELF%LHDORIGP
WRITE (KLUN) SELF%LHDCDPI
WRITE (KLUN) SELF%LFLEXDIA
WRITE (KLUN) SELF%LRDDHDYN
WRITE (KLUN) SELF%LRSLDDH
WRITE (KLUN) SELF%LRSIDDH
WRITE (KLUN) SELF%LRHDDDH
WRITE (KLUN) SELF%LDDH_OMP
END SUBROUTINE

SUBROUTINE LOAD_TLDDH (SELF, KLUN)

IMPLICIT NONE
TYPE (TLDDH), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%LSDDH
READ (KLUN) SELF%LHDGLB
READ (KLUN) SELF%LHDZON
READ (KLUN) SELF%LHDDOP
READ (KLUN) SELF%LHDLFA
READ (KLUN) SELF%LHDHKS
READ (KLUN) SELF%LHDMCI
READ (KLUN) SELF%LHDENT
READ (KLUN) SELF%LHDPRG
READ (KLUN) SELF%LHDPRZ
READ (KLUN) SELF%LHDPRD
READ (KLUN) SELF%LHDPR
READ (KLUN) SELF%LHDEFG
READ (KLUN) SELF%LHDEFZ
READ (KLUN) SELF%LHDEFD
READ (KLUN) SELF%LHDLIST
READ (KLUN) SELF%LHDOUFG
READ (KLUN) SELF%LHDOUFZ
READ (KLUN) SELF%LHDOUFD
READ (KLUN) SELF%LHDOUP
READ (KLUN) SELF%LHDFIL
READ (KLUN) SELF%LONLYVAR
READ (KLUN) SELF%LHDORIGP
READ (KLUN) SELF%LHDCDPI
READ (KLUN) SELF%LFLEXDIA
READ (KLUN) SELF%LRDDHDYN
READ (KLUN) SELF%LRSLDDH
READ (KLUN) SELF%LRSIDDH
READ (KLUN) SELF%LRHDDDH
READ (KLUN) SELF%LDDH_OMP
END SUBROUTINE


SUBROUTINE COPY_TLDDH (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TLDDH), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TLDDH (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TLDDH), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
