MODULE UTIL_TXYB_MOD

USE INTDYN_MOD, ONLY : TXYB

INTERFACE SAVE
MODULE PROCEDURE SAVE_TXYB
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TXYB
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TXYB
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TXYB
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TXYB (SELF, KLUN)

IMPLICIT NONE
TYPE (TXYB), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%M_DELP
WRITE (KLUN) SELF%M_RDELP
WRITE (KLUN) SELF%M_LNPR
WRITE (KLUN) SELF%M_ALPH
WRITE (KLUN) SELF%M_RTGR
WRITE (KLUN) SELF%M_RPRE
WRITE (KLUN) SELF%M_RPP
WRITE (KLUN) SELF%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TXYB (SELF, KLUN)

IMPLICIT NONE
TYPE (TXYB), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%M_DELP
READ (KLUN) SELF%M_RDELP
READ (KLUN) SELF%M_LNPR
READ (KLUN) SELF%M_ALPH
READ (KLUN) SELF%M_RTGR
READ (KLUN) SELF%M_RPRE
READ (KLUN) SELF%M_RPP
READ (KLUN) SELF%NDIM
END SUBROUTINE


SUBROUTINE COPY_TXYB (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TXYB), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TXYB (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TXYB), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
