MODULE UTIL_TDIM_MOD

USE YOMDIM, ONLY : TDIM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDIM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDIM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDIM
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDIM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TDIM (SELF, KLUN)

IMPLICIT NONE
TYPE (TDIM), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LNDLUNL, LNDLUXL
WRITE (KLUN) SELF%NDGLG
WRITE (KLUN) SELF%NDGLL
WRITE (KLUN) SELF%NDGNH
WRITE (KLUN) SELF%NDGSUR
WRITE (KLUN) SELF%NDGSAG
WRITE (KLUN) SELF%NDGSAL
WRITE (KLUN) SELF%NDGSAH
WRITE (KLUN) SELF%NDGSAFPH
WRITE (KLUN) SELF%NDGENG
WRITE (KLUN) SELF%NDGENL
WRITE (KLUN) SELF%NDGENH
WRITE (KLUN) SELF%NDGENFPH
WRITE (KLUN) SELF%NDGUNG
WRITE (KLUN) SELF%NDGUXG
WRITE (KLUN) SELF%NDGUNL
WRITE (KLUN) SELF%NDGUXL
WRITE (KLUN) SELF%NDLON
WRITE (KLUN) SELF%NDSUR1
WRITE (KLUN) SELF%NSTENCILWIDE
WRITE (KLUN) SELF%NDLSUR
WRITE (KLUN) SELF%NDLSM
WRITE (KLUN) SELF%NDLUNG
WRITE (KLUN) SELF%NDLUXG
LNDLUNL = ALLOCATED (SELF%NDLUNL)
WRITE (KLUN) LNDLUNL
IF (LNDLUNL) THEN
  WRITE (KLUN) LBOUND (SELF%NDLUNL)
  WRITE (KLUN) UBOUND (SELF%NDLUNL)
  WRITE (KLUN) SELF%NDLUNL
ENDIF
LNDLUXL = ALLOCATED (SELF%NDLUXL)
WRITE (KLUN) LNDLUXL
IF (LNDLUXL) THEN
  WRITE (KLUN) LBOUND (SELF%NDLUXL)
  WRITE (KLUN) UBOUND (SELF%NDLUXL)
  WRITE (KLUN) SELF%NDLUXL
ENDIF
WRITE (KLUN) SELF%NPROMA
WRITE (KLUN) SELF%NPROMM
WRITE (KLUN) SELF%NPROMM9
WRITE (KLUN) SELF%NPROMNH
WRITE (KLUN) SELF%NGPBLKS
WRITE (KLUN) SELF%LOPTPROMA
WRITE (KLUN) SELF%NRESOL
WRITE (KLUN) SELF%NSMAX
WRITE (KLUN) SELF%NMSMAX
WRITE (KLUN) SELF%NVARMAX
WRITE (KLUN) SELF%NSEFRE
WRITE (KLUN) SELF%NSPECG
WRITE (KLUN) SELF%NSPEC2G
WRITE (KLUN) SELF%NSPEC
WRITE (KLUN) SELF%NSPEC2
WRITE (KLUN) SELF%NSPEC2MX
WRITE (KLUN) SELF%NCMAX
WRITE (KLUN) SELF%NUMP
WRITE (KLUN) SELF%NUMCP
END SUBROUTINE

SUBROUTINE LOAD_TDIM (SELF, KLUN)

IMPLICIT NONE
TYPE (TDIM), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LNDLUNL, LNDLUXL
READ (KLUN) SELF%NDGLG
READ (KLUN) SELF%NDGLL
READ (KLUN) SELF%NDGNH
READ (KLUN) SELF%NDGSUR
READ (KLUN) SELF%NDGSAG
READ (KLUN) SELF%NDGSAL
READ (KLUN) SELF%NDGSAH
READ (KLUN) SELF%NDGSAFPH
READ (KLUN) SELF%NDGENG
READ (KLUN) SELF%NDGENL
READ (KLUN) SELF%NDGENH
READ (KLUN) SELF%NDGENFPH
READ (KLUN) SELF%NDGUNG
READ (KLUN) SELF%NDGUXG
READ (KLUN) SELF%NDGUNL
READ (KLUN) SELF%NDGUXL
READ (KLUN) SELF%NDLON
READ (KLUN) SELF%NDSUR1
READ (KLUN) SELF%NSTENCILWIDE
READ (KLUN) SELF%NDLSUR
READ (KLUN) SELF%NDLSM
READ (KLUN) SELF%NDLUNG
READ (KLUN) SELF%NDLUXG
READ (KLUN) LNDLUNL
IF (LNDLUNL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%NDLUNL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%NDLUNL
ENDIF
READ (KLUN) LNDLUXL
IF (LNDLUXL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%NDLUXL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%NDLUXL
ENDIF
READ (KLUN) SELF%NPROMA
READ (KLUN) SELF%NPROMM
READ (KLUN) SELF%NPROMM9
READ (KLUN) SELF%NPROMNH
READ (KLUN) SELF%NGPBLKS
READ (KLUN) SELF%LOPTPROMA
READ (KLUN) SELF%NRESOL
READ (KLUN) SELF%NSMAX
READ (KLUN) SELF%NMSMAX
READ (KLUN) SELF%NVARMAX
READ (KLUN) SELF%NSEFRE
READ (KLUN) SELF%NSPECG
READ (KLUN) SELF%NSPEC2G
READ (KLUN) SELF%NSPEC
READ (KLUN) SELF%NSPEC2
READ (KLUN) SELF%NSPEC2MX
READ (KLUN) SELF%NCMAX
READ (KLUN) SELF%NUMP
READ (KLUN) SELF%NUMCP
END SUBROUTINE


SUBROUTINE COPY_TDIM (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TDIM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LNDLUNL, LNDLUXL

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LNDLUNL = ALLOCATED (SELF%NDLUNL)
IF (LNDLUNL) THEN
  !$ACC ENTER DATA CREATE (SELF%NDLUNL)
  !$ACC UPDATE DEVICE (SELF%NDLUNL)
  !$ACC ENTER DATA ATTACH (SELF%NDLUNL)
ENDIF

LNDLUXL = ALLOCATED (SELF%NDLUXL)
IF (LNDLUXL) THEN
  !$ACC ENTER DATA CREATE (SELF%NDLUXL)
  !$ACC UPDATE DEVICE (SELF%NDLUXL)
  !$ACC ENTER DATA ATTACH (SELF%NDLUXL)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TDIM (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TDIM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LNDLUNL, LNDLUXL

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LNDLUNL = ALLOCATED (SELF%NDLUNL)
IF (LNDLUNL) THEN
  !$ACC EXIT DATA DETACH (SELF%NDLUNL)
  !$ACC EXIT DATA DETACH (SELF%NDLUNL)
ENDIF

LNDLUXL = ALLOCATED (SELF%NDLUXL)
IF (LNDLUXL) THEN
  !$ACC EXIT DATA DETACH (SELF%NDLUXL)
  !$ACC EXIT DATA DETACH (SELF%NDLUXL)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
