MODULE UTIL_TVERTICAL_GEOM_MOD

USE YOMVERT, ONLY : TVERTICAL_GEOM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TVERTICAL_GEOM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVERTICAL_GEOM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TVERTICAL_GEOM
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TVERTICAL_GEOM
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TVERTICAL_GEOM (SELF, KLUN)
USE UTIL_TCVER_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD
IMPLICIT NONE
TYPE (TVERTICAL_GEOM), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LNONHYD_GEOM
CALL SAVE_TVAB (SELF%YRVAB, KLUN)
CALL SAVE_TVETA (SELF%YRVETA, KLUN)
CALL SAVE_TVFE (SELF%YRVFE, KLUN)
CALL SAVE_TCVER (SELF%YRCVER, KLUN)
END SUBROUTINE

SUBROUTINE LOAD_TVERTICAL_GEOM (SELF, KLUN)
USE UTIL_TCVER_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD

IMPLICIT NONE
TYPE (TVERTICAL_GEOM), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%LNONHYD_GEOM
CALL LOAD_TVAB (SELF%YRVAB, KLUN)
CALL LOAD_TVETA (SELF%YRVETA, KLUN)
CALL LOAD_TVFE (SELF%YRVFE, KLUN)
CALL LOAD_TCVER (SELF%YRCVER, KLUN)
END SUBROUTINE


SUBROUTINE COPY_TVERTICAL_GEOM (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_TCVER_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD
IMPLICIT NONE
TYPE (TVERTICAL_GEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

CALL COPY_TVAB (SELF%YRVAB, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TVETA (SELF%YRVETA, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TVFE (SELF%YRVFE, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TCVER (SELF%YRCVER, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE



     



SUBROUTINE WIPE_TVERTICAL_GEOM (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_TCVER_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD
IMPLICIT NONE
TYPE (TVERTICAL_GEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

CALL WIPE_TVAB (SELF%YRVAB, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TVETA (SELF%YRVETA, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TVFE (SELF%YRVFE, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TCVER (SELF%YRCVER, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
