MODULE UTIL_TDYN_MOD

USE YOMDYN, ONLY : TDYN

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDYN
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDYN
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDYN
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDYN
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TDYN (SELF, KLUN)
USE UTIL_TSWE_MOD
IMPLICIT NONE
TYPE (TDYN), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHIDIV, LRDHIGFL, LRDHINHX, LRDHIP, LRDHISPD, LRDHISVD
LOGICAL :: LRDHIT, LRDHIVOR, LRDHS, LRDHSDIV, LRDHSNHX, LRDHSSVD, LRDHSVOR, LRDIDIV, LRDIGFL, LRDIPD
LOGICAL :: LRDISP, LRDITG, LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRGAMMA_WENO, LRGWFRIC, LRKRF
LOGICAL :: LRNHHY_DELTAM, LRSAVEDP, LSIALPH, LSIALPH_NH, LSIB, LSIBI, LSIBQ, LSIBQTRA, LSIDELP, LSIDELP_NH
LOGICAL :: LSIDPHI, LSIDPHI_NH, LSIFAC, LSIFACI, LSIFACITRA, LSIGFL, LSIGFM, LSIGHL, LSIGHM, LSIHEG
LOGICAL :: LSIHEG2, LSIHEG2TRA, LSIHEGB, LSIHEGB2, LSIHEGB2TRA, LSIHEGBTRA, LSIHEGIND, LSIHEGTRA, LSILNPR, LSILNPR_NH
LOGICAL :: LSIMI, LSIMITRA, LSIMO, LSIMOTRA, LSIPIS, LSIRDEL, LSIRDEL_NH, LSITAC, LSITFL, LSITFM
LOGICAL :: LSITGR, LSITLAF, LSITLAF_NH, LSITLAH, LSITLAH_NH, LSITRAM, LSITRM, LSIVP, LSIWF2H, LSIWH2F
LOGICAL :: LSIZA, LSIZC, LSLHD_MASK_T, LSLHD_MASK_U
WRITE (KLUN) SELF%REPS1
WRITE (KLUN) SELF%REPS2
WRITE (KLUN) SELF%REPSM1
WRITE (KLUN) SELF%REPSM2
WRITE (KLUN) SELF%REPSP1
WRITE (KLUN) SELF%HDIRVOR
WRITE (KLUN) SELF%HDIRDIV
WRITE (KLUN) SELF%HDIRT
WRITE (KLUN) SELF%HDIRQ
WRITE (KLUN) SELF%HDIRO3
WRITE (KLUN) SELF%HDIRPD
WRITE (KLUN) SELF%HDIRVD
WRITE (KLUN) SELF%HDIRSP
WRITE (KLUN) SELF%HRDIRVOR
WRITE (KLUN) SELF%HRDIRDIV
WRITE (KLUN) SELF%HRDIRT
WRITE (KLUN) SELF%HRDIRQ
WRITE (KLUN) SELF%HRDIRO3
WRITE (KLUN) SELF%HRDIRPD
WRITE (KLUN) SELF%HRDIRVD
WRITE (KLUN) SELF%HRDIRSP
WRITE (KLUN) SELF%RRDXTAU
WRITE (KLUN) SELF%RDAMPVOR
WRITE (KLUN) SELF%RDAMPDIV
WRITE (KLUN) SELF%RDAMPT
WRITE (KLUN) SELF%RDAMPQ
WRITE (KLUN) SELF%RDAMPO3
WRITE (KLUN) SELF%RDAMPPD
WRITE (KLUN) SELF%RDAMPVD
WRITE (KLUN) SELF%RDAMPSP
WRITE (KLUN) SELF%LNEWHD
WRITE (KLUN) SELF%REXPDH
WRITE (KLUN) SELF%FRANDH
WRITE (KLUN) SELF%SLEVDH
WRITE (KLUN) SELF%SLEVDH1
WRITE (KLUN) SELF%SLEVDH2
WRITE (KLUN) SELF%SLEVDH3
WRITE (KLUN) SELF%NSREFDH
WRITE (KLUN) SELF%RATIO_HDI_TOP
WRITE (KLUN) SELF%NPROFILEHD
WRITE (KLUN) SELF%RPROFHDBT
WRITE (KLUN) SELF%RPROFHDTP
WRITE (KLUN) SELF%RPROFHDMX
WRITE (KLUN) SELF%RPROFHDEX
WRITE (KLUN) SELF%LRDISPE_EC
LRDIVOR = ALLOCATED (SELF%RDIVOR)
WRITE (KLUN) LRDIVOR
IF (LRDIVOR) THEN
  WRITE (KLUN) LBOUND (SELF%RDIVOR)
  WRITE (KLUN) UBOUND (SELF%RDIVOR)
  WRITE (KLUN) SELF%RDIVOR
ENDIF
LRDIDIV = ALLOCATED (SELF%RDIDIV)
WRITE (KLUN) LRDIDIV
IF (LRDIDIV) THEN
  WRITE (KLUN) LBOUND (SELF%RDIDIV)
  WRITE (KLUN) UBOUND (SELF%RDIDIV)
  WRITE (KLUN) SELF%RDIDIV
ENDIF
LRDITG = ALLOCATED (SELF%RDITG)
WRITE (KLUN) LRDITG
IF (LRDITG) THEN
  WRITE (KLUN) LBOUND (SELF%RDITG)
  WRITE (KLUN) UBOUND (SELF%RDITG)
  WRITE (KLUN) SELF%RDITG
ENDIF
LRDIGFL = ALLOCATED (SELF%RDIGFL)
WRITE (KLUN) LRDIGFL
IF (LRDIGFL) THEN
  WRITE (KLUN) LBOUND (SELF%RDIGFL)
  WRITE (KLUN) UBOUND (SELF%RDIGFL)
  WRITE (KLUN) SELF%RDIGFL
ENDIF
LRDIPD = ALLOCATED (SELF%RDIPD)
WRITE (KLUN) LRDIPD
IF (LRDIPD) THEN
  WRITE (KLUN) LBOUND (SELF%RDIPD)
  WRITE (KLUN) UBOUND (SELF%RDIPD)
  WRITE (KLUN) SELF%RDIPD
ENDIF
LRDIVD = ALLOCATED (SELF%RDIVD)
WRITE (KLUN) LRDIVD
IF (LRDIVD) THEN
  WRITE (KLUN) LBOUND (SELF%RDIVD)
  WRITE (KLUN) UBOUND (SELF%RDIVD)
  WRITE (KLUN) SELF%RDIVD
ENDIF
LRDISP = ALLOCATED (SELF%RDISP)
WRITE (KLUN) LRDISP
IF (LRDISP) THEN
  WRITE (KLUN) LBOUND (SELF%RDISP)
  WRITE (KLUN) UBOUND (SELF%RDISP)
  WRITE (KLUN) SELF%RDISP
ENDIF
LRDHI = ALLOCATED (SELF%RDHI)
WRITE (KLUN) LRDHI
IF (LRDHI) THEN
  WRITE (KLUN) LBOUND (SELF%RDHI)
  WRITE (KLUN) UBOUND (SELF%RDHI)
  WRITE (KLUN) SELF%RDHI
ENDIF
LRDHIVOR = ALLOCATED (SELF%RDHIVOR)
WRITE (KLUN) LRDHIVOR
IF (LRDHIVOR) THEN
  WRITE (KLUN) LBOUND (SELF%RDHIVOR)
  WRITE (KLUN) UBOUND (SELF%RDHIVOR)
  WRITE (KLUN) SELF%RDHIVOR
ENDIF
LRDHIDIV = ALLOCATED (SELF%RDHIDIV)
WRITE (KLUN) LRDHIDIV
IF (LRDHIDIV) THEN
  WRITE (KLUN) LBOUND (SELF%RDHIDIV)
  WRITE (KLUN) UBOUND (SELF%RDHIDIV)
  WRITE (KLUN) SELF%RDHIDIV
ENDIF
LRDHISPD = ALLOCATED (SELF%RDHISPD)
WRITE (KLUN) LRDHISPD
IF (LRDHISPD) THEN
  WRITE (KLUN) LBOUND (SELF%RDHISPD)
  WRITE (KLUN) UBOUND (SELF%RDHISPD)
  WRITE (KLUN) SELF%RDHISPD
ENDIF
LRDHISVD = ALLOCATED (SELF%RDHISVD)
WRITE (KLUN) LRDHISVD
IF (LRDHISVD) THEN
  WRITE (KLUN) LBOUND (SELF%RDHISVD)
  WRITE (KLUN) UBOUND (SELF%RDHISVD)
  WRITE (KLUN) SELF%RDHISVD
ENDIF
LRDHINHX = ALLOCATED (SELF%RDHINHX)
WRITE (KLUN) LRDHINHX
IF (LRDHINHX) THEN
  WRITE (KLUN) LBOUND (SELF%RDHINHX)
  WRITE (KLUN) UBOUND (SELF%RDHINHX)
  WRITE (KLUN) SELF%RDHINHX
ENDIF
LRDHIT = ALLOCATED (SELF%RDHIT)
WRITE (KLUN) LRDHIT
IF (LRDHIT) THEN
  WRITE (KLUN) LBOUND (SELF%RDHIT)
  WRITE (KLUN) UBOUND (SELF%RDHIT)
  WRITE (KLUN) SELF%RDHIT
ENDIF
LRDHIGFL = ALLOCATED (SELF%RDHIGFL)
WRITE (KLUN) LRDHIGFL
IF (LRDHIGFL) THEN
  WRITE (KLUN) LBOUND (SELF%RDHIGFL)
  WRITE (KLUN) UBOUND (SELF%RDHIGFL)
  WRITE (KLUN) SELF%RDHIGFL
ENDIF
LRDHIP = ALLOCATED (SELF%RDHIP)
WRITE (KLUN) LRDHIP
IF (LRDHIP) THEN
  WRITE (KLUN) LBOUND (SELF%RDHIP)
  WRITE (KLUN) UBOUND (SELF%RDHIP)
  WRITE (KLUN) SELF%RDHIP
ENDIF
LRDHSVOR = ALLOCATED (SELF%RDHSVOR)
WRITE (KLUN) LRDHSVOR
IF (LRDHSVOR) THEN
  WRITE (KLUN) LBOUND (SELF%RDHSVOR)
  WRITE (KLUN) UBOUND (SELF%RDHSVOR)
  WRITE (KLUN) SELF%RDHSVOR
ENDIF
LRDHSDIV = ALLOCATED (SELF%RDHSDIV)
WRITE (KLUN) LRDHSDIV
IF (LRDHSDIV) THEN
  WRITE (KLUN) LBOUND (SELF%RDHSDIV)
  WRITE (KLUN) UBOUND (SELF%RDHSDIV)
  WRITE (KLUN) SELF%RDHSDIV
ENDIF
LRDHSSVD = ALLOCATED (SELF%RDHSSVD)
WRITE (KLUN) LRDHSSVD
IF (LRDHSSVD) THEN
  WRITE (KLUN) LBOUND (SELF%RDHSSVD)
  WRITE (KLUN) UBOUND (SELF%RDHSSVD)
  WRITE (KLUN) SELF%RDHSSVD
ENDIF
LRDHSNHX = ALLOCATED (SELF%RDHSNHX)
WRITE (KLUN) LRDHSNHX
IF (LRDHSNHX) THEN
  WRITE (KLUN) LBOUND (SELF%RDHSNHX)
  WRITE (KLUN) UBOUND (SELF%RDHSNHX)
  WRITE (KLUN) SELF%RDHSNHX
ENDIF
WRITE (KLUN) SELF%LSTRHD
WRITE (KLUN) SELF%HDTIME_STRHD
WRITE (KLUN) SELF%KLSPONGE
WRITE (KLUN) SELF%LM0DAMP
WRITE (KLUN) SELF%RBEGSPONGE
WRITE (KLUN) SELF%LTOP_VOR
WRITE (KLUN) SELF%NTOP_VOR_TRUNC
WRITE (KLUN) SELF%NTOP_VOR_BOT
LRSAVEDP = ALLOCATED (SELF%RSAVEDP)
WRITE (KLUN) LRSAVEDP
IF (LRSAVEDP) THEN
  WRITE (KLUN) LBOUND (SELF%RSAVEDP)
  WRITE (KLUN) UBOUND (SELF%RSAVEDP)
  WRITE (KLUN) SELF%RSAVEDP
ENDIF
WRITE (KLUN) SELF%SLHDA0
WRITE (KLUN) SELF%SLHDA0T
WRITE (KLUN) SELF%SLHDB
WRITE (KLUN) SELF%SLHDBT
WRITE (KLUN) SELF%SLHDD00
WRITE (KLUN) SELF%SLHDD00T
WRITE (KLUN) SELF%SLHDDIV
WRITE (KLUN) SELF%SLHDRATDDIV
WRITE (KLUN) SELF%SLHDHOR
WRITE (KLUN) SELF%SLHD_P_LOW
WRITE (KLUN) SELF%SLHD_P_HIGH
WRITE (KLUN) SELF%LSLHDHEAT
WRITE (KLUN) SELF%LSLHDSPONGE
WRITE (KLUN) SELF%HDSRVOR
WRITE (KLUN) SELF%HDSRDIV
WRITE (KLUN) SELF%HDSRVD
WRITE (KLUN) SELF%HRDSRVOR
WRITE (KLUN) SELF%HRDSRDIV
WRITE (KLUN) SELF%HRDSRVD
WRITE (KLUN) SELF%RDAMPVORS
WRITE (KLUN) SELF%RDAMPDIVS
WRITE (KLUN) SELF%RDAMPVDS
WRITE (KLUN) SELF%RDAMPHDS
WRITE (KLUN) SELF%REXPDHS
WRITE (KLUN) SELF%SLEVDHS
WRITE (KLUN) SELF%SLEVDHS1
WRITE (KLUN) SELF%SLEVDHS2
WRITE (KLUN) SELF%SDRED
LRDSVOR = ALLOCATED (SELF%RDSVOR)
WRITE (KLUN) LRDSVOR
IF (LRDSVOR) THEN
  WRITE (KLUN) LBOUND (SELF%RDSVOR)
  WRITE (KLUN) UBOUND (SELF%RDSVOR)
  WRITE (KLUN) SELF%RDSVOR
ENDIF
LRDSDIV = ALLOCATED (SELF%RDSDIV)
WRITE (KLUN) LRDSDIV
IF (LRDSDIV) THEN
  WRITE (KLUN) LBOUND (SELF%RDSDIV)
  WRITE (KLUN) UBOUND (SELF%RDSDIV)
  WRITE (KLUN) SELF%RDSDIV
ENDIF
LRDSVD = ALLOCATED (SELF%RDSVD)
WRITE (KLUN) LRDSVD
IF (LRDSVD) THEN
  WRITE (KLUN) LBOUND (SELF%RDSVD)
  WRITE (KLUN) UBOUND (SELF%RDSVD)
  WRITE (KLUN) SELF%RDSVD
ENDIF
LRDHS = ALLOCATED (SELF%RDHS)
WRITE (KLUN) LRDHS
IF (LRDHS) THEN
  WRITE (KLUN) LBOUND (SELF%RDHS)
  WRITE (KLUN) UBOUND (SELF%RDHS)
  WRITE (KLUN) SELF%RDHS
ENDIF
LSLHD_MASK_U = ALLOCATED (SELF%SLHD_MASK_U)
WRITE (KLUN) LSLHD_MASK_U
IF (LSLHD_MASK_U) THEN
  WRITE (KLUN) LBOUND (SELF%SLHD_MASK_U)
  WRITE (KLUN) UBOUND (SELF%SLHD_MASK_U)
  WRITE (KLUN) SELF%SLHD_MASK_U
ENDIF
LSLHD_MASK_T = ALLOCATED (SELF%SLHD_MASK_T)
WRITE (KLUN) LSLHD_MASK_T
IF (LSLHD_MASK_T) THEN
  WRITE (KLUN) LBOUND (SELF%SLHD_MASK_T)
  WRITE (KLUN) UBOUND (SELF%SLHD_MASK_T)
  WRITE (KLUN) SELF%SLHD_MASK_T
ENDIF
WRITE (KLUN) SELF%ZSLHDP1
WRITE (KLUN) SELF%ZSLHDP3
WRITE (KLUN) SELF%NLEV_SPONGE
WRITE (KLUN) SELF%LRFRIC
WRITE (KLUN) SELF%LRFRICISOTR
LRCORDIT = ALLOCATED (SELF%RCORDIT)
WRITE (KLUN) LRCORDIT
IF (LRCORDIT) THEN
  WRITE (KLUN) LBOUND (SELF%RCORDIT)
  WRITE (KLUN) UBOUND (SELF%RCORDIT)
  WRITE (KLUN) SELF%RCORDIT
ENDIF
LRCORDIH = ALLOCATED (SELF%RCORDIH)
WRITE (KLUN) LRCORDIH
IF (LRCORDIH) THEN
  WRITE (KLUN) LBOUND (SELF%RCORDIH)
  WRITE (KLUN) UBOUND (SELF%RCORDIH)
  WRITE (KLUN) SELF%RCORDIH
ENDIF
LRCORDIF = ALLOCATED (SELF%RCORDIF)
WRITE (KLUN) LRCORDIF
IF (LRCORDIF) THEN
  WRITE (KLUN) LBOUND (SELF%RCORDIF)
  WRITE (KLUN) UBOUND (SELF%RCORDIF)
  WRITE (KLUN) SELF%RCORDIF
ENDIF
WRITE (KLUN) SELF%VMAX1
WRITE (KLUN) SELF%VMAX2
WRITE (KLUN) SELF%RMAX_D3
WRITE (KLUN) SELF%LBOUND_D3
LRKRF = ALLOCATED (SELF%RKRF)
WRITE (KLUN) LRKRF
IF (LRKRF) THEN
  WRITE (KLUN) LBOUND (SELF%RKRF)
  WRITE (KLUN) UBOUND (SELF%RKRF)
  WRITE (KLUN) SELF%RKRF
ENDIF
WRITE (KLUN) SELF%NMAXLEVRF
WRITE (KLUN) SELF%RRFZ1
WRITE (KLUN) SELF%RRFPLM
WRITE (KLUN) SELF%RRFTAU
WRITE (KLUN) SELF%RTEMRB
WRITE (KLUN) SELF%NRUBC
WRITE (KLUN) SELF%LGWFRIC
WRITE (KLUN) SELF%NLEV_GWFRIC
WRITE (KLUN) SELF%RGWFRIC_MAX
WRITE (KLUN) SELF%RGWFRIC_PLM
LRGWFRIC = ALLOCATED (SELF%RGWFRIC)
WRITE (KLUN) LRGWFRIC
IF (LRGWFRIC) THEN
  WRITE (KLUN) LBOUND (SELF%RGWFRIC)
  WRITE (KLUN) UBOUND (SELF%RGWFRIC)
  WRITE (KLUN) SELF%RGWFRIC
ENDIF
WRITE (KLUN) SELF%LSIDG
WRITE (KLUN) SELF%LDYN_STABAN
WRITE (KLUN) SELF%LRHDI_LASTITERPC
WRITE (KLUN) SELF%LSIDYN_VERBOSE
WRITE (KLUN) SELF%BETADT
WRITE (KLUN) SELF%RBT
WRITE (KLUN) SELF%RBTS2
WRITE (KLUN) SELF%REFGEO
WRITE (KLUN) SELF%SIPR
WRITE (KLUN) SELF%SIPRA
WRITE (KLUN) SELF%SITR
WRITE (KLUN) SELF%SITRA
WRITE (KLUN) SELF%SITRUB
WRITE (KLUN) SELF%SIPRUB
WRITE (KLUN) SELF%SITIME
WRITE (KLUN) SELF%SIRPRG
WRITE (KLUN) SELF%SIRPRN
WRITE (KLUN) SELF%SISLP
WRITE (KLUN) SELF%SIFRG
WRITE (KLUN) SELF%SIFRA
WRITE (KLUN) SELF%SITVAR
WRITE (KLUN) SELF%NSITER
WRITE (KLUN) SELF%NCURRENT_ITER
WRITE (KLUN) SELF%NITERHELM
WRITE (KLUN) SELF%NOPT_SITR
WRITE (KLUN) SELF%NOPT_SIPR
WRITE (KLUN) SELF%NOPT_SISLP
LSITRAM = ALLOCATED (SELF%SITRAM)
WRITE (KLUN) LSITRAM
IF (LSITRAM) THEN
  WRITE (KLUN) LBOUND (SELF%SITRAM)
  WRITE (KLUN) UBOUND (SELF%SITRAM)
  WRITE (KLUN) SELF%SITRAM
ENDIF
LSITRM = ALLOCATED (SELF%SITRM)
WRITE (KLUN) LSITRM
IF (LSITRM) THEN
  WRITE (KLUN) LBOUND (SELF%SITRM)
  WRITE (KLUN) UBOUND (SELF%SITRM)
  WRITE (KLUN) SELF%SITRM
ENDIF
LSIALPH = ALLOCATED (SELF%SIALPH)
WRITE (KLUN) LSIALPH
IF (LSIALPH) THEN
  WRITE (KLUN) LBOUND (SELF%SIALPH)
  WRITE (KLUN) UBOUND (SELF%SIALPH)
  WRITE (KLUN) SELF%SIALPH
ENDIF
LSILNPR = ALLOCATED (SELF%SILNPR)
WRITE (KLUN) LSILNPR
IF (LSILNPR) THEN
  WRITE (KLUN) LBOUND (SELF%SILNPR)
  WRITE (KLUN) UBOUND (SELF%SILNPR)
  WRITE (KLUN) SELF%SILNPR
ENDIF
LSIDELP = ALLOCATED (SELF%SIDELP)
WRITE (KLUN) LSIDELP
IF (LSIDELP) THEN
  WRITE (KLUN) LBOUND (SELF%SIDELP)
  WRITE (KLUN) UBOUND (SELF%SIDELP)
  WRITE (KLUN) SELF%SIDELP
ENDIF
LSIRDEL = ALLOCATED (SELF%SIRDEL)
WRITE (KLUN) LSIRDEL
IF (LSIRDEL) THEN
  WRITE (KLUN) LBOUND (SELF%SIRDEL)
  WRITE (KLUN) UBOUND (SELF%SIRDEL)
  WRITE (KLUN) SELF%SIRDEL
ENDIF
LSITLAH = ALLOCATED (SELF%SITLAH)
WRITE (KLUN) LSITLAH
IF (LSITLAH) THEN
  WRITE (KLUN) LBOUND (SELF%SITLAH)
  WRITE (KLUN) UBOUND (SELF%SITLAH)
  WRITE (KLUN) SELF%SITLAH
ENDIF
LSITLAF = ALLOCATED (SELF%SITLAF)
WRITE (KLUN) LSITLAF
IF (LSITLAF) THEN
  WRITE (KLUN) LBOUND (SELF%SITLAF)
  WRITE (KLUN) UBOUND (SELF%SITLAF)
  WRITE (KLUN) SELF%SITLAF
ENDIF
LSIDPHI = ALLOCATED (SELF%SIDPHI)
WRITE (KLUN) LSIDPHI
IF (LSIDPHI) THEN
  WRITE (KLUN) LBOUND (SELF%SIDPHI)
  WRITE (KLUN) UBOUND (SELF%SIDPHI)
  WRITE (KLUN) SELF%SIDPHI
ENDIF
LSIALPH_NH = ALLOCATED (SELF%SIALPH_NH)
WRITE (KLUN) LSIALPH_NH
IF (LSIALPH_NH) THEN
  WRITE (KLUN) LBOUND (SELF%SIALPH_NH)
  WRITE (KLUN) UBOUND (SELF%SIALPH_NH)
  WRITE (KLUN) SELF%SIALPH_NH
ENDIF
LSILNPR_NH = ALLOCATED (SELF%SILNPR_NH)
WRITE (KLUN) LSILNPR_NH
IF (LSILNPR_NH) THEN
  WRITE (KLUN) LBOUND (SELF%SILNPR_NH)
  WRITE (KLUN) UBOUND (SELF%SILNPR_NH)
  WRITE (KLUN) SELF%SILNPR_NH
ENDIF
LSIDELP_NH = ALLOCATED (SELF%SIDELP_NH)
WRITE (KLUN) LSIDELP_NH
IF (LSIDELP_NH) THEN
  WRITE (KLUN) LBOUND (SELF%SIDELP_NH)
  WRITE (KLUN) UBOUND (SELF%SIDELP_NH)
  WRITE (KLUN) SELF%SIDELP_NH
ENDIF
LSIRDEL_NH = ALLOCATED (SELF%SIRDEL_NH)
WRITE (KLUN) LSIRDEL_NH
IF (LSIRDEL_NH) THEN
  WRITE (KLUN) LBOUND (SELF%SIRDEL_NH)
  WRITE (KLUN) UBOUND (SELF%SIRDEL_NH)
  WRITE (KLUN) SELF%SIRDEL_NH
ENDIF
LSITLAH_NH = ALLOCATED (SELF%SITLAH_NH)
WRITE (KLUN) LSITLAH_NH
IF (LSITLAH_NH) THEN
  WRITE (KLUN) LBOUND (SELF%SITLAH_NH)
  WRITE (KLUN) UBOUND (SELF%SITLAH_NH)
  WRITE (KLUN) SELF%SITLAH_NH
ENDIF
LSITLAF_NH = ALLOCATED (SELF%SITLAF_NH)
WRITE (KLUN) LSITLAF_NH
IF (LSITLAF_NH) THEN
  WRITE (KLUN) LBOUND (SELF%SITLAF_NH)
  WRITE (KLUN) UBOUND (SELF%SITLAF_NH)
  WRITE (KLUN) SELF%SITLAF_NH
ENDIF
LSIDPHI_NH = ALLOCATED (SELF%SIDPHI_NH)
WRITE (KLUN) LSIDPHI_NH
IF (LSIDPHI_NH) THEN
  WRITE (KLUN) LBOUND (SELF%SIDPHI_NH)
  WRITE (KLUN) UBOUND (SELF%SIDPHI_NH)
  WRITE (KLUN) SELF%SIDPHI_NH
ENDIF
LSIWF2H = ALLOCATED (SELF%SIWF2H)
WRITE (KLUN) LSIWF2H
IF (LSIWF2H) THEN
  WRITE (KLUN) LBOUND (SELF%SIWF2H)
  WRITE (KLUN) UBOUND (SELF%SIWF2H)
  WRITE (KLUN) SELF%SIWF2H
ENDIF
LSIWH2F = ALLOCATED (SELF%SIWH2F)
WRITE (KLUN) LSIWH2F
IF (LSIWH2F) THEN
  WRITE (KLUN) LBOUND (SELF%SIWH2F)
  WRITE (KLUN) UBOUND (SELF%SIWH2F)
  WRITE (KLUN) SELF%SIWH2F
ENDIF
LSIGFL = ALLOCATED (SELF%SIGFL)
WRITE (KLUN) LSIGFL
IF (LSIGFL) THEN
  WRITE (KLUN) LBOUND (SELF%SIGFL)
  WRITE (KLUN) UBOUND (SELF%SIGFL)
  WRITE (KLUN) SELF%SIGFL
ENDIF
LSIGFM = ALLOCATED (SELF%SIGFM)
WRITE (KLUN) LSIGFM
IF (LSIGFM) THEN
  WRITE (KLUN) LBOUND (SELF%SIGFM)
  WRITE (KLUN) UBOUND (SELF%SIGFM)
  WRITE (KLUN) SELF%SIGFM
ENDIF
LSITFL = ALLOCATED (SELF%SITFL)
WRITE (KLUN) LSITFL
IF (LSITFL) THEN
  WRITE (KLUN) LBOUND (SELF%SITFL)
  WRITE (KLUN) UBOUND (SELF%SITFL)
  WRITE (KLUN) SELF%SITFL
ENDIF
LSITFM = ALLOCATED (SELF%SITFM)
WRITE (KLUN) LSITFM
IF (LSITFM) THEN
  WRITE (KLUN) LBOUND (SELF%SITFM)
  WRITE (KLUN) UBOUND (SELF%SITFM)
  WRITE (KLUN) SELF%SITFM
ENDIF
LSIGHL = ALLOCATED (SELF%SIGHL)
WRITE (KLUN) LSIGHL
IF (LSIGHL) THEN
  WRITE (KLUN) LBOUND (SELF%SIGHL)
  WRITE (KLUN) UBOUND (SELF%SIGHL)
  WRITE (KLUN) SELF%SIGHL
ENDIF
LSIGHM = ALLOCATED (SELF%SIGHM)
WRITE (KLUN) LSIGHM
IF (LSIGHM) THEN
  WRITE (KLUN) LBOUND (SELF%SIGHM)
  WRITE (KLUN) UBOUND (SELF%SIGHM)
  WRITE (KLUN) SELF%SIGHM
ENDIF
LSIB = ALLOCATED (SELF%SIB)
WRITE (KLUN) LSIB
IF (LSIB) THEN
  WRITE (KLUN) LBOUND (SELF%SIB)
  WRITE (KLUN) UBOUND (SELF%SIB)
  WRITE (KLUN) SELF%SIB
ENDIF
LSIMO = ALLOCATED (SELF%SIMO)
WRITE (KLUN) LSIMO
IF (LSIMO) THEN
  WRITE (KLUN) LBOUND (SELF%SIMO)
  WRITE (KLUN) UBOUND (SELF%SIMO)
  WRITE (KLUN) SELF%SIMO
ENDIF
LSIMI = ALLOCATED (SELF%SIMI)
WRITE (KLUN) LSIMI
IF (LSIMI) THEN
  WRITE (KLUN) LBOUND (SELF%SIMI)
  WRITE (KLUN) UBOUND (SELF%SIMI)
  WRITE (KLUN) SELF%SIMI
ENDIF
LSIVP = ALLOCATED (SELF%SIVP)
WRITE (KLUN) LSIVP
IF (LSIVP) THEN
  WRITE (KLUN) LBOUND (SELF%SIVP)
  WRITE (KLUN) UBOUND (SELF%SIVP)
  WRITE (KLUN) SELF%SIVP
ENDIF
LSIHEG = ALLOCATED (SELF%SIHEG)
WRITE (KLUN) LSIHEG
IF (LSIHEG) THEN
  WRITE (KLUN) LBOUND (SELF%SIHEG)
  WRITE (KLUN) UBOUND (SELF%SIHEG)
  WRITE (KLUN) SELF%SIHEG
ENDIF
LSIHEG2 = ALLOCATED (SELF%SIHEG2)
WRITE (KLUN) LSIHEG2
IF (LSIHEG2) THEN
  WRITE (KLUN) LBOUND (SELF%SIHEG2)
  WRITE (KLUN) UBOUND (SELF%SIHEG2)
  WRITE (KLUN) SELF%SIHEG2
ENDIF
LSIHEGB = ALLOCATED (SELF%SIHEGB)
WRITE (KLUN) LSIHEGB
IF (LSIHEGB) THEN
  WRITE (KLUN) LBOUND (SELF%SIHEGB)
  WRITE (KLUN) UBOUND (SELF%SIHEGB)
  WRITE (KLUN) SELF%SIHEGB
ENDIF
LSIHEGB2 = ALLOCATED (SELF%SIHEGB2)
WRITE (KLUN) LSIHEGB2
IF (LSIHEGB2) THEN
  WRITE (KLUN) LBOUND (SELF%SIHEGB2)
  WRITE (KLUN) UBOUND (SELF%SIHEGB2)
  WRITE (KLUN) SELF%SIHEGB2
ENDIF
LSIFAC = ALLOCATED (SELF%SIFAC)
WRITE (KLUN) LSIFAC
IF (LSIFAC) THEN
  WRITE (KLUN) LBOUND (SELF%SIFAC)
  WRITE (KLUN) UBOUND (SELF%SIFAC)
  WRITE (KLUN) SELF%SIFAC
ENDIF
LSIFACI = ALLOCATED (SELF%SIFACI)
WRITE (KLUN) LSIFACI
IF (LSIFACI) THEN
  WRITE (KLUN) LBOUND (SELF%SIFACI)
  WRITE (KLUN) UBOUND (SELF%SIFACI)
  WRITE (KLUN) SELF%SIFACI
ENDIF
LSIBQ = ALLOCATED (SELF%SIBQ)
WRITE (KLUN) LSIBQ
IF (LSIBQ) THEN
  WRITE (KLUN) LBOUND (SELF%SIBQ)
  WRITE (KLUN) UBOUND (SELF%SIBQ)
  WRITE (KLUN) SELF%SIBQ
ENDIF
LSIMITRA = ALLOCATED (SELF%SIMITRA)
WRITE (KLUN) LSIMITRA
IF (LSIMITRA) THEN
  WRITE (KLUN) LBOUND (SELF%SIMITRA)
  WRITE (KLUN) UBOUND (SELF%SIMITRA)
  WRITE (KLUN) SELF%SIMITRA
ENDIF
LSIMOTRA = ALLOCATED (SELF%SIMOTRA)
WRITE (KLUN) LSIMOTRA
IF (LSIMOTRA) THEN
  WRITE (KLUN) LBOUND (SELF%SIMOTRA)
  WRITE (KLUN) UBOUND (SELF%SIMOTRA)
  WRITE (KLUN) SELF%SIMOTRA
ENDIF
LSIFACITRA = ALLOCATED (SELF%SIFACITRA)
WRITE (KLUN) LSIFACITRA
IF (LSIFACITRA) THEN
  WRITE (KLUN) LBOUND (SELF%SIFACITRA)
  WRITE (KLUN) UBOUND (SELF%SIFACITRA)
  WRITE (KLUN) SELF%SIFACITRA
ENDIF
LSIHEGTRA = ALLOCATED (SELF%SIHEGTRA)
WRITE (KLUN) LSIHEGTRA
IF (LSIHEGTRA) THEN
  WRITE (KLUN) LBOUND (SELF%SIHEGTRA)
  WRITE (KLUN) UBOUND (SELF%SIHEGTRA)
  WRITE (KLUN) SELF%SIHEGTRA
ENDIF
LSIHEG2TRA = ALLOCATED (SELF%SIHEG2TRA)
WRITE (KLUN) LSIHEG2TRA
IF (LSIHEG2TRA) THEN
  WRITE (KLUN) LBOUND (SELF%SIHEG2TRA)
  WRITE (KLUN) UBOUND (SELF%SIHEG2TRA)
  WRITE (KLUN) SELF%SIHEG2TRA
ENDIF
LSIHEGBTRA = ALLOCATED (SELF%SIHEGBTRA)
WRITE (KLUN) LSIHEGBTRA
IF (LSIHEGBTRA) THEN
  WRITE (KLUN) LBOUND (SELF%SIHEGBTRA)
  WRITE (KLUN) UBOUND (SELF%SIHEGBTRA)
  WRITE (KLUN) SELF%SIHEGBTRA
ENDIF
LSIHEGB2TRA = ALLOCATED (SELF%SIHEGB2TRA)
WRITE (KLUN) LSIHEGB2TRA
IF (LSIHEGB2TRA) THEN
  WRITE (KLUN) LBOUND (SELF%SIHEGB2TRA)
  WRITE (KLUN) UBOUND (SELF%SIHEGB2TRA)
  WRITE (KLUN) SELF%SIHEGB2TRA
ENDIF
LSIHEGIND = ALLOCATED (SELF%SIHEGIND)
WRITE (KLUN) LSIHEGIND
IF (LSIHEGIND) THEN
  WRITE (KLUN) LBOUND (SELF%SIHEGIND)
  WRITE (KLUN) UBOUND (SELF%SIHEGIND)
  WRITE (KLUN) SELF%SIHEGIND
ENDIF
LSIBQTRA = ALLOCATED (SELF%SIBQTRA)
WRITE (KLUN) LSIBQTRA
IF (LSIBQTRA) THEN
  WRITE (KLUN) LBOUND (SELF%SIBQTRA)
  WRITE (KLUN) UBOUND (SELF%SIBQTRA)
  WRITE (KLUN) SELF%SIBQTRA
ENDIF
LSIZA = ALLOCATED (SELF%SIZA)
WRITE (KLUN) LSIZA
IF (LSIZA) THEN
  WRITE (KLUN) LBOUND (SELF%SIZA)
  WRITE (KLUN) UBOUND (SELF%SIZA)
  WRITE (KLUN) SELF%SIZA
ENDIF
LSIZC = ALLOCATED (SELF%SIZC)
WRITE (KLUN) LSIZC
IF (LSIZC) THEN
  WRITE (KLUN) LBOUND (SELF%SIZC)
  WRITE (KLUN) UBOUND (SELF%SIZC)
  WRITE (KLUN) SELF%SIZC
ENDIF
LSIPIS = ALLOCATED (SELF%SIPIS)
WRITE (KLUN) LSIPIS
IF (LSIPIS) THEN
  WRITE (KLUN) LBOUND (SELF%SIPIS)
  WRITE (KLUN) UBOUND (SELF%SIPIS)
  WRITE (KLUN) SELF%SIPIS
ENDIF
LSITGR = ALLOCATED (SELF%SITGR)
WRITE (KLUN) LSITGR
IF (LSITGR) THEN
  WRITE (KLUN) LBOUND (SELF%SITGR)
  WRITE (KLUN) UBOUND (SELF%SITGR)
  WRITE (KLUN) SELF%SITGR
ENDIF
LSITAC = ALLOCATED (SELF%SITAC)
WRITE (KLUN) LSITAC
IF (LSITAC) THEN
  WRITE (KLUN) LBOUND (SELF%SITAC)
  WRITE (KLUN) UBOUND (SELF%SITAC)
  WRITE (KLUN) SELF%SITAC
ENDIF
WRITE (KLUN) SELF%VNORM
WRITE (KLUN) SELF%SLOPE_MAX
WRITE (KLUN) SELF%PSURF_MAX
WRITE (KLUN) SELF%PSURF_MIN
WRITE (KLUN) SELF%NVLAG
WRITE (KLUN) SELF%NWLAG
WRITE (KLUN) SELF%NTLAG
WRITE (KLUN) SELF%NSPDLAG
WRITE (KLUN) SELF%NSVDLAG
WRITE (KLUN) SELF%NSPLTHOI
WRITE (KLUN) SELF%LSPLTHOIGFL
WRITE (KLUN) SELF%NSLDIMK
WRITE (KLUN) SELF%NITMP
WRITE (KLUN) SELF%VETAON
WRITE (KLUN) SELF%VETAOX
WRITE (KLUN) SELF%LSETTLSVF
WRITE (KLUN) SELF%LSETFSTAT
WRITE (KLUN) SELF%LSETTLSVF_DIFF
WRITE (KLUN) SELF%RW2TLFF
WRITE (KLUN) SELF%RALPHA
WRITE (KLUN) SELF%RALPHA_TOP
WRITE (KLUN) SELF%NLEV_ZALPHA
WRITE (KLUN) SELF%NEDER
WRITE (KLUN) SELF%RBETAK
WRITE (KLUN) SELF%LWENOBC
WRITE (KLUN) SELF%NQMHOISLT
WRITE (KLUN) SELF%LSLDP_RK
WRITE (KLUN) SELF%LSLDP_CURV
WRITE (KLUN) SELF%LSLDP_CURV_FIX
WRITE (KLUN) SELF%LRHS_CURV
WRITE (KLUN) SELF%LRHS_CURV_FIX
WRITE (KLUN) SELF%LSLDP_XYZ
WRITE (KLUN) SELF%LSLDP_SAVE
WRITE (KLUN) SELF%VESL
WRITE (KLUN) SELF%XIDT
WRITE (KLUN) SELF%LQMW
WRITE (KLUN) SELF%LQMHW
WRITE (KLUN) SELF%LQMT
WRITE (KLUN) SELF%LQMHT
WRITE (KLUN) SELF%LQMP
WRITE (KLUN) SELF%LQMHP
WRITE (KLUN) SELF%LQMPD
WRITE (KLUN) SELF%LQMHPD
WRITE (KLUN) SELF%LQMVD
WRITE (KLUN) SELF%LQMHVD
WRITE (KLUN) SELF%LVWENO_W
WRITE (KLUN) SELF%LVWENO_T
WRITE (KLUN) SELF%LVWENO_SP
WRITE (KLUN) SELF%LVWENO_SPD
WRITE (KLUN) SELF%LVWENO_SVD
WRITE (KLUN) SELF%WENO_ALPHA_W
WRITE (KLUN) SELF%WENO_ALPHA_T
WRITE (KLUN) SELF%WENO_ALPHA_SP
WRITE (KLUN) SELF%WENO_ALPHA_SPD
WRITE (KLUN) SELF%WENO_ALPHA_SVD
WRITE (KLUN) SELF%LADVF
WRITE (KLUN) SELF%LIMPF
WRITE (KLUN) SELF%L2TLFF
WRITE (KLUN) SELF%RCMSLP0
WRITE (KLUN) SELF%NCOMP_CVGQ
WRITE (KLUN) SELF%LSVTSM
WRITE (KLUN) SELF%RPRES_SVTSM
WRITE (KLUN) SELF%RPRES_SETTLSVF
WRITE (KLUN) SELF%NFLEVSF
WRITE (KLUN) SELF%RSCALE
WRITE (KLUN) SELF%RSCALEOFF
WRITE (KLUN) SELF%RINTOPT
WRITE (KLUN) SELF%RRINTOPT
WRITE (KLUN) SELF%LHDIFFM
WRITE (KLUN) SELF%LSPECVIS
WRITE (KLUN) SELF%NDIFFACT
WRITE (KLUN) SELF%LGPSTRESS
WRITE (KLUN) SELF%RCLSTRESS
WRITE (KLUN) SELF%RCLPOLE
WRITE (KLUN) SELF%NVSEPC
WRITE (KLUN) SELF%NVSEPL
WRITE (KLUN) SELF%LFINDVSEP
WRITE (KLUN) SELF%LMASCOR
WRITE (KLUN) SELF%LMASDRY
WRITE (KLUN) SELF%LGPMASCOR
WRITE (KLUN) SELF%NGPMASCOR
WRITE (KLUN) SELF%GPMASSI
WRITE (KLUN) SELF%GMASSI
WRITE (KLUN) SELF%GMASS0
WRITE (KLUN) SELF%GMASSINC
WRITE (KLUN) SELF%LNODRYFLX
LSIBI = ALLOCATED (SELF%SIBI)
WRITE (KLUN) LSIBI
IF (LSIBI) THEN
  WRITE (KLUN) LBOUND (SELF%SIBI)
  WRITE (KLUN) UBOUND (SELF%SIBI)
  WRITE (KLUN) SELF%SIBI
ENDIF
WRITE (KLUN) SELF%RESGP
WRITE (KLUN) SELF%RESGM
WRITE (KLUN) SELF%LNHHY_SOLVER_GP
WRITE (KLUN) SELF%LNHHY_SOLVER_SP
WRITE (KLUN) SELF%LNHQE_SOLVER_GP
WRITE (KLUN) SELF%LNHQE_SOLVER_SP
WRITE (KLUN) SELF%LRESET_BLEND_SI
WRITE (KLUN) SELF%NSTOP_BLEND
WRITE (KLUN) SELF%NSTART_BLEND
WRITE (KLUN) SELF%RNHQE_DELTAM
LRNHHY_DELTAM = ALLOCATED (SELF%RNHHY_DELTAM)
WRITE (KLUN) LRNHHY_DELTAM
IF (LRNHHY_DELTAM) THEN
  WRITE (KLUN) LBOUND (SELF%RNHHY_DELTAM)
  WRITE (KLUN) UBOUND (SELF%RNHHY_DELTAM)
  WRITE (KLUN) SELF%RNHHY_DELTAM
ENDIF
CALL SAVE_TSWE (SELF%YRSWE, KLUN)
WRITE (KLUN) SELF%CLAITRI_TYPE
WRITE (KLUN) SELF%CLAITRI_WENO_TYPE
LRGAMMA_WENO = ALLOCATED (SELF%RGAMMA_WENO)
WRITE (KLUN) LRGAMMA_WENO
IF (LRGAMMA_WENO) THEN
  WRITE (KLUN) LBOUND (SELF%RGAMMA_WENO)
  WRITE (KLUN) UBOUND (SELF%RGAMMA_WENO)
  WRITE (KLUN) SELF%RGAMMA_WENO
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TDYN (SELF, KLUN)
USE UTIL_TSWE_MOD
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
TYPE (TDYN), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHIDIV, LRDHIGFL, LRDHINHX, LRDHIP, LRDHISPD, LRDHISVD
LOGICAL :: LRDHIT, LRDHIVOR, LRDHS, LRDHSDIV, LRDHSNHX, LRDHSSVD, LRDHSVOR, LRDIDIV, LRDIGFL, LRDIPD
LOGICAL :: LRDISP, LRDITG, LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRGAMMA_WENO, LRGWFRIC, LRKRF
LOGICAL :: LRNHHY_DELTAM, LRSAVEDP, LSIALPH, LSIALPH_NH, LSIB, LSIBI, LSIBQ, LSIBQTRA, LSIDELP, LSIDELP_NH
LOGICAL :: LSIDPHI, LSIDPHI_NH, LSIFAC, LSIFACI, LSIFACITRA, LSIGFL, LSIGFM, LSIGHL, LSIGHM, LSIHEG
LOGICAL :: LSIHEG2, LSIHEG2TRA, LSIHEGB, LSIHEGB2, LSIHEGB2TRA, LSIHEGBTRA, LSIHEGIND, LSIHEGTRA, LSILNPR, LSILNPR_NH
LOGICAL :: LSIMI, LSIMITRA, LSIMO, LSIMOTRA, LSIPIS, LSIRDEL, LSIRDEL_NH, LSITAC, LSITFL, LSITFM
LOGICAL :: LSITGR, LSITLAF, LSITLAF_NH, LSITLAH, LSITLAH_NH, LSITRAM, LSITRM, LSIVP, LSIWF2H, LSIWH2F
LOGICAL :: LSIZA, LSIZC, LSLHD_MASK_T, LSLHD_MASK_U
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP4 (:,:,:,:)
READ (KLUN) ZTMP0
SELF%REPS1 = ZTMP0
READ (KLUN) ZTMP0
SELF%REPS2 = ZTMP0
READ (KLUN) ZTMP0
SELF%REPSM1 = ZTMP0
READ (KLUN) ZTMP0
SELF%REPSM2 = ZTMP0
READ (KLUN) ZTMP0
SELF%REPSP1 = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRVOR = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRT = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRQ = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRO3 = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRPD = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRVD = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRSP = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRVOR = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRT = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRQ = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRO3 = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRPD = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRVD = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRSP = ZTMP0
READ (KLUN) ZTMP0
SELF%RRDXTAU = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPVOR = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPT = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPQ = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPO3 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPPD = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPVD = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPSP = ZTMP0
READ (KLUN) SELF%LNEWHD
READ (KLUN) ZTMP0
SELF%REXPDH = ZTMP0
READ (KLUN) ZTMP0
SELF%FRANDH = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDH = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDH1 = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDH2 = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDH3 = ZTMP0
READ (KLUN) SELF%NSREFDH
READ (KLUN) ZTMP0
SELF%RATIO_HDI_TOP = ZTMP0
READ (KLUN) SELF%NPROFILEHD
READ (KLUN) ZTMP0
SELF%RPROFHDBT = ZTMP0
READ (KLUN) ZTMP0
SELF%RPROFHDTP = ZTMP0
READ (KLUN) ZTMP0
SELF%RPROFHDMX = ZTMP0
READ (KLUN) ZTMP0
SELF%RPROFHDEX = ZTMP0
READ (KLUN) SELF%LRDISPE_EC
READ (KLUN) LRDIVOR
IF (LRDIVOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDIVOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDIVOR,1):UBOUND(SELF%RDIVOR,1), LBOUND(SELF%RDIVOR,2):UBOUND(SELF%RDIVOR,2)))
  READ (KLUN) ZTMP2
  SELF%RDIVOR = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDIDIV
IF (LRDIDIV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDIDIV (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDIDIV,1):UBOUND(SELF%RDIDIV,1), LBOUND(SELF%RDIDIV,2):UBOUND(SELF%RDIDIV,2)))
  READ (KLUN) ZTMP2
  SELF%RDIDIV = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDITG
IF (LRDITG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDITG (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDITG,1):UBOUND(SELF%RDITG,1), LBOUND(SELF%RDITG,2):UBOUND(SELF%RDITG,2)))
  READ (KLUN) ZTMP2
  SELF%RDITG = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDIGFL
IF (LRDIGFL) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDIGFL (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDIGFL,1):UBOUND(SELF%RDIGFL,1), LBOUND(SELF%RDIGFL,2):UBOUND(SELF%RDIGFL,2), LBOUND(SELF%RDIGFL,3):UBOUND(SELF%RDIGFL,3)))
  READ (KLUN) ZTMP3
  SELF%RDIGFL = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDIPD
IF (LRDIPD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDIPD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDIPD,1):UBOUND(SELF%RDIPD,1), LBOUND(SELF%RDIPD,2):UBOUND(SELF%RDIPD,2)))
  READ (KLUN) ZTMP2
  SELF%RDIPD = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDIVD
IF (LRDIVD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDIVD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDIVD,1):UBOUND(SELF%RDIVD,1), LBOUND(SELF%RDIVD,2):UBOUND(SELF%RDIVD,2)))
  READ (KLUN) ZTMP2
  SELF%RDIVD = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDISP
IF (LRDISP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RDISP (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RDISP,1):UBOUND(SELF%RDISP,1)))
  READ (KLUN) ZTMP1
  SELF%RDISP = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRDHI
IF (LRDHI) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHI (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHI,1):UBOUND(SELF%RDHI,1), LBOUND(SELF%RDHI,2):UBOUND(SELF%RDHI,2), LBOUND(SELF%RDHI,3):UBOUND(SELF%RDHI,3)))
  READ (KLUN) ZTMP3
  SELF%RDHI = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHIVOR
IF (LRDHIVOR) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHIVOR (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHIVOR,1):UBOUND(SELF%RDHIVOR,1), LBOUND(SELF%RDHIVOR,2):UBOUND(SELF%RDHIVOR,2), LBOUND(SELF%RDHIVOR,3):UBOUND(SELF%RDHIVOR,3)))
  READ (KLUN) ZTMP3
  SELF%RDHIVOR = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHIDIV
IF (LRDHIDIV) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHIDIV (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHIDIV,1):UBOUND(SELF%RDHIDIV,1), LBOUND(SELF%RDHIDIV,2):UBOUND(SELF%RDHIDIV,2), LBOUND(SELF%RDHIDIV,3):UBOUND(SELF%RDHIDIV,3)))
  READ (KLUN) ZTMP3
  SELF%RDHIDIV = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHISPD
IF (LRDHISPD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHISPD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHISPD,1):UBOUND(SELF%RDHISPD,1), LBOUND(SELF%RDHISPD,2):UBOUND(SELF%RDHISPD,2), LBOUND(SELF%RDHISPD,3):UBOUND(SELF%RDHISPD,3)))
  READ (KLUN) ZTMP3
  SELF%RDHISPD = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHISVD
IF (LRDHISVD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHISVD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHISVD,1):UBOUND(SELF%RDHISVD,1), LBOUND(SELF%RDHISVD,2):UBOUND(SELF%RDHISVD,2), LBOUND(SELF%RDHISVD,3):UBOUND(SELF%RDHISVD,3)))
  READ (KLUN) ZTMP3
  SELF%RDHISVD = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHINHX
IF (LRDHINHX) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHINHX (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHINHX,1):UBOUND(SELF%RDHINHX,1), LBOUND(SELF%RDHINHX,2):UBOUND(SELF%RDHINHX,2), LBOUND(SELF%RDHINHX,3):UBOUND(SELF%RDHINHX,3)))
  READ (KLUN) ZTMP3
  SELF%RDHINHX = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHIT
IF (LRDHIT) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHIT (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHIT,1):UBOUND(SELF%RDHIT,1), LBOUND(SELF%RDHIT,2):UBOUND(SELF%RDHIT,2), LBOUND(SELF%RDHIT,3):UBOUND(SELF%RDHIT,3)))
  READ (KLUN) ZTMP3
  SELF%RDHIT = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHIGFL
IF (LRDHIGFL) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (SELF%RDHIGFL (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(SELF%RDHIGFL,1):UBOUND(SELF%RDHIGFL,1), LBOUND(SELF%RDHIGFL,2):UBOUND(SELF%RDHIGFL,2), LBOUND(SELF%RDHIGFL,3):UBOUND(SELF%RDHIGFL,3), LBOUND(SELF%RDHIGFL,4):UBOUND(SELF%RDHIGFL,4)))
  READ (KLUN) ZTMP4
  SELF%RDHIGFL = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
READ (KLUN) LRDHIP
IF (LRDHIP) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHIP (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHIP,1):UBOUND(SELF%RDHIP,1), LBOUND(SELF%RDHIP,2):UBOUND(SELF%RDHIP,2), LBOUND(SELF%RDHIP,3):UBOUND(SELF%RDHIP,3)))
  READ (KLUN) ZTMP3
  SELF%RDHIP = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHSVOR
IF (LRDHSVOR) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHSVOR (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHSVOR,1):UBOUND(SELF%RDHSVOR,1), LBOUND(SELF%RDHSVOR,2):UBOUND(SELF%RDHSVOR,2), LBOUND(SELF%RDHSVOR,3):UBOUND(SELF%RDHSVOR,3)))
  READ (KLUN) ZTMP3
  SELF%RDHSVOR = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHSDIV
IF (LRDHSDIV) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHSDIV (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHSDIV,1):UBOUND(SELF%RDHSDIV,1), LBOUND(SELF%RDHSDIV,2):UBOUND(SELF%RDHSDIV,2), LBOUND(SELF%RDHSDIV,3):UBOUND(SELF%RDHSDIV,3)))
  READ (KLUN) ZTMP3
  SELF%RDHSDIV = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHSSVD
IF (LRDHSSVD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHSSVD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHSSVD,1):UBOUND(SELF%RDHSSVD,1), LBOUND(SELF%RDHSSVD,2):UBOUND(SELF%RDHSSVD,2), LBOUND(SELF%RDHSSVD,3):UBOUND(SELF%RDHSSVD,3)))
  READ (KLUN) ZTMP3
  SELF%RDHSSVD = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHSNHX
IF (LRDHSNHX) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHSNHX (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHSNHX,1):UBOUND(SELF%RDHSNHX,1), LBOUND(SELF%RDHSNHX,2):UBOUND(SELF%RDHSNHX,2), LBOUND(SELF%RDHSNHX,3):UBOUND(SELF%RDHSNHX,3)))
  READ (KLUN) ZTMP3
  SELF%RDHSNHX = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) SELF%LSTRHD
READ (KLUN) ZTMP0
SELF%HDTIME_STRHD = ZTMP0
READ (KLUN) ZTMP0
SELF%KLSPONGE = ZTMP0
READ (KLUN) SELF%LM0DAMP
READ (KLUN) ZTMP0
SELF%RBEGSPONGE = ZTMP0
READ (KLUN) SELF%LTOP_VOR
READ (KLUN) SELF%NTOP_VOR_TRUNC
READ (KLUN) SELF%NTOP_VOR_BOT
READ (KLUN) LRSAVEDP
IF (LRSAVEDP) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (SELF%RSAVEDP (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(SELF%RSAVEDP,1):UBOUND(SELF%RSAVEDP,1), LBOUND(SELF%RSAVEDP,2):UBOUND(SELF%RSAVEDP,2), LBOUND(SELF%RSAVEDP,3):UBOUND(SELF%RSAVEDP,3), LBOUND(SELF%RSAVEDP,4):UBOUND(SELF%RSAVEDP,4)))
  READ (KLUN) ZTMP4
  SELF%RSAVEDP = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
READ (KLUN) ZTMP0
SELF%SLHDA0 = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDA0T = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDB = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDBT = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDD00 = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDD00T = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDRATDDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDHOR = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHD_P_LOW = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHD_P_HIGH = ZTMP0
READ (KLUN) SELF%LSLHDHEAT
READ (KLUN) SELF%LSLHDSPONGE
READ (KLUN) ZTMP0
SELF%HDSRVOR = ZTMP0
READ (KLUN) ZTMP0
SELF%HDSRDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%HDSRVD = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDSRVOR = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDSRDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDSRVD = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPVORS = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPDIVS = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPVDS = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPHDS = ZTMP0
READ (KLUN) ZTMP0
SELF%REXPDHS = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDHS = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDHS1 = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDHS2 = ZTMP0
READ (KLUN) ZTMP0
SELF%SDRED = ZTMP0
READ (KLUN) LRDSVOR
IF (LRDSVOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDSVOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDSVOR,1):UBOUND(SELF%RDSVOR,1), LBOUND(SELF%RDSVOR,2):UBOUND(SELF%RDSVOR,2)))
  READ (KLUN) ZTMP2
  SELF%RDSVOR = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDSDIV
IF (LRDSDIV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDSDIV (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDSDIV,1):UBOUND(SELF%RDSDIV,1), LBOUND(SELF%RDSDIV,2):UBOUND(SELF%RDSDIV,2)))
  READ (KLUN) ZTMP2
  SELF%RDSDIV = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDSVD
IF (LRDSVD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDSVD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDSVD,1):UBOUND(SELF%RDSVD,1), LBOUND(SELF%RDSVD,2):UBOUND(SELF%RDSVD,2)))
  READ (KLUN) ZTMP2
  SELF%RDSVD = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDHS
IF (LRDHS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHS,1):UBOUND(SELF%RDHS,1), LBOUND(SELF%RDHS,2):UBOUND(SELF%RDHS,2), LBOUND(SELF%RDHS,3):UBOUND(SELF%RDHS,3)))
  READ (KLUN) ZTMP3
  SELF%RDHS = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSLHD_MASK_U
IF (LSLHD_MASK_U) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SLHD_MASK_U (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SLHD_MASK_U,1):UBOUND(SELF%SLHD_MASK_U,1)))
  READ (KLUN) ZTMP1
  SELF%SLHD_MASK_U = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSLHD_MASK_T
IF (LSLHD_MASK_T) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SLHD_MASK_T (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SLHD_MASK_T,1):UBOUND(SELF%SLHD_MASK_T,1)))
  READ (KLUN) ZTMP1
  SELF%SLHD_MASK_T = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) ZTMP0
SELF%ZSLHDP1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZSLHDP3 = ZTMP0
READ (KLUN) SELF%NLEV_SPONGE
READ (KLUN) SELF%LRFRIC
READ (KLUN) SELF%LRFRICISOTR
READ (KLUN) LRCORDIT
IF (LRCORDIT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RCORDIT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RCORDIT,1):UBOUND(SELF%RCORDIT,1)))
  READ (KLUN) ZTMP1
  SELF%RCORDIT = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRCORDIH
IF (LRCORDIH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RCORDIH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RCORDIH,1):UBOUND(SELF%RCORDIH,1)))
  READ (KLUN) ZTMP1
  SELF%RCORDIH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRCORDIF
IF (LRCORDIF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RCORDIF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RCORDIF,1):UBOUND(SELF%RCORDIF,1)))
  READ (KLUN) ZTMP1
  SELF%RCORDIF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) ZTMP0
SELF%VMAX1 = ZTMP0
READ (KLUN) ZTMP0
SELF%VMAX2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RMAX_D3 = ZTMP0
READ (KLUN) SELF%LBOUND_D3
READ (KLUN) LRKRF
IF (LRKRF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RKRF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RKRF,1):UBOUND(SELF%RKRF,1)))
  READ (KLUN) ZTMP1
  SELF%RKRF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) SELF%NMAXLEVRF
READ (KLUN) ZTMP0
SELF%RRFZ1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RRFPLM = ZTMP0
READ (KLUN) ZTMP0
SELF%RRFTAU = ZTMP0
READ (KLUN) ZTMP0
SELF%RTEMRB = ZTMP0
READ (KLUN) SELF%NRUBC
READ (KLUN) SELF%LGWFRIC
READ (KLUN) SELF%NLEV_GWFRIC
READ (KLUN) ZTMP0
SELF%RGWFRIC_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RGWFRIC_PLM = ZTMP0
READ (KLUN) LRGWFRIC
IF (LRGWFRIC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RGWFRIC (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RGWFRIC,1):UBOUND(SELF%RGWFRIC,1)))
  READ (KLUN) ZTMP1
  SELF%RGWFRIC = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) SELF%LSIDG
READ (KLUN) SELF%LDYN_STABAN
READ (KLUN) SELF%LRHDI_LASTITERPC
READ (KLUN) SELF%LSIDYN_VERBOSE
READ (KLUN) ZTMP0
SELF%BETADT = ZTMP0
READ (KLUN) ZTMP0
SELF%RBT = ZTMP0
READ (KLUN) ZTMP0
SELF%RBTS2 = ZTMP0
READ (KLUN) ZTMP0
SELF%REFGEO = ZTMP0
READ (KLUN) ZTMP0
SELF%SIPR = ZTMP0
READ (KLUN) ZTMP0
SELF%SIPRA = ZTMP0
READ (KLUN) ZTMP0
SELF%SITR = ZTMP0
READ (KLUN) ZTMP0
SELF%SITRA = ZTMP0
READ (KLUN) ZTMP0
SELF%SITRUB = ZTMP0
READ (KLUN) ZTMP0
SELF%SIPRUB = ZTMP0
READ (KLUN) ZTMP0
SELF%SITIME = ZTMP0
READ (KLUN) ZTMP0
SELF%SIRPRG = ZTMP0
READ (KLUN) ZTMP0
SELF%SIRPRN = ZTMP0
READ (KLUN) ZTMP0
SELF%SISLP = ZTMP0
READ (KLUN) ZTMP0
SELF%SIFRG = ZTMP0
READ (KLUN) ZTMP0
SELF%SIFRA = ZTMP0
READ (KLUN) ZTMP0
SELF%SITVAR = ZTMP0
READ (KLUN) SELF%NSITER
READ (KLUN) SELF%NCURRENT_ITER
READ (KLUN) SELF%NITERHELM
READ (KLUN) SELF%NOPT_SITR
READ (KLUN) SELF%NOPT_SIPR
READ (KLUN) SELF%NOPT_SISLP
READ (KLUN) LSITRAM
IF (LSITRAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITRAM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITRAM,1):UBOUND(SELF%SITRAM,1)))
  READ (KLUN) ZTMP1
  SELF%SITRAM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITRM
IF (LSITRM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITRM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITRM,1):UBOUND(SELF%SITRM,1)))
  READ (KLUN) ZTMP1
  SELF%SITRM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIALPH
IF (LSIALPH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIALPH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIALPH,1):UBOUND(SELF%SIALPH,1)))
  READ (KLUN) ZTMP1
  SELF%SIALPH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSILNPR
IF (LSILNPR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SILNPR (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SILNPR,1):UBOUND(SELF%SILNPR,1)))
  READ (KLUN) ZTMP1
  SELF%SILNPR = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIDELP
IF (LSIDELP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIDELP (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIDELP,1):UBOUND(SELF%SIDELP,1)))
  READ (KLUN) ZTMP1
  SELF%SIDELP = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIRDEL
IF (LSIRDEL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIRDEL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIRDEL,1):UBOUND(SELF%SIRDEL,1)))
  READ (KLUN) ZTMP1
  SELF%SIRDEL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITLAH
IF (LSITLAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITLAH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITLAH,1):UBOUND(SELF%SITLAH,1)))
  READ (KLUN) ZTMP1
  SELF%SITLAH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITLAF
IF (LSITLAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITLAF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITLAF,1):UBOUND(SELF%SITLAF,1)))
  READ (KLUN) ZTMP1
  SELF%SITLAF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIDPHI
IF (LSIDPHI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIDPHI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIDPHI,1):UBOUND(SELF%SIDPHI,1)))
  READ (KLUN) ZTMP1
  SELF%SIDPHI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIALPH_NH
IF (LSIALPH_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIALPH_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIALPH_NH,1):UBOUND(SELF%SIALPH_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SIALPH_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSILNPR_NH
IF (LSILNPR_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SILNPR_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SILNPR_NH,1):UBOUND(SELF%SILNPR_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SILNPR_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIDELP_NH
IF (LSIDELP_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIDELP_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIDELP_NH,1):UBOUND(SELF%SIDELP_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SIDELP_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIRDEL_NH
IF (LSIRDEL_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIRDEL_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIRDEL_NH,1):UBOUND(SELF%SIRDEL_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SIRDEL_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITLAH_NH
IF (LSITLAH_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITLAH_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITLAH_NH,1):UBOUND(SELF%SITLAH_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SITLAH_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITLAF_NH
IF (LSITLAF_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITLAF_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITLAF_NH,1):UBOUND(SELF%SITLAF_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SITLAF_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIDPHI_NH
IF (LSIDPHI_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIDPHI_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIDPHI_NH,1):UBOUND(SELF%SIDPHI_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SIDPHI_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIWF2H
IF (LSIWF2H) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIWF2H (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIWF2H,1):UBOUND(SELF%SIWF2H,1)))
  READ (KLUN) ZTMP1
  SELF%SIWF2H = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIWH2F
IF (LSIWH2F) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIWH2F (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIWH2F,1):UBOUND(SELF%SIWH2F,1), LBOUND(SELF%SIWH2F,2):UBOUND(SELF%SIWH2F,2)))
  READ (KLUN) ZTMP2
  SELF%SIWH2F = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIGFL
IF (LSIGFL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIGFL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIGFL,1):UBOUND(SELF%SIGFL,1)))
  READ (KLUN) ZTMP1
  SELF%SIGFL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIGFM
IF (LSIGFM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIGFM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIGFM,1):UBOUND(SELF%SIGFM,1)))
  READ (KLUN) ZTMP1
  SELF%SIGFM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITFL
IF (LSITFL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITFL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITFL,1):UBOUND(SELF%SITFL,1)))
  READ (KLUN) ZTMP1
  SELF%SITFL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITFM
IF (LSITFM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITFM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITFM,1):UBOUND(SELF%SITFM,1)))
  READ (KLUN) ZTMP1
  SELF%SITFM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIGHL
IF (LSIGHL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIGHL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIGHL,1):UBOUND(SELF%SIGHL,1)))
  READ (KLUN) ZTMP1
  SELF%SIGHL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIGHM
IF (LSIGHM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIGHM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIGHM,1):UBOUND(SELF%SIGHM,1)))
  READ (KLUN) ZTMP1
  SELF%SIGHM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIB
IF (LSIB) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIB (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIB,1):UBOUND(SELF%SIB,1), LBOUND(SELF%SIB,2):UBOUND(SELF%SIB,2)))
  READ (KLUN) ZTMP2
  SELF%SIB = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIMO
IF (LSIMO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIMO (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIMO,1):UBOUND(SELF%SIMO,1), LBOUND(SELF%SIMO,2):UBOUND(SELF%SIMO,2)))
  READ (KLUN) ZTMP2
  SELF%SIMO = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIMI
IF (LSIMI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIMI (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIMI,1):UBOUND(SELF%SIMI,1), LBOUND(SELF%SIMI,2):UBOUND(SELF%SIMI,2)))
  READ (KLUN) ZTMP2
  SELF%SIMI = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIVP
IF (LSIVP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIVP (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIVP,1):UBOUND(SELF%SIVP,1)))
  READ (KLUN) ZTMP1
  SELF%SIVP = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIHEG
IF (LSIHEG) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%SIHEG (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%SIHEG,1):UBOUND(SELF%SIHEG,1), LBOUND(SELF%SIHEG,2):UBOUND(SELF%SIHEG,2), LBOUND(SELF%SIHEG,3):UBOUND(SELF%SIHEG,3)))
  READ (KLUN) ZTMP3
  SELF%SIHEG = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEG2
IF (LSIHEG2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%SIHEG2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%SIHEG2,1):UBOUND(SELF%SIHEG2,1), LBOUND(SELF%SIHEG2,2):UBOUND(SELF%SIHEG2,2), LBOUND(SELF%SIHEG2,3):UBOUND(SELF%SIHEG2,3)))
  READ (KLUN) ZTMP3
  SELF%SIHEG2 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEGB
IF (LSIHEGB) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%SIHEGB (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%SIHEGB,1):UBOUND(SELF%SIHEGB,1), LBOUND(SELF%SIHEGB,2):UBOUND(SELF%SIHEGB,2), LBOUND(SELF%SIHEGB,3):UBOUND(SELF%SIHEGB,3)))
  READ (KLUN) ZTMP3
  SELF%SIHEGB = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEGB2
IF (LSIHEGB2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%SIHEGB2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%SIHEGB2,1):UBOUND(SELF%SIHEGB2,1), LBOUND(SELF%SIHEGB2,2):UBOUND(SELF%SIHEGB2,2), LBOUND(SELF%SIHEGB2,3):UBOUND(SELF%SIHEGB2,3)))
  READ (KLUN) ZTMP3
  SELF%SIHEGB2 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIFAC
IF (LSIFAC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIFAC (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIFAC,1):UBOUND(SELF%SIFAC,1), LBOUND(SELF%SIFAC,2):UBOUND(SELF%SIFAC,2)))
  READ (KLUN) ZTMP2
  SELF%SIFAC = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIFACI
IF (LSIFACI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIFACI (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIFACI,1):UBOUND(SELF%SIFACI,1), LBOUND(SELF%SIFACI,2):UBOUND(SELF%SIFACI,2)))
  READ (KLUN) ZTMP2
  SELF%SIFACI = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIBQ
IF (LSIBQ) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIBQ (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIBQ,1):UBOUND(SELF%SIBQ,1), LBOUND(SELF%SIBQ,2):UBOUND(SELF%SIBQ,2)))
  READ (KLUN) ZTMP2
  SELF%SIBQ = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIMITRA
IF (LSIMITRA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIMITRA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIMITRA,1):UBOUND(SELF%SIMITRA,1), LBOUND(SELF%SIMITRA,2):UBOUND(SELF%SIMITRA,2)))
  READ (KLUN) ZTMP2
  SELF%SIMITRA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIMOTRA
IF (LSIMOTRA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIMOTRA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIMOTRA,1):UBOUND(SELF%SIMOTRA,1), LBOUND(SELF%SIMOTRA,2):UBOUND(SELF%SIMOTRA,2)))
  READ (KLUN) ZTMP2
  SELF%SIMOTRA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIFACITRA
IF (LSIFACITRA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIFACITRA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIFACITRA,1):UBOUND(SELF%SIFACITRA,1), LBOUND(SELF%SIFACITRA,2):UBOUND(SELF%SIFACITRA,2)))
  READ (KLUN) ZTMP2
  SELF%SIFACITRA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIHEGTRA
IF (LSIHEGTRA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIHEGTRA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIHEGTRA,1):UBOUND(SELF%SIHEGTRA,1), LBOUND(SELF%SIHEGTRA,2):UBOUND(SELF%SIHEGTRA,2)))
  READ (KLUN) ZTMP2
  SELF%SIHEGTRA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIHEG2TRA
IF (LSIHEG2TRA) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%SIHEG2TRA (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%SIHEG2TRA,1):UBOUND(SELF%SIHEG2TRA,1), LBOUND(SELF%SIHEG2TRA,2):UBOUND(SELF%SIHEG2TRA,2), LBOUND(SELF%SIHEG2TRA,3):UBOUND(SELF%SIHEG2TRA,3)))
  READ (KLUN) ZTMP3
  SELF%SIHEG2TRA = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEGBTRA
IF (LSIHEGBTRA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIHEGBTRA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIHEGBTRA,1):UBOUND(SELF%SIHEGBTRA,1), LBOUND(SELF%SIHEGBTRA,2):UBOUND(SELF%SIHEGBTRA,2)))
  READ (KLUN) ZTMP2
  SELF%SIHEGBTRA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIHEGB2TRA
IF (LSIHEGB2TRA) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%SIHEGB2TRA (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%SIHEGB2TRA,1):UBOUND(SELF%SIHEGB2TRA,1), LBOUND(SELF%SIHEGB2TRA,2):UBOUND(SELF%SIHEGB2TRA,2), LBOUND(SELF%SIHEGB2TRA,3):UBOUND(SELF%SIHEGB2TRA,3)))
  READ (KLUN) ZTMP3
  SELF%SIHEGB2TRA = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEGIND
IF (LSIHEGIND) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIHEGIND (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIHEGIND,1):UBOUND(SELF%SIHEGIND,1)))
  READ (KLUN) ZTMP1
  SELF%SIHEGIND = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIBQTRA
IF (LSIBQTRA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIBQTRA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIBQTRA,1):UBOUND(SELF%SIBQTRA,1), LBOUND(SELF%SIBQTRA,2):UBOUND(SELF%SIBQTRA,2)))
  READ (KLUN) ZTMP2
  SELF%SIBQTRA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIZA
IF (LSIZA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIZA (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIZA,1):UBOUND(SELF%SIZA,1)))
  READ (KLUN) ZTMP1
  SELF%SIZA = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIZC
IF (LSIZC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIZC (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIZC,1):UBOUND(SELF%SIZC,1)))
  READ (KLUN) ZTMP1
  SELF%SIZC = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIPIS
IF (LSIPIS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIPIS (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIPIS,1):UBOUND(SELF%SIPIS,1)))
  READ (KLUN) ZTMP1
  SELF%SIPIS = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITGR
IF (LSITGR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SITGR (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SITGR,1):UBOUND(SELF%SITGR,1), LBOUND(SELF%SITGR,2):UBOUND(SELF%SITGR,2)))
  READ (KLUN) ZTMP2
  SELF%SITGR = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSITAC
IF (LSITAC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITAC (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITAC,1):UBOUND(SELF%SITAC,1)))
  READ (KLUN) ZTMP1
  SELF%SITAC = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) ZTMP0
SELF%VNORM = ZTMP0
READ (KLUN) ZTMP0
SELF%SLOPE_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%PSURF_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%PSURF_MIN = ZTMP0
READ (KLUN) SELF%NVLAG
READ (KLUN) SELF%NWLAG
READ (KLUN) SELF%NTLAG
READ (KLUN) SELF%NSPDLAG
READ (KLUN) SELF%NSVDLAG
READ (KLUN) SELF%NSPLTHOI
READ (KLUN) SELF%LSPLTHOIGFL
READ (KLUN) SELF%NSLDIMK
READ (KLUN) SELF%NITMP
READ (KLUN) ZTMP0
SELF%VETAON = ZTMP0
READ (KLUN) ZTMP0
SELF%VETAOX = ZTMP0
READ (KLUN) SELF%LSETTLSVF
READ (KLUN) SELF%LSETFSTAT
READ (KLUN) SELF%LSETTLSVF_DIFF
READ (KLUN) ZTMP0
SELF%RW2TLFF = ZTMP0
READ (KLUN) ZTMP0
SELF%RALPHA = ZTMP0
READ (KLUN) ZTMP0
SELF%RALPHA_TOP = ZTMP0
READ (KLUN) SELF%NLEV_ZALPHA
READ (KLUN) SELF%NEDER
ALLOCATE (ZTMP2(LBOUND(SELF%RBETAK,1):UBOUND(SELF%RBETAK,1), LBOUND(SELF%RBETAK,2):UBOUND(SELF%RBETAK,2)))
READ (KLUN) ZTMP2
SELF%RBETAK = ZTMP2
DEALLOCATE (ZTMP2)
READ (KLUN) SELF%LWENOBC
READ (KLUN) SELF%NQMHOISLT
READ (KLUN) SELF%LSLDP_RK
READ (KLUN) SELF%LSLDP_CURV
READ (KLUN) SELF%LSLDP_CURV_FIX
READ (KLUN) SELF%LRHS_CURV
READ (KLUN) SELF%LRHS_CURV_FIX
READ (KLUN) SELF%LSLDP_XYZ
READ (KLUN) SELF%LSLDP_SAVE
READ (KLUN) ZTMP0
SELF%VESL = ZTMP0
READ (KLUN) ZTMP0
SELF%XIDT = ZTMP0
READ (KLUN) SELF%LQMW
READ (KLUN) SELF%LQMHW
READ (KLUN) SELF%LQMT
READ (KLUN) SELF%LQMHT
READ (KLUN) SELF%LQMP
READ (KLUN) SELF%LQMHP
READ (KLUN) SELF%LQMPD
READ (KLUN) SELF%LQMHPD
READ (KLUN) SELF%LQMVD
READ (KLUN) SELF%LQMHVD
READ (KLUN) SELF%LVWENO_W
READ (KLUN) SELF%LVWENO_T
READ (KLUN) SELF%LVWENO_SP
READ (KLUN) SELF%LVWENO_SPD
READ (KLUN) SELF%LVWENO_SVD
READ (KLUN) ZTMP0
SELF%WENO_ALPHA_W = ZTMP0
READ (KLUN) ZTMP0
SELF%WENO_ALPHA_T = ZTMP0
READ (KLUN) ZTMP0
SELF%WENO_ALPHA_SP = ZTMP0
READ (KLUN) ZTMP0
SELF%WENO_ALPHA_SPD = ZTMP0
READ (KLUN) ZTMP0
SELF%WENO_ALPHA_SVD = ZTMP0
READ (KLUN) SELF%LADVF
READ (KLUN) SELF%LIMPF
READ (KLUN) SELF%L2TLFF
READ (KLUN) ZTMP0
SELF%RCMSLP0 = ZTMP0
READ (KLUN) SELF%NCOMP_CVGQ
READ (KLUN) SELF%LSVTSM
READ (KLUN) ZTMP0
SELF%RPRES_SVTSM = ZTMP0
READ (KLUN) ZTMP0
SELF%RPRES_SETTLSVF = ZTMP0
READ (KLUN) SELF%NFLEVSF
READ (KLUN) ZTMP0
SELF%RSCALE = ZTMP0
READ (KLUN) ZTMP0
SELF%RSCALEOFF = ZTMP0
READ (KLUN) ZTMP0
SELF%RINTOPT = ZTMP0
READ (KLUN) ZTMP0
SELF%RRINTOPT = ZTMP0
READ (KLUN) SELF%LHDIFFM
READ (KLUN) SELF%LSPECVIS
READ (KLUN) SELF%NDIFFACT
READ (KLUN) SELF%LGPSTRESS
READ (KLUN) ZTMP0
SELF%RCLSTRESS = ZTMP0
READ (KLUN) ZTMP0
SELF%RCLPOLE = ZTMP0
READ (KLUN) SELF%NVSEPC
READ (KLUN) SELF%NVSEPL
READ (KLUN) SELF%LFINDVSEP
READ (KLUN) SELF%LMASCOR
READ (KLUN) SELF%LMASDRY
READ (KLUN) SELF%LGPMASCOR
READ (KLUN) SELF%NGPMASCOR
READ (KLUN) ZTMP0
SELF%GPMASSI = ZTMP0
READ (KLUN) ZTMP0
SELF%GMASSI = ZTMP0
READ (KLUN) ZTMP0
SELF%GMASS0 = ZTMP0
READ (KLUN) ZTMP0
SELF%GMASSINC = ZTMP0
READ (KLUN) SELF%LNODRYFLX
READ (KLUN) LSIBI
IF (LSIBI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIBI (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIBI,1):UBOUND(SELF%SIBI,1), LBOUND(SELF%SIBI,2):UBOUND(SELF%SIBI,2)))
  READ (KLUN) ZTMP2
  SELF%SIBI = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) ZTMP0
SELF%RESGP = ZTMP0
READ (KLUN) ZTMP0
SELF%RESGM = ZTMP0
READ (KLUN) SELF%LNHHY_SOLVER_GP
READ (KLUN) SELF%LNHHY_SOLVER_SP
READ (KLUN) SELF%LNHQE_SOLVER_GP
READ (KLUN) SELF%LNHQE_SOLVER_SP
READ (KLUN) SELF%LRESET_BLEND_SI
READ (KLUN) SELF%NSTOP_BLEND
READ (KLUN) SELF%NSTART_BLEND
READ (KLUN) ZTMP0
SELF%RNHQE_DELTAM = ZTMP0
READ (KLUN) LRNHHY_DELTAM
IF (LRNHHY_DELTAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RNHHY_DELTAM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RNHHY_DELTAM,1):UBOUND(SELF%RNHHY_DELTAM,1)))
  READ (KLUN) ZTMP1
  SELF%RNHHY_DELTAM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
CALL LOAD_TSWE (SELF%YRSWE, KLUN)
READ (KLUN) SELF%CLAITRI_TYPE
READ (KLUN) SELF%CLAITRI_WENO_TYPE
READ (KLUN) LRGAMMA_WENO
IF (LRGAMMA_WENO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RGAMMA_WENO (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RGAMMA_WENO,1):UBOUND(SELF%RGAMMA_WENO,1), LBOUND(SELF%RGAMMA_WENO,2):UBOUND(SELF%RGAMMA_WENO,2)))
  READ (KLUN) ZTMP2
  SELF%RGAMMA_WENO = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TDYN (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_TSWE_MOD
IMPLICIT NONE
TYPE (TDYN), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHIDIV, LRDHIGFL, LRDHINHX, LRDHIP, LRDHISPD, LRDHISVD
LOGICAL :: LRDHIT, LRDHIVOR, LRDHS, LRDHSDIV, LRDHSNHX, LRDHSSVD, LRDHSVOR, LRDIDIV, LRDIGFL, LRDIPD
LOGICAL :: LRDISP, LRDITG, LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRGAMMA_WENO, LRGWFRIC, LRKRF
LOGICAL :: LRNHHY_DELTAM, LRSAVEDP, LSIALPH, LSIALPH_NH, LSIB, LSIBI, LSIBQ, LSIBQTRA, LSIDELP, LSIDELP_NH
LOGICAL :: LSIDPHI, LSIDPHI_NH, LSIFAC, LSIFACI, LSIFACITRA, LSIGFL, LSIGFM, LSIGHL, LSIGHM, LSIHEG
LOGICAL :: LSIHEG2, LSIHEG2TRA, LSIHEGB, LSIHEGB2, LSIHEGB2TRA, LSIHEGBTRA, LSIHEGIND, LSIHEGTRA, LSILNPR, LSILNPR_NH
LOGICAL :: LSIMI, LSIMITRA, LSIMO, LSIMOTRA, LSIPIS, LSIRDEL, LSIRDEL_NH, LSITAC, LSITFL, LSITFM
LOGICAL :: LSITGR, LSITLAF, LSITLAF_NH, LSITLAH, LSITLAH_NH, LSITRAM, LSITRM, LSIVP, LSIWF2H, LSIWH2F
LOGICAL :: LSIZA, LSIZC, LSLHD_MASK_T, LSLHD_MASK_U

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LRDIVOR = ALLOCATED (SELF%RDIVOR)
IF (LRDIVOR) THEN
  !$ACC ENTER DATA CREATE (SELF%RDIVOR)
  !$ACC UPDATE DEVICE (SELF%RDIVOR)
  !$ACC ENTER DATA ATTACH (SELF%RDIVOR)
ENDIF

LRDIDIV = ALLOCATED (SELF%RDIDIV)
IF (LRDIDIV) THEN
  !$ACC ENTER DATA CREATE (SELF%RDIDIV)
  !$ACC UPDATE DEVICE (SELF%RDIDIV)
  !$ACC ENTER DATA ATTACH (SELF%RDIDIV)
ENDIF

LRDITG = ALLOCATED (SELF%RDITG)
IF (LRDITG) THEN
  !$ACC ENTER DATA CREATE (SELF%RDITG)
  !$ACC UPDATE DEVICE (SELF%RDITG)
  !$ACC ENTER DATA ATTACH (SELF%RDITG)
ENDIF

LRDIGFL = ALLOCATED (SELF%RDIGFL)
IF (LRDIGFL) THEN
  !$ACC ENTER DATA CREATE (SELF%RDIGFL)
  !$ACC UPDATE DEVICE (SELF%RDIGFL)
  !$ACC ENTER DATA ATTACH (SELF%RDIGFL)
ENDIF

LRDIPD = ALLOCATED (SELF%RDIPD)
IF (LRDIPD) THEN
  !$ACC ENTER DATA CREATE (SELF%RDIPD)
  !$ACC UPDATE DEVICE (SELF%RDIPD)
  !$ACC ENTER DATA ATTACH (SELF%RDIPD)
ENDIF

LRDIVD = ALLOCATED (SELF%RDIVD)
IF (LRDIVD) THEN
  !$ACC ENTER DATA CREATE (SELF%RDIVD)
  !$ACC UPDATE DEVICE (SELF%RDIVD)
  !$ACC ENTER DATA ATTACH (SELF%RDIVD)
ENDIF

LRDISP = ALLOCATED (SELF%RDISP)
IF (LRDISP) THEN
  !$ACC ENTER DATA CREATE (SELF%RDISP)
  !$ACC UPDATE DEVICE (SELF%RDISP)
  !$ACC ENTER DATA ATTACH (SELF%RDISP)
ENDIF

LRDHI = ALLOCATED (SELF%RDHI)
IF (LRDHI) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHI)
  !$ACC UPDATE DEVICE (SELF%RDHI)
  !$ACC ENTER DATA ATTACH (SELF%RDHI)
ENDIF

LRDHIVOR = ALLOCATED (SELF%RDHIVOR)
IF (LRDHIVOR) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHIVOR)
  !$ACC UPDATE DEVICE (SELF%RDHIVOR)
  !$ACC ENTER DATA ATTACH (SELF%RDHIVOR)
ENDIF

LRDHIDIV = ALLOCATED (SELF%RDHIDIV)
IF (LRDHIDIV) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHIDIV)
  !$ACC UPDATE DEVICE (SELF%RDHIDIV)
  !$ACC ENTER DATA ATTACH (SELF%RDHIDIV)
ENDIF

LRDHISPD = ALLOCATED (SELF%RDHISPD)
IF (LRDHISPD) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHISPD)
  !$ACC UPDATE DEVICE (SELF%RDHISPD)
  !$ACC ENTER DATA ATTACH (SELF%RDHISPD)
ENDIF

LRDHISVD = ALLOCATED (SELF%RDHISVD)
IF (LRDHISVD) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHISVD)
  !$ACC UPDATE DEVICE (SELF%RDHISVD)
  !$ACC ENTER DATA ATTACH (SELF%RDHISVD)
ENDIF

LRDHINHX = ALLOCATED (SELF%RDHINHX)
IF (LRDHINHX) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHINHX)
  !$ACC UPDATE DEVICE (SELF%RDHINHX)
  !$ACC ENTER DATA ATTACH (SELF%RDHINHX)
ENDIF

LRDHIT = ALLOCATED (SELF%RDHIT)
IF (LRDHIT) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHIT)
  !$ACC UPDATE DEVICE (SELF%RDHIT)
  !$ACC ENTER DATA ATTACH (SELF%RDHIT)
ENDIF

LRDHIGFL = ALLOCATED (SELF%RDHIGFL)
IF (LRDHIGFL) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHIGFL)
  !$ACC UPDATE DEVICE (SELF%RDHIGFL)
  !$ACC ENTER DATA ATTACH (SELF%RDHIGFL)
ENDIF

LRDHIP = ALLOCATED (SELF%RDHIP)
IF (LRDHIP) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHIP)
  !$ACC UPDATE DEVICE (SELF%RDHIP)
  !$ACC ENTER DATA ATTACH (SELF%RDHIP)
ENDIF

LRDHSVOR = ALLOCATED (SELF%RDHSVOR)
IF (LRDHSVOR) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHSVOR)
  !$ACC UPDATE DEVICE (SELF%RDHSVOR)
  !$ACC ENTER DATA ATTACH (SELF%RDHSVOR)
ENDIF

LRDHSDIV = ALLOCATED (SELF%RDHSDIV)
IF (LRDHSDIV) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHSDIV)
  !$ACC UPDATE DEVICE (SELF%RDHSDIV)
  !$ACC ENTER DATA ATTACH (SELF%RDHSDIV)
ENDIF

LRDHSSVD = ALLOCATED (SELF%RDHSSVD)
IF (LRDHSSVD) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHSSVD)
  !$ACC UPDATE DEVICE (SELF%RDHSSVD)
  !$ACC ENTER DATA ATTACH (SELF%RDHSSVD)
ENDIF

LRDHSNHX = ALLOCATED (SELF%RDHSNHX)
IF (LRDHSNHX) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHSNHX)
  !$ACC UPDATE DEVICE (SELF%RDHSNHX)
  !$ACC ENTER DATA ATTACH (SELF%RDHSNHX)
ENDIF

LRSAVEDP = ALLOCATED (SELF%RSAVEDP)
IF (LRSAVEDP) THEN
  !$ACC ENTER DATA CREATE (SELF%RSAVEDP)
  !$ACC UPDATE DEVICE (SELF%RSAVEDP)
  !$ACC ENTER DATA ATTACH (SELF%RSAVEDP)
ENDIF

LRDSVOR = ALLOCATED (SELF%RDSVOR)
IF (LRDSVOR) THEN
  !$ACC ENTER DATA CREATE (SELF%RDSVOR)
  !$ACC UPDATE DEVICE (SELF%RDSVOR)
  !$ACC ENTER DATA ATTACH (SELF%RDSVOR)
ENDIF

LRDSDIV = ALLOCATED (SELF%RDSDIV)
IF (LRDSDIV) THEN
  !$ACC ENTER DATA CREATE (SELF%RDSDIV)
  !$ACC UPDATE DEVICE (SELF%RDSDIV)
  !$ACC ENTER DATA ATTACH (SELF%RDSDIV)
ENDIF

LRDSVD = ALLOCATED (SELF%RDSVD)
IF (LRDSVD) THEN
  !$ACC ENTER DATA CREATE (SELF%RDSVD)
  !$ACC UPDATE DEVICE (SELF%RDSVD)
  !$ACC ENTER DATA ATTACH (SELF%RDSVD)
ENDIF

LRDHS = ALLOCATED (SELF%RDHS)
IF (LRDHS) THEN
  !$ACC ENTER DATA CREATE (SELF%RDHS)
  !$ACC UPDATE DEVICE (SELF%RDHS)
  !$ACC ENTER DATA ATTACH (SELF%RDHS)
ENDIF

LSLHD_MASK_U = ALLOCATED (SELF%SLHD_MASK_U)
IF (LSLHD_MASK_U) THEN
  !$ACC ENTER DATA CREATE (SELF%SLHD_MASK_U)
  !$ACC UPDATE DEVICE (SELF%SLHD_MASK_U)
  !$ACC ENTER DATA ATTACH (SELF%SLHD_MASK_U)
ENDIF

LSLHD_MASK_T = ALLOCATED (SELF%SLHD_MASK_T)
IF (LSLHD_MASK_T) THEN
  !$ACC ENTER DATA CREATE (SELF%SLHD_MASK_T)
  !$ACC UPDATE DEVICE (SELF%SLHD_MASK_T)
  !$ACC ENTER DATA ATTACH (SELF%SLHD_MASK_T)
ENDIF

LRCORDIT = ALLOCATED (SELF%RCORDIT)
IF (LRCORDIT) THEN
  !$ACC ENTER DATA CREATE (SELF%RCORDIT)
  !$ACC UPDATE DEVICE (SELF%RCORDIT)
  !$ACC ENTER DATA ATTACH (SELF%RCORDIT)
ENDIF

LRCORDIH = ALLOCATED (SELF%RCORDIH)
IF (LRCORDIH) THEN
  !$ACC ENTER DATA CREATE (SELF%RCORDIH)
  !$ACC UPDATE DEVICE (SELF%RCORDIH)
  !$ACC ENTER DATA ATTACH (SELF%RCORDIH)
ENDIF

LRCORDIF = ALLOCATED (SELF%RCORDIF)
IF (LRCORDIF) THEN
  !$ACC ENTER DATA CREATE (SELF%RCORDIF)
  !$ACC UPDATE DEVICE (SELF%RCORDIF)
  !$ACC ENTER DATA ATTACH (SELF%RCORDIF)
ENDIF

LRKRF = ALLOCATED (SELF%RKRF)
IF (LRKRF) THEN
  !$ACC ENTER DATA CREATE (SELF%RKRF)
  !$ACC UPDATE DEVICE (SELF%RKRF)
  !$ACC ENTER DATA ATTACH (SELF%RKRF)
ENDIF

LRGWFRIC = ALLOCATED (SELF%RGWFRIC)
IF (LRGWFRIC) THEN
  !$ACC ENTER DATA CREATE (SELF%RGWFRIC)
  !$ACC UPDATE DEVICE (SELF%RGWFRIC)
  !$ACC ENTER DATA ATTACH (SELF%RGWFRIC)
ENDIF

LSITRAM = ALLOCATED (SELF%SITRAM)
IF (LSITRAM) THEN
  !$ACC ENTER DATA CREATE (SELF%SITRAM)
  !$ACC UPDATE DEVICE (SELF%SITRAM)
  !$ACC ENTER DATA ATTACH (SELF%SITRAM)
ENDIF

LSITRM = ALLOCATED (SELF%SITRM)
IF (LSITRM) THEN
  !$ACC ENTER DATA CREATE (SELF%SITRM)
  !$ACC UPDATE DEVICE (SELF%SITRM)
  !$ACC ENTER DATA ATTACH (SELF%SITRM)
ENDIF

LSIALPH = ALLOCATED (SELF%SIALPH)
IF (LSIALPH) THEN
  !$ACC ENTER DATA CREATE (SELF%SIALPH)
  !$ACC UPDATE DEVICE (SELF%SIALPH)
  !$ACC ENTER DATA ATTACH (SELF%SIALPH)
ENDIF

LSILNPR = ALLOCATED (SELF%SILNPR)
IF (LSILNPR) THEN
  !$ACC ENTER DATA CREATE (SELF%SILNPR)
  !$ACC UPDATE DEVICE (SELF%SILNPR)
  !$ACC ENTER DATA ATTACH (SELF%SILNPR)
ENDIF

LSIDELP = ALLOCATED (SELF%SIDELP)
IF (LSIDELP) THEN
  !$ACC ENTER DATA CREATE (SELF%SIDELP)
  !$ACC UPDATE DEVICE (SELF%SIDELP)
  !$ACC ENTER DATA ATTACH (SELF%SIDELP)
ENDIF

LSIRDEL = ALLOCATED (SELF%SIRDEL)
IF (LSIRDEL) THEN
  !$ACC ENTER DATA CREATE (SELF%SIRDEL)
  !$ACC UPDATE DEVICE (SELF%SIRDEL)
  !$ACC ENTER DATA ATTACH (SELF%SIRDEL)
ENDIF

LSITLAH = ALLOCATED (SELF%SITLAH)
IF (LSITLAH) THEN
  !$ACC ENTER DATA CREATE (SELF%SITLAH)
  !$ACC UPDATE DEVICE (SELF%SITLAH)
  !$ACC ENTER DATA ATTACH (SELF%SITLAH)
ENDIF

LSITLAF = ALLOCATED (SELF%SITLAF)
IF (LSITLAF) THEN
  !$ACC ENTER DATA CREATE (SELF%SITLAF)
  !$ACC UPDATE DEVICE (SELF%SITLAF)
  !$ACC ENTER DATA ATTACH (SELF%SITLAF)
ENDIF

LSIDPHI = ALLOCATED (SELF%SIDPHI)
IF (LSIDPHI) THEN
  !$ACC ENTER DATA CREATE (SELF%SIDPHI)
  !$ACC UPDATE DEVICE (SELF%SIDPHI)
  !$ACC ENTER DATA ATTACH (SELF%SIDPHI)
ENDIF

LSIALPH_NH = ALLOCATED (SELF%SIALPH_NH)
IF (LSIALPH_NH) THEN
  !$ACC ENTER DATA CREATE (SELF%SIALPH_NH)
  !$ACC UPDATE DEVICE (SELF%SIALPH_NH)
  !$ACC ENTER DATA ATTACH (SELF%SIALPH_NH)
ENDIF

LSILNPR_NH = ALLOCATED (SELF%SILNPR_NH)
IF (LSILNPR_NH) THEN
  !$ACC ENTER DATA CREATE (SELF%SILNPR_NH)
  !$ACC UPDATE DEVICE (SELF%SILNPR_NH)
  !$ACC ENTER DATA ATTACH (SELF%SILNPR_NH)
ENDIF

LSIDELP_NH = ALLOCATED (SELF%SIDELP_NH)
IF (LSIDELP_NH) THEN
  !$ACC ENTER DATA CREATE (SELF%SIDELP_NH)
  !$ACC UPDATE DEVICE (SELF%SIDELP_NH)
  !$ACC ENTER DATA ATTACH (SELF%SIDELP_NH)
ENDIF

LSIRDEL_NH = ALLOCATED (SELF%SIRDEL_NH)
IF (LSIRDEL_NH) THEN
  !$ACC ENTER DATA CREATE (SELF%SIRDEL_NH)
  !$ACC UPDATE DEVICE (SELF%SIRDEL_NH)
  !$ACC ENTER DATA ATTACH (SELF%SIRDEL_NH)
ENDIF

LSITLAH_NH = ALLOCATED (SELF%SITLAH_NH)
IF (LSITLAH_NH) THEN
  !$ACC ENTER DATA CREATE (SELF%SITLAH_NH)
  !$ACC UPDATE DEVICE (SELF%SITLAH_NH)
  !$ACC ENTER DATA ATTACH (SELF%SITLAH_NH)
ENDIF

LSITLAF_NH = ALLOCATED (SELF%SITLAF_NH)
IF (LSITLAF_NH) THEN
  !$ACC ENTER DATA CREATE (SELF%SITLAF_NH)
  !$ACC UPDATE DEVICE (SELF%SITLAF_NH)
  !$ACC ENTER DATA ATTACH (SELF%SITLAF_NH)
ENDIF

LSIDPHI_NH = ALLOCATED (SELF%SIDPHI_NH)
IF (LSIDPHI_NH) THEN
  !$ACC ENTER DATA CREATE (SELF%SIDPHI_NH)
  !$ACC UPDATE DEVICE (SELF%SIDPHI_NH)
  !$ACC ENTER DATA ATTACH (SELF%SIDPHI_NH)
ENDIF

LSIWF2H = ALLOCATED (SELF%SIWF2H)
IF (LSIWF2H) THEN
  !$ACC ENTER DATA CREATE (SELF%SIWF2H)
  !$ACC UPDATE DEVICE (SELF%SIWF2H)
  !$ACC ENTER DATA ATTACH (SELF%SIWF2H)
ENDIF

LSIWH2F = ALLOCATED (SELF%SIWH2F)
IF (LSIWH2F) THEN
  !$ACC ENTER DATA CREATE (SELF%SIWH2F)
  !$ACC UPDATE DEVICE (SELF%SIWH2F)
  !$ACC ENTER DATA ATTACH (SELF%SIWH2F)
ENDIF

LSIGFL = ALLOCATED (SELF%SIGFL)
IF (LSIGFL) THEN
  !$ACC ENTER DATA CREATE (SELF%SIGFL)
  !$ACC UPDATE DEVICE (SELF%SIGFL)
  !$ACC ENTER DATA ATTACH (SELF%SIGFL)
ENDIF

LSIGFM = ALLOCATED (SELF%SIGFM)
IF (LSIGFM) THEN
  !$ACC ENTER DATA CREATE (SELF%SIGFM)
  !$ACC UPDATE DEVICE (SELF%SIGFM)
  !$ACC ENTER DATA ATTACH (SELF%SIGFM)
ENDIF

LSITFL = ALLOCATED (SELF%SITFL)
IF (LSITFL) THEN
  !$ACC ENTER DATA CREATE (SELF%SITFL)
  !$ACC UPDATE DEVICE (SELF%SITFL)
  !$ACC ENTER DATA ATTACH (SELF%SITFL)
ENDIF

LSITFM = ALLOCATED (SELF%SITFM)
IF (LSITFM) THEN
  !$ACC ENTER DATA CREATE (SELF%SITFM)
  !$ACC UPDATE DEVICE (SELF%SITFM)
  !$ACC ENTER DATA ATTACH (SELF%SITFM)
ENDIF

LSIGHL = ALLOCATED (SELF%SIGHL)
IF (LSIGHL) THEN
  !$ACC ENTER DATA CREATE (SELF%SIGHL)
  !$ACC UPDATE DEVICE (SELF%SIGHL)
  !$ACC ENTER DATA ATTACH (SELF%SIGHL)
ENDIF

LSIGHM = ALLOCATED (SELF%SIGHM)
IF (LSIGHM) THEN
  !$ACC ENTER DATA CREATE (SELF%SIGHM)
  !$ACC UPDATE DEVICE (SELF%SIGHM)
  !$ACC ENTER DATA ATTACH (SELF%SIGHM)
ENDIF

LSIB = ALLOCATED (SELF%SIB)
IF (LSIB) THEN
  !$ACC ENTER DATA CREATE (SELF%SIB)
  !$ACC UPDATE DEVICE (SELF%SIB)
  !$ACC ENTER DATA ATTACH (SELF%SIB)
ENDIF

LSIMO = ALLOCATED (SELF%SIMO)
IF (LSIMO) THEN
  !$ACC ENTER DATA CREATE (SELF%SIMO)
  !$ACC UPDATE DEVICE (SELF%SIMO)
  !$ACC ENTER DATA ATTACH (SELF%SIMO)
ENDIF

LSIMI = ALLOCATED (SELF%SIMI)
IF (LSIMI) THEN
  !$ACC ENTER DATA CREATE (SELF%SIMI)
  !$ACC UPDATE DEVICE (SELF%SIMI)
  !$ACC ENTER DATA ATTACH (SELF%SIMI)
ENDIF

LSIVP = ALLOCATED (SELF%SIVP)
IF (LSIVP) THEN
  !$ACC ENTER DATA CREATE (SELF%SIVP)
  !$ACC UPDATE DEVICE (SELF%SIVP)
  !$ACC ENTER DATA ATTACH (SELF%SIVP)
ENDIF

LSIHEG = ALLOCATED (SELF%SIHEG)
IF (LSIHEG) THEN
  !$ACC ENTER DATA CREATE (SELF%SIHEG)
  !$ACC UPDATE DEVICE (SELF%SIHEG)
  !$ACC ENTER DATA ATTACH (SELF%SIHEG)
ENDIF

LSIHEG2 = ALLOCATED (SELF%SIHEG2)
IF (LSIHEG2) THEN
  !$ACC ENTER DATA CREATE (SELF%SIHEG2)
  !$ACC UPDATE DEVICE (SELF%SIHEG2)
  !$ACC ENTER DATA ATTACH (SELF%SIHEG2)
ENDIF

LSIHEGB = ALLOCATED (SELF%SIHEGB)
IF (LSIHEGB) THEN
  !$ACC ENTER DATA CREATE (SELF%SIHEGB)
  !$ACC UPDATE DEVICE (SELF%SIHEGB)
  !$ACC ENTER DATA ATTACH (SELF%SIHEGB)
ENDIF

LSIHEGB2 = ALLOCATED (SELF%SIHEGB2)
IF (LSIHEGB2) THEN
  !$ACC ENTER DATA CREATE (SELF%SIHEGB2)
  !$ACC UPDATE DEVICE (SELF%SIHEGB2)
  !$ACC ENTER DATA ATTACH (SELF%SIHEGB2)
ENDIF

LSIFAC = ALLOCATED (SELF%SIFAC)
IF (LSIFAC) THEN
  !$ACC ENTER DATA CREATE (SELF%SIFAC)
  !$ACC UPDATE DEVICE (SELF%SIFAC)
  !$ACC ENTER DATA ATTACH (SELF%SIFAC)
ENDIF

LSIFACI = ALLOCATED (SELF%SIFACI)
IF (LSIFACI) THEN
  !$ACC ENTER DATA CREATE (SELF%SIFACI)
  !$ACC UPDATE DEVICE (SELF%SIFACI)
  !$ACC ENTER DATA ATTACH (SELF%SIFACI)
ENDIF

LSIBQ = ALLOCATED (SELF%SIBQ)
IF (LSIBQ) THEN
  !$ACC ENTER DATA CREATE (SELF%SIBQ)
  !$ACC UPDATE DEVICE (SELF%SIBQ)
  !$ACC ENTER DATA ATTACH (SELF%SIBQ)
ENDIF

LSIMITRA = ALLOCATED (SELF%SIMITRA)
IF (LSIMITRA) THEN
  !$ACC ENTER DATA CREATE (SELF%SIMITRA)
  !$ACC UPDATE DEVICE (SELF%SIMITRA)
  !$ACC ENTER DATA ATTACH (SELF%SIMITRA)
ENDIF

LSIMOTRA = ALLOCATED (SELF%SIMOTRA)
IF (LSIMOTRA) THEN
  !$ACC ENTER DATA CREATE (SELF%SIMOTRA)
  !$ACC UPDATE DEVICE (SELF%SIMOTRA)
  !$ACC ENTER DATA ATTACH (SELF%SIMOTRA)
ENDIF

LSIFACITRA = ALLOCATED (SELF%SIFACITRA)
IF (LSIFACITRA) THEN
  !$ACC ENTER DATA CREATE (SELF%SIFACITRA)
  !$ACC UPDATE DEVICE (SELF%SIFACITRA)
  !$ACC ENTER DATA ATTACH (SELF%SIFACITRA)
ENDIF

LSIHEGTRA = ALLOCATED (SELF%SIHEGTRA)
IF (LSIHEGTRA) THEN
  !$ACC ENTER DATA CREATE (SELF%SIHEGTRA)
  !$ACC UPDATE DEVICE (SELF%SIHEGTRA)
  !$ACC ENTER DATA ATTACH (SELF%SIHEGTRA)
ENDIF

LSIHEG2TRA = ALLOCATED (SELF%SIHEG2TRA)
IF (LSIHEG2TRA) THEN
  !$ACC ENTER DATA CREATE (SELF%SIHEG2TRA)
  !$ACC UPDATE DEVICE (SELF%SIHEG2TRA)
  !$ACC ENTER DATA ATTACH (SELF%SIHEG2TRA)
ENDIF

LSIHEGBTRA = ALLOCATED (SELF%SIHEGBTRA)
IF (LSIHEGBTRA) THEN
  !$ACC ENTER DATA CREATE (SELF%SIHEGBTRA)
  !$ACC UPDATE DEVICE (SELF%SIHEGBTRA)
  !$ACC ENTER DATA ATTACH (SELF%SIHEGBTRA)
ENDIF

LSIHEGB2TRA = ALLOCATED (SELF%SIHEGB2TRA)
IF (LSIHEGB2TRA) THEN
  !$ACC ENTER DATA CREATE (SELF%SIHEGB2TRA)
  !$ACC UPDATE DEVICE (SELF%SIHEGB2TRA)
  !$ACC ENTER DATA ATTACH (SELF%SIHEGB2TRA)
ENDIF

LSIHEGIND = ALLOCATED (SELF%SIHEGIND)
IF (LSIHEGIND) THEN
  !$ACC ENTER DATA CREATE (SELF%SIHEGIND)
  !$ACC UPDATE DEVICE (SELF%SIHEGIND)
  !$ACC ENTER DATA ATTACH (SELF%SIHEGIND)
ENDIF

LSIBQTRA = ALLOCATED (SELF%SIBQTRA)
IF (LSIBQTRA) THEN
  !$ACC ENTER DATA CREATE (SELF%SIBQTRA)
  !$ACC UPDATE DEVICE (SELF%SIBQTRA)
  !$ACC ENTER DATA ATTACH (SELF%SIBQTRA)
ENDIF

LSIZA = ALLOCATED (SELF%SIZA)
IF (LSIZA) THEN
  !$ACC ENTER DATA CREATE (SELF%SIZA)
  !$ACC UPDATE DEVICE (SELF%SIZA)
  !$ACC ENTER DATA ATTACH (SELF%SIZA)
ENDIF

LSIZC = ALLOCATED (SELF%SIZC)
IF (LSIZC) THEN
  !$ACC ENTER DATA CREATE (SELF%SIZC)
  !$ACC UPDATE DEVICE (SELF%SIZC)
  !$ACC ENTER DATA ATTACH (SELF%SIZC)
ENDIF

LSIPIS = ALLOCATED (SELF%SIPIS)
IF (LSIPIS) THEN
  !$ACC ENTER DATA CREATE (SELF%SIPIS)
  !$ACC UPDATE DEVICE (SELF%SIPIS)
  !$ACC ENTER DATA ATTACH (SELF%SIPIS)
ENDIF

LSITGR = ALLOCATED (SELF%SITGR)
IF (LSITGR) THEN
  !$ACC ENTER DATA CREATE (SELF%SITGR)
  !$ACC UPDATE DEVICE (SELF%SITGR)
  !$ACC ENTER DATA ATTACH (SELF%SITGR)
ENDIF

LSITAC = ALLOCATED (SELF%SITAC)
IF (LSITAC) THEN
  !$ACC ENTER DATA CREATE (SELF%SITAC)
  !$ACC UPDATE DEVICE (SELF%SITAC)
  !$ACC ENTER DATA ATTACH (SELF%SITAC)
ENDIF

LSIBI = ALLOCATED (SELF%SIBI)
IF (LSIBI) THEN
  !$ACC ENTER DATA CREATE (SELF%SIBI)
  !$ACC UPDATE DEVICE (SELF%SIBI)
  !$ACC ENTER DATA ATTACH (SELF%SIBI)
ENDIF

LRNHHY_DELTAM = ALLOCATED (SELF%RNHHY_DELTAM)
IF (LRNHHY_DELTAM) THEN
  !$ACC ENTER DATA CREATE (SELF%RNHHY_DELTAM)
  !$ACC UPDATE DEVICE (SELF%RNHHY_DELTAM)
  !$ACC ENTER DATA ATTACH (SELF%RNHHY_DELTAM)
ENDIF

CALL COPY_TSWE (SELF%YRSWE, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LRGAMMA_WENO = ALLOCATED (SELF%RGAMMA_WENO)
IF (LRGAMMA_WENO) THEN
  !$ACC ENTER DATA CREATE (SELF%RGAMMA_WENO)
  !$ACC UPDATE DEVICE (SELF%RGAMMA_WENO)
  !$ACC ENTER DATA ATTACH (SELF%RGAMMA_WENO)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TDYN (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_TSWE_MOD
IMPLICIT NONE
TYPE (TDYN), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHIDIV, LRDHIGFL, LRDHINHX, LRDHIP, LRDHISPD, LRDHISVD
LOGICAL :: LRDHIT, LRDHIVOR, LRDHS, LRDHSDIV, LRDHSNHX, LRDHSSVD, LRDHSVOR, LRDIDIV, LRDIGFL, LRDIPD
LOGICAL :: LRDISP, LRDITG, LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRGAMMA_WENO, LRGWFRIC, LRKRF
LOGICAL :: LRNHHY_DELTAM, LRSAVEDP, LSIALPH, LSIALPH_NH, LSIB, LSIBI, LSIBQ, LSIBQTRA, LSIDELP, LSIDELP_NH
LOGICAL :: LSIDPHI, LSIDPHI_NH, LSIFAC, LSIFACI, LSIFACITRA, LSIGFL, LSIGFM, LSIGHL, LSIGHM, LSIHEG
LOGICAL :: LSIHEG2, LSIHEG2TRA, LSIHEGB, LSIHEGB2, LSIHEGB2TRA, LSIHEGBTRA, LSIHEGIND, LSIHEGTRA, LSILNPR, LSILNPR_NH
LOGICAL :: LSIMI, LSIMITRA, LSIMO, LSIMOTRA, LSIPIS, LSIRDEL, LSIRDEL_NH, LSITAC, LSITFL, LSITFM
LOGICAL :: LSITGR, LSITLAF, LSITLAF_NH, LSITLAH, LSITLAH_NH, LSITRAM, LSITRM, LSIVP, LSIWF2H, LSIWH2F
LOGICAL :: LSIZA, LSIZC, LSLHD_MASK_T, LSLHD_MASK_U

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LRDIVOR = ALLOCATED (SELF%RDIVOR)
IF (LRDIVOR) THEN
  !$ACC EXIT DATA DETACH (SELF%RDIVOR)
  !$ACC EXIT DATA DETACH (SELF%RDIVOR)
ENDIF

LRDIDIV = ALLOCATED (SELF%RDIDIV)
IF (LRDIDIV) THEN
  !$ACC EXIT DATA DETACH (SELF%RDIDIV)
  !$ACC EXIT DATA DETACH (SELF%RDIDIV)
ENDIF

LRDITG = ALLOCATED (SELF%RDITG)
IF (LRDITG) THEN
  !$ACC EXIT DATA DETACH (SELF%RDITG)
  !$ACC EXIT DATA DETACH (SELF%RDITG)
ENDIF

LRDIGFL = ALLOCATED (SELF%RDIGFL)
IF (LRDIGFL) THEN
  !$ACC EXIT DATA DETACH (SELF%RDIGFL)
  !$ACC EXIT DATA DETACH (SELF%RDIGFL)
ENDIF

LRDIPD = ALLOCATED (SELF%RDIPD)
IF (LRDIPD) THEN
  !$ACC EXIT DATA DETACH (SELF%RDIPD)
  !$ACC EXIT DATA DETACH (SELF%RDIPD)
ENDIF

LRDIVD = ALLOCATED (SELF%RDIVD)
IF (LRDIVD) THEN
  !$ACC EXIT DATA DETACH (SELF%RDIVD)
  !$ACC EXIT DATA DETACH (SELF%RDIVD)
ENDIF

LRDISP = ALLOCATED (SELF%RDISP)
IF (LRDISP) THEN
  !$ACC EXIT DATA DETACH (SELF%RDISP)
  !$ACC EXIT DATA DETACH (SELF%RDISP)
ENDIF

LRDHI = ALLOCATED (SELF%RDHI)
IF (LRDHI) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHI)
  !$ACC EXIT DATA DETACH (SELF%RDHI)
ENDIF

LRDHIVOR = ALLOCATED (SELF%RDHIVOR)
IF (LRDHIVOR) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHIVOR)
  !$ACC EXIT DATA DETACH (SELF%RDHIVOR)
ENDIF

LRDHIDIV = ALLOCATED (SELF%RDHIDIV)
IF (LRDHIDIV) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHIDIV)
  !$ACC EXIT DATA DETACH (SELF%RDHIDIV)
ENDIF

LRDHISPD = ALLOCATED (SELF%RDHISPD)
IF (LRDHISPD) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHISPD)
  !$ACC EXIT DATA DETACH (SELF%RDHISPD)
ENDIF

LRDHISVD = ALLOCATED (SELF%RDHISVD)
IF (LRDHISVD) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHISVD)
  !$ACC EXIT DATA DETACH (SELF%RDHISVD)
ENDIF

LRDHINHX = ALLOCATED (SELF%RDHINHX)
IF (LRDHINHX) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHINHX)
  !$ACC EXIT DATA DETACH (SELF%RDHINHX)
ENDIF

LRDHIT = ALLOCATED (SELF%RDHIT)
IF (LRDHIT) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHIT)
  !$ACC EXIT DATA DETACH (SELF%RDHIT)
ENDIF

LRDHIGFL = ALLOCATED (SELF%RDHIGFL)
IF (LRDHIGFL) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHIGFL)
  !$ACC EXIT DATA DETACH (SELF%RDHIGFL)
ENDIF

LRDHIP = ALLOCATED (SELF%RDHIP)
IF (LRDHIP) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHIP)
  !$ACC EXIT DATA DETACH (SELF%RDHIP)
ENDIF

LRDHSVOR = ALLOCATED (SELF%RDHSVOR)
IF (LRDHSVOR) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHSVOR)
  !$ACC EXIT DATA DETACH (SELF%RDHSVOR)
ENDIF

LRDHSDIV = ALLOCATED (SELF%RDHSDIV)
IF (LRDHSDIV) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHSDIV)
  !$ACC EXIT DATA DETACH (SELF%RDHSDIV)
ENDIF

LRDHSSVD = ALLOCATED (SELF%RDHSSVD)
IF (LRDHSSVD) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHSSVD)
  !$ACC EXIT DATA DETACH (SELF%RDHSSVD)
ENDIF

LRDHSNHX = ALLOCATED (SELF%RDHSNHX)
IF (LRDHSNHX) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHSNHX)
  !$ACC EXIT DATA DETACH (SELF%RDHSNHX)
ENDIF

LRSAVEDP = ALLOCATED (SELF%RSAVEDP)
IF (LRSAVEDP) THEN
  !$ACC EXIT DATA DETACH (SELF%RSAVEDP)
  !$ACC EXIT DATA DETACH (SELF%RSAVEDP)
ENDIF

LRDSVOR = ALLOCATED (SELF%RDSVOR)
IF (LRDSVOR) THEN
  !$ACC EXIT DATA DETACH (SELF%RDSVOR)
  !$ACC EXIT DATA DETACH (SELF%RDSVOR)
ENDIF

LRDSDIV = ALLOCATED (SELF%RDSDIV)
IF (LRDSDIV) THEN
  !$ACC EXIT DATA DETACH (SELF%RDSDIV)
  !$ACC EXIT DATA DETACH (SELF%RDSDIV)
ENDIF

LRDSVD = ALLOCATED (SELF%RDSVD)
IF (LRDSVD) THEN
  !$ACC EXIT DATA DETACH (SELF%RDSVD)
  !$ACC EXIT DATA DETACH (SELF%RDSVD)
ENDIF

LRDHS = ALLOCATED (SELF%RDHS)
IF (LRDHS) THEN
  !$ACC EXIT DATA DETACH (SELF%RDHS)
  !$ACC EXIT DATA DETACH (SELF%RDHS)
ENDIF

LSLHD_MASK_U = ALLOCATED (SELF%SLHD_MASK_U)
IF (LSLHD_MASK_U) THEN
  !$ACC EXIT DATA DETACH (SELF%SLHD_MASK_U)
  !$ACC EXIT DATA DETACH (SELF%SLHD_MASK_U)
ENDIF

LSLHD_MASK_T = ALLOCATED (SELF%SLHD_MASK_T)
IF (LSLHD_MASK_T) THEN
  !$ACC EXIT DATA DETACH (SELF%SLHD_MASK_T)
  !$ACC EXIT DATA DETACH (SELF%SLHD_MASK_T)
ENDIF

LRCORDIT = ALLOCATED (SELF%RCORDIT)
IF (LRCORDIT) THEN
  !$ACC EXIT DATA DETACH (SELF%RCORDIT)
  !$ACC EXIT DATA DETACH (SELF%RCORDIT)
ENDIF

LRCORDIH = ALLOCATED (SELF%RCORDIH)
IF (LRCORDIH) THEN
  !$ACC EXIT DATA DETACH (SELF%RCORDIH)
  !$ACC EXIT DATA DETACH (SELF%RCORDIH)
ENDIF

LRCORDIF = ALLOCATED (SELF%RCORDIF)
IF (LRCORDIF) THEN
  !$ACC EXIT DATA DETACH (SELF%RCORDIF)
  !$ACC EXIT DATA DETACH (SELF%RCORDIF)
ENDIF

LRKRF = ALLOCATED (SELF%RKRF)
IF (LRKRF) THEN
  !$ACC EXIT DATA DETACH (SELF%RKRF)
  !$ACC EXIT DATA DETACH (SELF%RKRF)
ENDIF

LRGWFRIC = ALLOCATED (SELF%RGWFRIC)
IF (LRGWFRIC) THEN
  !$ACC EXIT DATA DETACH (SELF%RGWFRIC)
  !$ACC EXIT DATA DETACH (SELF%RGWFRIC)
ENDIF

LSITRAM = ALLOCATED (SELF%SITRAM)
IF (LSITRAM) THEN
  !$ACC EXIT DATA DETACH (SELF%SITRAM)
  !$ACC EXIT DATA DETACH (SELF%SITRAM)
ENDIF

LSITRM = ALLOCATED (SELF%SITRM)
IF (LSITRM) THEN
  !$ACC EXIT DATA DETACH (SELF%SITRM)
  !$ACC EXIT DATA DETACH (SELF%SITRM)
ENDIF

LSIALPH = ALLOCATED (SELF%SIALPH)
IF (LSIALPH) THEN
  !$ACC EXIT DATA DETACH (SELF%SIALPH)
  !$ACC EXIT DATA DETACH (SELF%SIALPH)
ENDIF

LSILNPR = ALLOCATED (SELF%SILNPR)
IF (LSILNPR) THEN
  !$ACC EXIT DATA DETACH (SELF%SILNPR)
  !$ACC EXIT DATA DETACH (SELF%SILNPR)
ENDIF

LSIDELP = ALLOCATED (SELF%SIDELP)
IF (LSIDELP) THEN
  !$ACC EXIT DATA DETACH (SELF%SIDELP)
  !$ACC EXIT DATA DETACH (SELF%SIDELP)
ENDIF

LSIRDEL = ALLOCATED (SELF%SIRDEL)
IF (LSIRDEL) THEN
  !$ACC EXIT DATA DETACH (SELF%SIRDEL)
  !$ACC EXIT DATA DETACH (SELF%SIRDEL)
ENDIF

LSITLAH = ALLOCATED (SELF%SITLAH)
IF (LSITLAH) THEN
  !$ACC EXIT DATA DETACH (SELF%SITLAH)
  !$ACC EXIT DATA DETACH (SELF%SITLAH)
ENDIF

LSITLAF = ALLOCATED (SELF%SITLAF)
IF (LSITLAF) THEN
  !$ACC EXIT DATA DETACH (SELF%SITLAF)
  !$ACC EXIT DATA DETACH (SELF%SITLAF)
ENDIF

LSIDPHI = ALLOCATED (SELF%SIDPHI)
IF (LSIDPHI) THEN
  !$ACC EXIT DATA DETACH (SELF%SIDPHI)
  !$ACC EXIT DATA DETACH (SELF%SIDPHI)
ENDIF

LSIALPH_NH = ALLOCATED (SELF%SIALPH_NH)
IF (LSIALPH_NH) THEN
  !$ACC EXIT DATA DETACH (SELF%SIALPH_NH)
  !$ACC EXIT DATA DETACH (SELF%SIALPH_NH)
ENDIF

LSILNPR_NH = ALLOCATED (SELF%SILNPR_NH)
IF (LSILNPR_NH) THEN
  !$ACC EXIT DATA DETACH (SELF%SILNPR_NH)
  !$ACC EXIT DATA DETACH (SELF%SILNPR_NH)
ENDIF

LSIDELP_NH = ALLOCATED (SELF%SIDELP_NH)
IF (LSIDELP_NH) THEN
  !$ACC EXIT DATA DETACH (SELF%SIDELP_NH)
  !$ACC EXIT DATA DETACH (SELF%SIDELP_NH)
ENDIF

LSIRDEL_NH = ALLOCATED (SELF%SIRDEL_NH)
IF (LSIRDEL_NH) THEN
  !$ACC EXIT DATA DETACH (SELF%SIRDEL_NH)
  !$ACC EXIT DATA DETACH (SELF%SIRDEL_NH)
ENDIF

LSITLAH_NH = ALLOCATED (SELF%SITLAH_NH)
IF (LSITLAH_NH) THEN
  !$ACC EXIT DATA DETACH (SELF%SITLAH_NH)
  !$ACC EXIT DATA DETACH (SELF%SITLAH_NH)
ENDIF

LSITLAF_NH = ALLOCATED (SELF%SITLAF_NH)
IF (LSITLAF_NH) THEN
  !$ACC EXIT DATA DETACH (SELF%SITLAF_NH)
  !$ACC EXIT DATA DETACH (SELF%SITLAF_NH)
ENDIF

LSIDPHI_NH = ALLOCATED (SELF%SIDPHI_NH)
IF (LSIDPHI_NH) THEN
  !$ACC EXIT DATA DETACH (SELF%SIDPHI_NH)
  !$ACC EXIT DATA DETACH (SELF%SIDPHI_NH)
ENDIF

LSIWF2H = ALLOCATED (SELF%SIWF2H)
IF (LSIWF2H) THEN
  !$ACC EXIT DATA DETACH (SELF%SIWF2H)
  !$ACC EXIT DATA DETACH (SELF%SIWF2H)
ENDIF

LSIWH2F = ALLOCATED (SELF%SIWH2F)
IF (LSIWH2F) THEN
  !$ACC EXIT DATA DETACH (SELF%SIWH2F)
  !$ACC EXIT DATA DETACH (SELF%SIWH2F)
ENDIF

LSIGFL = ALLOCATED (SELF%SIGFL)
IF (LSIGFL) THEN
  !$ACC EXIT DATA DETACH (SELF%SIGFL)
  !$ACC EXIT DATA DETACH (SELF%SIGFL)
ENDIF

LSIGFM = ALLOCATED (SELF%SIGFM)
IF (LSIGFM) THEN
  !$ACC EXIT DATA DETACH (SELF%SIGFM)
  !$ACC EXIT DATA DETACH (SELF%SIGFM)
ENDIF

LSITFL = ALLOCATED (SELF%SITFL)
IF (LSITFL) THEN
  !$ACC EXIT DATA DETACH (SELF%SITFL)
  !$ACC EXIT DATA DETACH (SELF%SITFL)
ENDIF

LSITFM = ALLOCATED (SELF%SITFM)
IF (LSITFM) THEN
  !$ACC EXIT DATA DETACH (SELF%SITFM)
  !$ACC EXIT DATA DETACH (SELF%SITFM)
ENDIF

LSIGHL = ALLOCATED (SELF%SIGHL)
IF (LSIGHL) THEN
  !$ACC EXIT DATA DETACH (SELF%SIGHL)
  !$ACC EXIT DATA DETACH (SELF%SIGHL)
ENDIF

LSIGHM = ALLOCATED (SELF%SIGHM)
IF (LSIGHM) THEN
  !$ACC EXIT DATA DETACH (SELF%SIGHM)
  !$ACC EXIT DATA DETACH (SELF%SIGHM)
ENDIF

LSIB = ALLOCATED (SELF%SIB)
IF (LSIB) THEN
  !$ACC EXIT DATA DETACH (SELF%SIB)
  !$ACC EXIT DATA DETACH (SELF%SIB)
ENDIF

LSIMO = ALLOCATED (SELF%SIMO)
IF (LSIMO) THEN
  !$ACC EXIT DATA DETACH (SELF%SIMO)
  !$ACC EXIT DATA DETACH (SELF%SIMO)
ENDIF

LSIMI = ALLOCATED (SELF%SIMI)
IF (LSIMI) THEN
  !$ACC EXIT DATA DETACH (SELF%SIMI)
  !$ACC EXIT DATA DETACH (SELF%SIMI)
ENDIF

LSIVP = ALLOCATED (SELF%SIVP)
IF (LSIVP) THEN
  !$ACC EXIT DATA DETACH (SELF%SIVP)
  !$ACC EXIT DATA DETACH (SELF%SIVP)
ENDIF

LSIHEG = ALLOCATED (SELF%SIHEG)
IF (LSIHEG) THEN
  !$ACC EXIT DATA DETACH (SELF%SIHEG)
  !$ACC EXIT DATA DETACH (SELF%SIHEG)
ENDIF

LSIHEG2 = ALLOCATED (SELF%SIHEG2)
IF (LSIHEG2) THEN
  !$ACC EXIT DATA DETACH (SELF%SIHEG2)
  !$ACC EXIT DATA DETACH (SELF%SIHEG2)
ENDIF

LSIHEGB = ALLOCATED (SELF%SIHEGB)
IF (LSIHEGB) THEN
  !$ACC EXIT DATA DETACH (SELF%SIHEGB)
  !$ACC EXIT DATA DETACH (SELF%SIHEGB)
ENDIF

LSIHEGB2 = ALLOCATED (SELF%SIHEGB2)
IF (LSIHEGB2) THEN
  !$ACC EXIT DATA DETACH (SELF%SIHEGB2)
  !$ACC EXIT DATA DETACH (SELF%SIHEGB2)
ENDIF

LSIFAC = ALLOCATED (SELF%SIFAC)
IF (LSIFAC) THEN
  !$ACC EXIT DATA DETACH (SELF%SIFAC)
  !$ACC EXIT DATA DETACH (SELF%SIFAC)
ENDIF

LSIFACI = ALLOCATED (SELF%SIFACI)
IF (LSIFACI) THEN
  !$ACC EXIT DATA DETACH (SELF%SIFACI)
  !$ACC EXIT DATA DETACH (SELF%SIFACI)
ENDIF

LSIBQ = ALLOCATED (SELF%SIBQ)
IF (LSIBQ) THEN
  !$ACC EXIT DATA DETACH (SELF%SIBQ)
  !$ACC EXIT DATA DETACH (SELF%SIBQ)
ENDIF

LSIMITRA = ALLOCATED (SELF%SIMITRA)
IF (LSIMITRA) THEN
  !$ACC EXIT DATA DETACH (SELF%SIMITRA)
  !$ACC EXIT DATA DETACH (SELF%SIMITRA)
ENDIF

LSIMOTRA = ALLOCATED (SELF%SIMOTRA)
IF (LSIMOTRA) THEN
  !$ACC EXIT DATA DETACH (SELF%SIMOTRA)
  !$ACC EXIT DATA DETACH (SELF%SIMOTRA)
ENDIF

LSIFACITRA = ALLOCATED (SELF%SIFACITRA)
IF (LSIFACITRA) THEN
  !$ACC EXIT DATA DETACH (SELF%SIFACITRA)
  !$ACC EXIT DATA DETACH (SELF%SIFACITRA)
ENDIF

LSIHEGTRA = ALLOCATED (SELF%SIHEGTRA)
IF (LSIHEGTRA) THEN
  !$ACC EXIT DATA DETACH (SELF%SIHEGTRA)
  !$ACC EXIT DATA DETACH (SELF%SIHEGTRA)
ENDIF

LSIHEG2TRA = ALLOCATED (SELF%SIHEG2TRA)
IF (LSIHEG2TRA) THEN
  !$ACC EXIT DATA DETACH (SELF%SIHEG2TRA)
  !$ACC EXIT DATA DETACH (SELF%SIHEG2TRA)
ENDIF

LSIHEGBTRA = ALLOCATED (SELF%SIHEGBTRA)
IF (LSIHEGBTRA) THEN
  !$ACC EXIT DATA DETACH (SELF%SIHEGBTRA)
  !$ACC EXIT DATA DETACH (SELF%SIHEGBTRA)
ENDIF

LSIHEGB2TRA = ALLOCATED (SELF%SIHEGB2TRA)
IF (LSIHEGB2TRA) THEN
  !$ACC EXIT DATA DETACH (SELF%SIHEGB2TRA)
  !$ACC EXIT DATA DETACH (SELF%SIHEGB2TRA)
ENDIF

LSIHEGIND = ALLOCATED (SELF%SIHEGIND)
IF (LSIHEGIND) THEN
  !$ACC EXIT DATA DETACH (SELF%SIHEGIND)
  !$ACC EXIT DATA DETACH (SELF%SIHEGIND)
ENDIF

LSIBQTRA = ALLOCATED (SELF%SIBQTRA)
IF (LSIBQTRA) THEN
  !$ACC EXIT DATA DETACH (SELF%SIBQTRA)
  !$ACC EXIT DATA DETACH (SELF%SIBQTRA)
ENDIF

LSIZA = ALLOCATED (SELF%SIZA)
IF (LSIZA) THEN
  !$ACC EXIT DATA DETACH (SELF%SIZA)
  !$ACC EXIT DATA DETACH (SELF%SIZA)
ENDIF

LSIZC = ALLOCATED (SELF%SIZC)
IF (LSIZC) THEN
  !$ACC EXIT DATA DETACH (SELF%SIZC)
  !$ACC EXIT DATA DETACH (SELF%SIZC)
ENDIF

LSIPIS = ALLOCATED (SELF%SIPIS)
IF (LSIPIS) THEN
  !$ACC EXIT DATA DETACH (SELF%SIPIS)
  !$ACC EXIT DATA DETACH (SELF%SIPIS)
ENDIF

LSITGR = ALLOCATED (SELF%SITGR)
IF (LSITGR) THEN
  !$ACC EXIT DATA DETACH (SELF%SITGR)
  !$ACC EXIT DATA DETACH (SELF%SITGR)
ENDIF

LSITAC = ALLOCATED (SELF%SITAC)
IF (LSITAC) THEN
  !$ACC EXIT DATA DETACH (SELF%SITAC)
  !$ACC EXIT DATA DETACH (SELF%SITAC)
ENDIF

LSIBI = ALLOCATED (SELF%SIBI)
IF (LSIBI) THEN
  !$ACC EXIT DATA DETACH (SELF%SIBI)
  !$ACC EXIT DATA DETACH (SELF%SIBI)
ENDIF

LRNHHY_DELTAM = ALLOCATED (SELF%RNHHY_DELTAM)
IF (LRNHHY_DELTAM) THEN
  !$ACC EXIT DATA DETACH (SELF%RNHHY_DELTAM)
  !$ACC EXIT DATA DETACH (SELF%RNHHY_DELTAM)
ENDIF

CALL WIPE_TSWE (SELF%YRSWE, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LRGAMMA_WENO = ALLOCATED (SELF%RGAMMA_WENO)
IF (LRGAMMA_WENO) THEN
  !$ACC EXIT DATA DETACH (SELF%RGAMMA_WENO)
  !$ACC EXIT DATA DETACH (SELF%RGAMMA_WENO)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
