MODULE YOEAERC_TEGEN

!$ACDC methods

USE PARKIND1,ONLY : JPIM,JPRB

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------
!*    ** *YOEAERC* - TEGEN/GISS AEROSOL CLIMATOLOGY
!     ------------------------------------------------------------------

INTEGER(KIND=JPIM), PARAMETER :: NFDECSO4DIM=185 , NLDECSO4DIM=210
INTEGER(KIND=JPIM), PARAMETER :: ISHIST=1850, IEHIST=2100, INLAT=24


TYPE :: TEAERC_TEGEN
REAL(KIND=JPRB) :: REPAER = -HUGE(1._JPRB)
REAL(KIND=JPRB), POINTER, DIMENSION(:,:,:) :: RAERBC => NULL(), RAEROR => NULL(), RAERSD => NULL()
REAL(KIND=JPRB), POINTER, DIMENSION(:,:,:) :: RAERSS => NULL(), RAERSU => NULL()
REAL(KIND=JPRB), POINTER, DIMENSION(:,:,:) :: RAERV  => NULL()
REAL(KIND=JPRB), POINTER, DIMENSION(:)     :: RLATV  => NULL()
REAL(KIND=JPRB) :: RTAEBC(72,46), RTAEOR(72,46), RTAESD(72,46)
REAL(KIND=JPRB) :: RTAESS(72,46), RTAESU(72,46), RTAEVO(46)
INTEGER(KIND=JPIM) :: ISYEAR=ISHIST, IEYEAR=IEHIST

LOGICAL :: IS_INITIALISED = .FALSE.

END TYPE TEAERC_TEGEN

END MODULE YOEAERC_TEGEN

